### ISSUE TITLE
Support float zoomlevel

### ISSUE THREAD

**Issue by liaoaoyang** [osmdroid/osmdroid#296] opened 2016-04-09 08:53 UTC
Hello

I wonder whether there is any plan to add float `zoomlevel` support?

Sometimes when use two fingers to zoom in/out the map, `zoomlevel` only change from an `int` to another `int`, it seems like the the map is trembling.

I read the source code and I found that the variable which represent `zoomlevel` is `int`.

And thanks for your great work on osmdroid.

**Comment by wildfiregt** [comment] 2016-04-09 16:32
All I can help you with is this code 
`        final float scale = getBaseContext().getResources().getDisplayMetrics().density;
        final int newScale = (int) (256 * scale);
        String[] OSMSource = new String[2];
        OSMSource[0] = "http://a.tile.openstreetmap.org/";
        OSMSource[1] = "http://b.tile.openstreetmap.org/";
        XYTileSource MapSource = new XYTileSource("OSM", 1, 18, newScale, ".png", OSMSource);
        map.setTileSource(MapSource);`

This will zoom every tile. Tweak the scale as your needs

**Comment by liaoaoyang** [comment] 2016-04-10 06:21
@wildfiregt Thanks for your answer first, I've already wrote in this way and it doesn't work on my app.

**Comment by spyhunter99** [comment] 2016-04-10 12:16
In the plan? Well unlikely at this point. We're pretty tied to osm, which uses discrete zoom levels.

**Comment by liaoaoyang** [comment] 2016-04-10 15:51
@spyhunter99 Thanks for your reply and I may try some other ways

**Comment by spyhunter99** [comment] 2016-04-10 16:10
for what it's worth, it looks like NASA has been doing some more work on
WorldWind for Android. Worth checking out

**Comment by kjeremy** [comment] 2016-04-15 18:29
You could probably use floats and just round to the nearest int for osm sources.  Other tile sources use floating zoom levels.  As a general comment the lack of floating point in osmdroid is very frustrating if you need to represent anything with cm accuracy.

**Comment by spyhunter99** [comment] 2016-04-15 23:27
there's a branch called "doubles" which changes everything to use doubles for positioning things. Floats won't give you better accuracy because the level is precision is no more than integer.

**Comment by MKergall** [comment] 2016-05-06 20:57
It would really make sense to have a float zoom level. This would allow much graceful pinch-to-zoom. 
On intermediate levels, it implies to apply appropriate scale factor on the closest tiles set. 

When MapBox made its [fork of osmdroid](https://github.com/mapbox/mapbox-android-sdk-legacy), they implemented this. 
Have a look at the [Projection](https://github.com/mapbox/mapbox-android-sdk-legacy/blob/mb-pages/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/util/Projection.java) class for instance.

**Comment by spyhunter99** [comment] 2016-05-27 00:22
If someone wants to attempt to port the mapbox changes over and open a PR, it will definitely get reviewed and probably merged. I'd suggest to keep the existing discrete zoom levels to aid with backwards compat

**Comment by ivangorelow** [comment] 2016-07-26 16:36
Do you have any solutions??

**Comment by ivangorelow** [comment] 2016-07-28 11:32
will you solve this problem or not&

**Comment by ivangorelow** [comment] 2016-07-28 11:36
I think it's a big problem. I like your library, but nowadays I can't use your library, because users won't feel satisfied, when they see such an AWFUL pinch zoom!

**Comment by spyhunter99** [comment] 2016-07-28 11:37
osmdroid thrives by contributions from the community. We are primarily volunteers. I don't believe anyone gets paid to support osmdroid as part of their day job. As such, any contribution is welcome.

**Comment by spyhunter99** [comment] 2017-08-28 01:20
this is a duplicate of #640 which has been merged

**Closed by spyhunter99** 2017-08-28 01:20 UTC
Labels: enhancement
