### ISSUE TITLE
MapsForgeTileProvider yellow tiles

### ISSUE THREAD

**Issue by iillyyaa2033** [osmdroid/osmdroid#510] opened 2016-12-29 08:51 UTC
Hello!
I'm trying to write simple android app using osmdroid and offline Mapsforge .map files.
  - Osmdroid libraries v5.2,
  - app tested on devices with android 4.3, 5.1.1 and 6.1,
  - .map file is valid (it can be shown using only mapsforge libraries)
  - path to .map file is valid
  - code copied from [osmdroid sample](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-forge-app/src/main/java/org/osmdroid/forge/app/MainActivity.java)

But I got yellow screen. All cached tiles also yellow.

Screenshot from tablet with Android 6:
![screenshot_20161229-113603](https://cloud.githubusercontent.com/assets/17745136/21539990/a90c121e-cdb4-11e6-858c-b80ca147252a.png)

**Comment by spyhunter99** [comment] 2016-12-29 13:49
does the sample osmdroid forge app work?

**Comment by iillyyaa2033** [comment] 2017-01-01 20:24
I've got same problem when have builded myself. Prebuilded app works fine.

**Comment by spyhunter99** [comment] 2017-01-01 21:16
if the sample app works, there's probably nothing wrong with the library. Is your app on github? Also worth looking at, if you have a maps forge .map file that is only for a specific region, then make sure you tell osmdroid to center on that location and zoom to an appropriate level in onActivityCreated or afterwards.

**Comment by iillyyaa2033** [comment] 2017-01-03 20:34
Looks like my english is too bad. Sorry.
  - The sample app doesnt works when I compiled it myself.
  - About month (or two) ago I've found prebuilded sample. It works fine.
  - No, this sources havent uploaded to github yet.
  - Yes, my .map is regional. But map centered on my location.
  - Also, built-in map sources - online OSM -  works fine.
  - I'm building my free-time projects on Android with AIDE, java 7. Maybe it can help.

**Comment by spyhunter99** [comment] 2017-01-03 23:55
Just ran the latest version and it worked with the sample "world.map" file. Did you grant the app storage permissions on API23+? You may have to restart the app for changes to take effect. What API level is the device? The sample app scans all mounted storage paths osmdroid/*.map, so...
/sdcard/osmdroid/*.map
/storage/extSdCard/osmdroid/*.map
/storage/xyz/osmdroid/*.map

**Comment by spyhunter99** [comment] 2017-01-14 03:06
@illarionov  ping, any updates?

**Comment by iillyyaa2033** [comment] 2017-01-14 11:27
@spyhunter99, are you talking with me?

Updates? Not yet. But I'll do it next week.

**Comment by spyhunter99** [comment] 2017-09-20 23:01
closing this for now. i can't reproduce it

**Closed by spyhunter99** 2017-09-20 23:01 UTC
Labels: waiting for feedback
