### ISSUE TITLE
Setting Icon resets previously set Anchor 

### ISSUE THREAD

**Issue by EdgarK** [osmdroid/osmdroid#1104] opened 2018-07-20 09:47 UTC
## Issue Type

[ ] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
method "public void setIcon(final Drawable icon)" contains lines "setAnchor(0.5f, 0.5f);" which makes previously set anchor reset. 
The suggestion is to remove those since othervise one would always need to set anchor after changing the icon.

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment] 2018-07-20 15:00
@EdgarK My 2 cents: I'd rather say that we would need a new method `Marker.setIcon(Drawable icon, float anchorU, float anchorV)`. Would that be OK with you?

**Comment by EdgarK** [comment] 2018-07-20 15:07
In my particular case it won't be that useful, since I am constantly changing icons that only differ in their colours hence need the same anchor. But the way you are proposing would be definitely much more clearly stating that anchor will change while changing the icon.

**Comment by monsieurtanuki** [comment] 2018-07-20 15:45
@EdgarK Looking thoroughly at the code of method `Marker.setIcon(Drawable icon)`, I see that it's divided in 4 cases:
1. if the icon is null, there's a title and the "replace null icon with text bitmap" flags are true, then you display the text as a bitmap and you set the anchors
1. if the icon is not null and the "text as bitmap" flags are both false, then you set the icon AND you reset the anchors
1. if the icon is not null, then you set the icon BUT you don't reset the anchors
1. if the icon is null, you use the default icon with its default anchors

By default, both "text as bitmap" flags (`Marker.mEnableTextLabelsWhenNoImage` and static `Marker.ENABLE_TEXT_LABELS_WHEN_NO_IMAGE`) are false.
I guess it's the same in your case. Therefore with a not null icon you are in case 2, which resets the anchors.
Does it make sense to have a different behavior in cases 2 (resetting the anchors to default values) and 3 (no anchor reset)? I don't think so.

I have 2 distinct suggestions:
* in your specific case, without editing the `Marker` class code, adding `Marker.ENABLE_TEXT_LABELS_WHEN_NO_IMAGE = true;` in your code (yes, this `static` member is `public`...) should make `setIcon` work the way you want
* in general, fix that discrepancy and edit `Marker.setIcon` with only 3 cases (icon is not null - where we don't reset the anchors, "text as bitmap" flags are true, and default icon) - but it would be in contradiction with #945 - wouldn't it, @spyhunter99?

**Comment by MKergall** [comment] 2018-07-20 16:32
I also noticed this bug in 6.0.2, but didn't found the root cause yet. 

My point of view: 
There is a setAnchor method, I don't see any reason to get rid of user choice inside setIcon. 

So, in case 1 and case 2, call to setAnchor is definitely a bug (introduced with #945), it should be removed. 

The only setAnchor that could be kept is in case 4, as this is for the default icon only.

**Comment by monsieurtanuki** [comment] 2018-07-20 17:06
I don't agree 100% with case 1 being a bug, as I assume (ANCHOR_CENTER, ANCHOR_CENTER) would be more appropriate for text than the default (ANCHOR_CENTER, ANCHOR_BOTTOM).
Disclaimer: I never used that text/icon feature and didn't even know it existed. It's a nice feature btw.

What is a bit lousy anyway is this `setIcon(null)` code that implicitly and in some conditions draws a text instead. Something like `setTitleAsIcon()` or `setTextAsIcon(String text)` would be more explicit and more self explanatory.

**Comment by MKergall** [comment] 2018-07-20 19:53
Default anchor is already ANCHOR_CENTER, ANCHOR_CENTER. 
So if the user set something else wih setAnchor, it is probably intentional and should not be changed by setIcon. 

Fully agree that API for the text feature is not very clear and could be improved.

**Comment by monsieurtanuki** [comment] 2018-07-21 13:13
Just PR'ed #1105

**Comment by monsieurtanuki** [comment] 2018-08-03 09:35
@EdgarK Fixed by merged #1105.

**Closed by monsieurtanuki** 2018-08-03 09:35 UTC
