### ISSUE TITLE
ArrayIndexOutOfBoundsException in osmdroid

### ISSUE THREAD

**Issue by abinpaul1** [osmdroid/osmdroid#1739] opened 2021-09-07 10:32 UTC
## Issue Type

[ ] Question
[ X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

A sample project to reproduce the error can be found at 
(https://github.com/abinpaul1/Android-Snippets/tree/e9c69a3a6a40e285caa5b6252f6f6bd7e579a6d1)
Importing to Android Studio and running would be sufficient.

The sample above does the following:
 - Adds a marker with a point to mapview
 -  Takes a snapshot of the mapview
 -  Removes the current marker and adds new one
This is done for an array of points read from a GPX file.

The crash can be triggered by starting the snapshoting by clicking the button. After a while (crash happens randomly), osmdroid throws the exception.

The full stack trace is also given below

### If it's a bug, version(s) of android this affects:
 - Tested on Pixel emulator with Android 11
 -  Poco X3 pro - MIUI 12.5 (Android 11)
 - Android 8 on Samsung J7 Prime

### Version of osmdroid the issue relates to:
6.1.5, 6.1.10 (possibly all)

```java
FATAL EXCEPTION: Thread-785
    Process: com.example.osm_mapviewscreenshot, PID: 8093
    java.lang.ArrayIndexOutOfBoundsException: length=256; index=257
        at org.osmdroid.util.LineBuilder.add(LineBuilder.java:24)
        at org.osmdroid.util.SegmentClipper.nextVertex(SegmentClipper.java:181)
        at org.osmdroid.util.SegmentClipper.clip(SegmentClipper.java:97)
        at org.osmdroid.util.SegmentClipper.add(SegmentClipper.java:57)
        at org.osmdroid.views.overlay.LinearRing.clipAndStore(LinearRing.java:338)
        at org.osmdroid.views.overlay.LinearRing.buildLinePortion(LinearRing.java:234)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.drawWithLines(PolyOverlayWithIW.java:207)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.draw(PolyOverlayWithIW.java:164)
        at org.osmdroid.views.drawing.MapSnapshot.draw(MapSnapshot.java:147)
        at org.osmdroid.views.drawing.MapSnapshot.refresh(MapSnapshot.java:190)
        at org.osmdroid.views.drawing.MapSnapshot.refreshASAP(MapSnapshot.java:246)
        at org.osmdroid.views.drawing.MapSnapshot.run(MapSnapshot.java:110)
        at java.lang.Thread.run(Thread.java:923)
2021-09-07 15:34:00.166 8093-8093/com.example.osm_mapviewscreenshot E/OsmDroid: error dispatchDraw, probably in edit mode
    java.lang.ArrayIndexOutOfBoundsException: length=256; index=256
        at org.osmdroid.util.LineBuilder.add(LineBuilder.java:25)
        at org.osmdroid.util.SegmentClipper.nextVertex(SegmentClipper.java:181)
        at org.osmdroid.util.SegmentClipper.clip(SegmentClipper.java:83)
        at org.osmdroid.util.SegmentClipper.add(SegmentClipper.java:57)
        at org.osmdroid.views.overlay.LinearRing.clipAndStore(LinearRing.java:338)
        at org.osmdroid.views.overlay.LinearRing.buildLinePortion(LinearRing.java:234)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.drawWithLines(PolyOverlayWithIW.java:207)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.draw(PolyOverlayWithIW.java:164)
        at org.osmdroid.views.overlay.Overlay.draw(Overlay.java:141)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDrawHelper(DefaultOverlayManager.java:181)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:139)
        at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1235)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22353)
        at com.android.internal.policy.DecorView.draw(DecorView.java:806)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4101)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3828)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by monsieurtanuki** [comment] 2021-09-07 16:54
@abinpaul1 It looks like the problem comes from the polyline you want to display with all the markers, when you reach the number of 256 markers (or something like that).
To confirm that, could you add logs counting the number of points, and try without the polyline?
I don't know either if it's caused by the snapshot: could you try with just the mapview but without the snapshot bitmap copy?
An additional idea: create a new polyline instead of reusing the same.
The way you're doing things, there might be a collision between your bitmap creation due to the snapshot, and the actual screen refresh, in more or less async mode (you cannot prevent the screen from being refreshed while you're snapshoting). I think it's possible to use a `MapSnapshot` without an underlying `MapView`: that would be much cleaner.
Tell me if it works.

**Comment by abinpaul1** [comment] 2021-09-09 12:28
The sample consists of a total of around 1700 points. It tries to snapshot each one with a marker (one at a time) them along with the polyline. So basically in each snapshot there are two overlays the Polyline and the Marker.
Okay, I tried the following out:
- Each time I clear the overlays and add a new polyline - This still caused the same crash
- Removed polylines (only marker present) - Crashes after taking some snapshots but doesnt throw any kind of error
- Removed the code for saving the snapshot to png file - Crashes without throwing error
- I removed the MapSnapshot completely and just created a runnable to update the map with marker and line every 1 ms .
 In the code I changed the `capture_screenshot` function to the below code. This works smoothly. Map is updated periodically for all the points.
 ```java
 private void capture_snapshot() {
        if (trackPointsIterator.hasNext()) {
            TrackPoint t = trackPointsIterator.next();
            Double lat = t.getLatitude();
            Double lon = t.getLongitude();
            new Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            schedule_snapshot(new GeoPoint(lat, lon));
                        }
                    });
                }
            }, 1);
        }
    }
```

I think the problem has something to do with the threads being created to take snapshot.

**Comment by monsieurtanuki** [comment] 2021-09-09 19:56
> I think the problem has something to do with the threads being created to take snapshot.

That's more or less what I was mentioning at the end of my previous comment: the problem may come from the fact that you're editing the same overlays that are being used for the display (MapView), for the callback (MapSnapshot) and for the bitmap copy.

You'd be better off splitting both actions:
1. use a MapView that displays nothing (or a Projection), that is centered around the successive GeoPoints
2. use a MapSnapshot that triggers, when all the tiles are there, the snapshot of a **brand new MapView with polyline**

The first MapView would be the "master" ("I know when a new MapView can be snapshot"), and the others successive MapViews are just there for the actual bitmap copy.

Anyway, if it's an occasional need your 1-second strategy looks good enough.

**Comment by abinpaul1** [comment] 2021-09-11 18:11
Sorry for the delay. I was trying to figure out how to do the second strategy you mentioned. So I modified the code to the below snippet. A master Mapview and then I snapshot a new Mapview with polylines and marker. 
```java
MapView map = new MapView(getApplicationContext());
MapTileProviderBase mapTileProviderBase = new MapTileProviderBasic(getApplicationContext());

for (int i =0; i< gpxTrackPoints.size(); ++i){
    Double lat = gpxTrackPoints.get(i).getLatitude();
    Double lon = gpxTrackPoints.get(i).getLongitude();
    GeoPoint pt = new GeoPoint(lat,lon);


    Polyline line = new Polyline();
    line.setPoints(pts);

    Marker marker = new Marker(map);
    marker.setPosition(new GeoPoint(lat,lon));
    marker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
    marker.setDefaultIcon();

    List<Overlay> mOverlay = new ArrayList<>();
    mOverlay.add(line);
    mOverlay.add(marker);


    Projection mProjection = new Projection(15.00, 800, 800, pt, 0, true, true, 0, 0);

    final MapSnapshot mapSnapshot = new MapSnapshot(new MapSnapshot.MapSnapshotable() {
        @Override
        public void callback(final MapSnapshot pMapSnapshot) {
            // Save the current snapshot

            if (pMapSnapshot.getStatus() != MapSnapshot.Status.CANVAS_OK) {
                return;
            }

            String img_name = "map-" + System.currentTimeMillis() + ".png";
            File file = new File(path, img_name);
            pMapSnapshot.save(file);
        }
    }, MapSnapshot.INCLUDE_FLAG_UPTODATE, mapTileProviderBase, mOverlay, mProjection);
    executorService.submit(mapSnapshot);
}
```
But this code throws the following error after about 120 location points. Again I guess it has something to do with too many threads being created from the activity.
```java
2021-09-11 22:49:15.181 27855-27926/com.example.gps_app E/AndroidRuntime: FATAL EXCEPTION: approximater
    Process: com.example.gps_app, PID: 27855
    java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
        at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
        at org.osmdroid.tileprovider.MapTileProviderBase.mapTileRequestExpiredTile(MapTileProviderBase.java:222)
        at org.osmdroid.tileprovider.MapTileProviderArray.mapTileRequestExpiredTile(MapTileProviderArray.java:173)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.tileLoadedScaled(MapTileModuleProviderBase.java:299)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```
So I thought the solution would be to move the snapshoting to the background. I created a Foreground Service to do the same [ForegroundService.java](https://github.com/abinpaul1/Android-Snippets/blob/osm_crash/OSM_MapViewScreenshot/app/src/main/java/com/example/osm_mapviewscreenshot/ForegroundService.java).  It does run for quite sometime but eventually it does crash. Also even when run in background the main thread UI freezes. I should mention that for a lucky single time it did complete all points :). But it crashed midway all other times after displaying warnings like given below in the logs.
```java
2021-09-11 23:13:21.229 13738-13795/com.example.osm_mapviewscreenshot W/pviewscreensho: Long monitor contention with owner assets (13792) at void org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.loadMapTileAsync(org.osmdroid.tileprovider.MapTileRequestState)(MapTileModuleProviderBase.java:152) waiters=4 in void org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.removeTileFromQueues(long) for 1.462s
2021-09-11 23:13:21.229 13738-13797/com.example.osm_mapviewscreenshot W/pviewscreensho: Long monitor contention with owner assets (13792) at void org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.loadMapTileAsync(org.osmdroid.tileprovider.MapTileRequestState)(MapTileModuleProviderBase.java:152) waiters=5 in org.osmdroid.tileprovider.MapTileRequestState org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.nextTile() for 1.342s
2021-09-11 23:13:21.230 13738-13794/com.example.osm_mapviewscreenshot W/pviewscreensho: Long monitor contention with owner assets (13792) at void org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.loadMapTileAsync(org.osmdroid.tileprovider.MapTileRequestState)(MapTileModuleProviderBase.java:152) waiters=7 in org.osmdroid.tileprovider.MapTileRequestState org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.nextTile() for 1.214s
2021-09-11 23:13:21.230 13738-13799/com.example.osm_mapviewscreenshot W/pviewscreensho: Long monitor contention with owner assets (13792) at void org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.loadMapTileAsync(org.osmdroid.tileprovider.MapTileRequestState)(MapTileModuleProviderBase.java:152) waiters=8 in org.osmdroid.tileprovider.MapTileRequestState org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.nextTile() for 1.211s
2021-09-11 23:13:21.230 13738-13801/com.example.osm_mapviewscreenshot W/pviewscreensho: Long monitor contention with owner assets (13792) at void org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.loadMapTileAsync(org.osmdroid.tileprovider.MapTileRequestState)(MapTileModuleProviderBase.java:152) waiters=3 in void org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.removeTileFromQueues(long) for 3.710s
2021-09-11 23:16:47.137 13738-13794/com.example.osm_mapviewscreenshot W/pviewscreensho: Long monitor contention with owner sqlcache (13800) at boolean android.os.MessageQueue.enqueueMessage(android.os.Message, long)(MessageQueue.java:603) waiters=7 in boolean android.os.MessageQueue.enqueueMessage(android.os.Message, long) for 511ms

```
I'm not entirely sure what the problem here is. It might be running too many threads at once. I'm not sure. But the warnings show something related to `MapTileModuleProviderBase.loadMapTileAsync` so I thought I'll mention it. Do let me know if this falls outside the purview of osmdroid (or if i should create a new issue with this).

**Comment by monsieurtanuki** [comment] 2021-09-12 07:07
What do you mean, "several threads at once"? Just run one `MapSnapshot` at a time. The point of my previous comment was not only to separate a master MapView from snapshots, but to avoid concurrency issues.
I don't think you even need a `MapView` now, as long as you use a `Projection` for your `MapSnapshot`.

My suggestions:
* use a `Projection` (like you do now)
* don't run a loop
* after the file is saved, run the next `MapSnapshot`
* anyway, don't run several snapshots at at time

Tell me if it works.

**Comment by abinpaul1** [comment] 2021-09-12 12:15
Great. It works that way 🥳 (running the next Snapshot after it is saved and the entire thing in a Foreground Service). Thanks a ton for the guidance. Really really appreciate the swift response.


> I don't think you even need a `MapView` now, as long as you use a `Projection` for your `MapSnapshot`

I think I need the MapView because the Marker object requires it during intialization. Is there any other way around it.

**Comment by monsieurtanuki** [comment] 2021-09-12 13:11
@abinpaul1 I've double-checked: you're right, for the moment you need a `MapView`. I guess we could get rid of it if needed, but that is not a priority I think.
I'm glad I was helpful!
Feel free to close the issue if relevant.

**Closed** 2021-09-12 14:58 UTC
