### ISSUE TITLE
Map shows many

### ISSUE THREAD

**Issue by suguMax** [osmdroid/osmdroid#559] opened 2017-02-15 13:24 UTC
Hi @spyhunter99, is there any possibility to set the map limit or use only one map instead of may maps in the mapview?

**Comment by suguMax** [comment] 2017-02-15 13:29
http://stackoverflow.com/questions/30742476/osmdroid-limit-the-map-in-north-south
When I try this answer, map does not shows up when deep zoom and one pinch zoom out.

**Comment by suguMax** [comment] 2017-02-15 13:30
@spyhunter99 Please check this and let me know the reason.

**Comment by spyhunter99** [comment] 2017-02-17 12:10
you can set the scroll and zoom limits. this is also a frequently duplicated issue. I think @MKergall was looking into it at one point

**Comment by spyhunter99** [comment] 2017-06-16 23:19
related issue https://github.com/osmdroid/osmdroid/issues/183

**Comment by spyhunter99** [comment] 2017-06-16 23:38
great question. i added some comments on that so post i had some degree of success with moving north bound, but not the other way. i'll push my changes to a branch. maybe @MKergall will look at it

**Comment by spyhunter99** [comment] 2017-07-29 15:04
closing this as duplicate of #183

**Closed by spyhunter99** 2017-07-29 15:04 UTC
Labels: duplicate
