### ISSUE TITLE
tiles get lost after switching off the display

### ISSUE THREAD

**Issue by PontiacCZ** [osmdroid/osmdroid#263] opened 2016-02-08 21:12 UTC
First I submitted the following ticket into [OSMTracker's issue list](https://github.com/nguillaumin/osmtracker-android/issues/61#issuecomment-181309187) and the author replied that the problem was most likely on the OSMDroid library part. So I'm putting it here as well in the hope that... it could be useful somehow. If it won't, feel free to close it.

-----

**Screen 1**: OSMTracker is tracking, all tiles in the current area are downloaded. Then I switch off the display to save battery...
![pic1](https://cloud.githubusercontent.com/assets/9153595/12899049/e7df447a-ceaf-11e5-874f-335bb826fb9e.png)

**Screen 2**: after switching on the display I see this - couple of tiles are missing. OSMTracker reloads them, it takes some time and data from my data limit. In the end everything is loaded just like in the first screenshot. Then again I turn off the display...
![pic2](https://cloud.githubusercontent.com/assets/9153595/12899047/e7dbb65c-ceaf-11e5-9a51-2017933292db.png)

**Screen 3**: ... to find out that after switching it on I have lost another tiles. And again, it starts reloading the missing tiles. 
![pic3](https://cloud.githubusercontent.com/assets/9153595/12899048/e7dc6d86-ceaf-11e5-854d-730bf5c8205e.png)

Sometimes when mapping I get to areas without service and then no reload can occur so I am a little bit blinded.

OSMTracker for Android v0.6.11
HW: Nexus 6 (Android 6.0.1)

**Comment by spyhunter99** [comment] 2016-02-08 23:36
dollars to donuts, this is probably not an osmdroid issue. We provide a variety of tools to support caching and minimize network usage. Most likely, the author used something other than the default setting for map provider uses Assets, Archives, File Cache, and then Online network access.

It's possible that you're device doesn't have an Environment.getExternalStorage available OR the app doesn't have write permissions to external storage OR sine you're running android 6, the app hasn't been updated for the new permissions scheme in which you the user, have to grant explicit write access to storage in order to get things caching correctly.

For the author of OSMTracker, it's more than possible now to set the cache dir to be the application's private data folder which would eliminate the need for the read and right to external storage.

hope this helps, but there's little I can do from over here.

**Comment by nguillaumin** [comment] 2016-02-09 08:23
Hi, thanks for the pointers.

Unfortunately I'm not the one who implemented the map view no OSMTracker, it was done by contribute since long gone so I'm not very familiar with the implementation... The code using the `MapView` is around here I believe: https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/DisplayTrackMap.java#L169

It seems to me we're using the defaults for everything (just [changing the tile source depending on a user preference](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/DisplayTrackMap.java#L232)), would you be able to have a quick look and tell me if you see anything wrong with the code?

> it's more than possible now to set the cache dir to be the application's private data folder

How would I do that?

Thanks!

**Comment by ZKjellberg** [comment] 2016-02-09 09:24
Downloaded and testing the application and am able reproduce the issue as suggested.

The application targets Android 16, so it is automatically granted the storage permissions, so that isn't the issue.

I upgraded the osmdroid plugin from 4.2 to 5.1, but had to remove the **implements OpenStreetMapContributorConstants** in DisplayMapData.java for the upgrade. With the upgrade, the issue still persists. Additionally, I tested using all three Map Sources: Mapnik, Cycle Map, and MapQuest Open. All have the same issue.

I don't know well enough how the cache system works, is it downloading tiles again or could this be slow loading of cache?

**Comment by ZKjellberg** [comment] 2016-02-09 09:49
Could [osmView.invalidate();](https://github.com/ZKjellberg/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/DisplayTrackMap.java#L388) cause a refresh of the map?

This is triggered in the [onResume](https://github.com/ZKjellberg/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/DisplayTrackMap.java#L208) method. Removing the call to **pathChanged()** still experiences the same issue.

I just loaded up the OpenStreetMapViewer test application and this issue exists there as well, so this seems to be a global issue.

Delving into this further, I wanted to determine if this was a slow loading mechanism from cache or if it was downloading live each time. If I load the application with cell service, it will experience this slow load. If I am in airplane mode, the application loads the map instantly. Interestingly, if I use cell service for the load and instantly enable AirPlane mode, it will result in all gray tiles never loading.

I suspect this may relate to the mechanism for determing if tiles have been updated. Possibly the code is waiting for the server response prior to loading the cached files? If so, maybe we could reverse this by loading the tiles first and then checking for an update?

**Comment by spyhunter99** [comment] 2016-02-09 23:46
again, assuming defaults, the tile request is first checked from assets, the file based archives, then the cache, then download the tile (and write to the file system for the cache). There is in a mechanism to expire tiles based on openstreetmap.org's policy of something like 3 days. This should be configurable since 5.1 (i think).

There's a few things to try to narrow down the root cause. 

1. turn on debugging
`OpenStreetMapTileProviderConstants.DEBUGMODE=true;`
2. turn on tile loading debugging
`OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS=true;`

**Comment by spyhunter99** [comment] 2016-02-19 23:42
Funny story, i just ran into a similar issue and now that I think about it, i think there was a few related issues in the tracker. My issue is that tiles loaded from assets cause a boat ton of GC and is actually causing serious battery drain

**Comment by spyhunter99** [comment] 2016-02-21 13:19
related issue #131

**Comment by spyhunter99** [comment] 2016-02-21 13:34
I guess i own someone donuts :)
I'll see look into as time allows

**Comment by spyhunter99** [comment] 2016-02-21 14:33
a few notes, offline tile loading doesn't appear to be affected by this, no reloading noticed with sqlite files.

i think the fix for 272 has either helped to fixed this. The cache was being LRU cache was being checked, but not inserted into.

another issue is that when using online sources, the tile download will attempt to download the tile indefinitely until it's loaded

**Comment by spyhunter99** [comment] 2016-02-23 00:18
the fix for this should be in master now. feel free to test and reopen if it's still a problem for you. thanks for the bug reports!

**Closed by spyhunter99** 2016-02-23 00:18 UTC
Labels: bug
