### ISSUE TITLE
Scale map tiles to dpi/Calculate largest available zoom level dynamically

### ISSUE THREAD

**Issue by kurtzmarc** [osmdroid/osmdroid#81] opened 2014-11-21 20:30 UTC
Since we are beholden to the Android Canvas integer based coordinate system, if we are using a tile size of 256 pixels then we can support up to zoom level 22. However if we use a tile size of 512 pixels, we now have to support a map size that is now double the map size at 256 pixels, and therefore, we can only support up to zoom level 21.

This causes problems when calling toProjectedPixels() since the numbers will now overflow if we can't support our MAXIMUM_ZOOMLEVEL constant which is 22.

Fixing this will close #13, #49, #68.

**Comment by mrachelski** [comment] 2015-01-13 09:20
Thank you @kurtzmarc that seems to have done the trick for the maps themselves. I can confirm that they are now readable on the high density devices I am testing with. 

However, I still seem to have an issue with the text I am placing into Markers on the map (using ItemizedOverlayWithFocus and OverlayItem). This text on the highlighted marker is still too small to be readable in much the same way the streets and labels used to be too small. Was this fix intended to address this or am I supposed to be adjusting the text size myself somewhere?

**Comment by kurtzmarc** [comment] 2015-01-13 14:20
@silviokuehn The Android canvas uses integers for its coordinate system. Overflow happens at 2^31-1. If we have a tile size of 512 then MapSize(22) = 2^31. (we could probably get away with using 22 since it will only overflow by one pixel, but anything higher than that would be more greatly affected)

**Comment by kurtzmarc** [comment] 2015-01-13 14:24
@mrachelski The ItemizedOverlayWithFocus uses its own Paint objects to determine the text size. If you extend the overlay you can change the parameters of mDescriptionPaint and mTitlePaint. But really, ItemizedOverlayWithFocus is really old and outdated. You'd probably have better luck with [osmbonuspack](https://code.google.com/p/osmbonuspack/).

**Comment by samskiter** [comment] 2015-04-06 15:27
hi, i've found a slight issue here,

calling `mapView2.setTilesScaledToDpi(false);`

produces a different effect to doing nothing at all.

You probably need to add a call to `TileSystem.setTileSize` whenever a tilesource is set.

**Comment by kurtzmarc** [comment] 2015-04-07 12:24
I'm not sure what you're saying here. When you call mapView.setTileSource() it calls updateTileSizeForDensity() which calls setTileSize().

**Comment by samskiter** [comment] 2015-04-10 13:17
I don't think I ever call mapView.setTileSource()

My setup looks like this:
```
mapView = new org.osmdroid.views.MapView(
                getActivity(),
                100,
                new DefaultResourceProxyImpl(getActivity()),
                maptilbasic,
                null);

mapView.setTilesScaledToDpi(false);
```

Without the last line, I end up with difference sized map tiles.

**Comment by kurtzmarc** [comment] 2015-04-13 12:41
Okay, I think I see what's happening now. You're right, we need that initial TileSystem.setTileSize() adjustment when a tileSource is set.

**Comment by kurtzmarc** [comment] 2015-04-16 14:49
That should fix that issue. Thinking more long-term, we really should pass the tileSize in to all the TileSystem methods rather than try to keep a static field for it.

**Comment by flekken** [comment] 2015-04-22 07:50
There is a commit connected to this issue that broken the tile loading:
[Commit d75b60c](https://github.com/osmdroid/osmdroid/commit/d75b60c774af8de0bab091d3d96fcd992e9305b0)
There is at least 1 issue on the mailing list connected to this:
[Issue 1](https://groups.google.com/forum/#!topic/osmdroid/xLblBVC3K6A)

Reverting that commit makes tile loading from asset all good again.

**Comment by gsantner** [comment] 2016-06-11 15:42
Any updates to this? setTilesScaledToDpi(true) works great, but makes everything very pixelated.  Is there an way to make MapView **render** dpi dependent, rather than scaling up?

**Comment by sleepnova** [comment] 2016-10-11 14:25
I don't know if this is related with this issue. When I display map tiles which looks great on desktop/laptop on cellphone, it become very small even if I

`mapView.setTilesScaledToDpi(false);`

Currently I manually call setTileSize as a workaround.

`TileSystem.setTileSize((int) (aTileSource.getTileSizePixels() * density * 0.5));`

Don't know if there is any better way...

**Comment by spyhunter99** [comment] 2017-01-15 22:17
resolved with #488

**Closed by spyhunter99** 2017-01-15 22:17 UTC
Labels: enhancement, waiting for feedback

**Comment by gsantner** [comment] 2017-01-17 00:40
Tried the new version on my Nexus 5.

* `.setTilesScaledToDpi(false);` too small that anything could be read (that's okay, as scaling off)
* `.setTilesScaledToDpi(true);` still pixelated, and text not really good readable (at least the small street names)

**Comment by spyhunter99** [comment] 2017-01-17 01:31
@gsantner maybe we can make the scaling factor dynamic or have a developer override.

**Comment by hlaurent** [comment] 2017-04-23 09:47
Having a developer override for the scaling factor would be great. With the new devices, it is becoming harder to read the maps.
