### ISSUE TITLE
MapView enters an infinite redraw loop

### ISSUE THREAD

**Issue by miguel-porto** [osmdroid/osmdroid#846] opened 2018-01-05 17:24 UTC
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

Sometimes, when pinch-zooming, the map enters an infinite redraw loop, where tiles are reloaded and removed indefinitely. Please see a video shot here: [infinite redraw bug](http://flora-on.pt/infinite-redraw.mp4)
I don't have any clue of what triggers this issue. It just happens "sometimes", not very frequently. If you zoom to other place, sometimes it goes back normal. Sometimes comes back again. You see the video!
When this happens, the app freezes on detach. No error messages are thrown.
Has anybody experienced this? Can you replicate?
Thanks!

### If it's a bug, version(s) of android this affects:

API 23

### Version of osmdroid the issue relates to:

6.0.0-SNAPSHOT

**Comment by spyhunter99** [comment] 2018-01-05 23:35
trippy!

**Comment by spyhunter99** [comment] 2018-01-06 00:08
#812 possibly related

**Comment by miguel-porto** [comment] 2018-01-06 23:53
I've been digging this issue by putting log messages throughout the redraw chain. It turns out that the [MapView's dispatchDraw](https://github.com/osmdroid/osmdroid/blob/5198ee03925d915c617b1b31517fdcb5d4b0f787/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L1047), under some circumstances, starts getting called repeatedly, indefinitely, and this is causing the tiles continuously flicker.
So yes, it's an infinite redraw loop, the problem. But what's causing dispatchDraw to be called repeatedly? Maybe there is some misplaced invalidate()? Through where goes the feedback loop? I have no idea yet, and also no idea of what circumstances trigger this issue - but it happens only on zooming out, I think. I have no other overlays but the tile overlay.

**Comment by spyhunter99** [comment] 2018-01-07 00:22
can't help but wonder if it's related to #164. I'm trying to reproduce this on this end, not successful yet. There is a configuration setting which dictates the size of the in memory cache

**Comment by secaw** [comment] 2018-01-07 21:40
@miguel-porto Are you creating your own `MapTileProviderArray`? Then it's probably related to something I've been experiencing some time ago...

Quote from my own comment on 6 Sep 2017 in #646
> Since I did not use MapTileProviderBasic, but MapTileProviderArray directly, tile loading was stuck in an infinite loop with expired tiles and when offline, because 'isDowngradedMode()' always returned false. I created my own MapTileProviderArray now based on MapTileProviderBasic, which solved this problem and actually a few others.

**Comment by miguel-porto** [comment] 2018-01-07 21:53
This is partially solved by increasing the overshoot cache, see [this comment](https://github.com/osmdroid/osmdroid/issues/812#issuecomment-355854488)!
@secaw no, I'm using the "plain old" Bing maps directly, nothing more. This infinite loop also happens online, but increasing the overshoot cache seems to resolve it. I think @monsieurtanuki [theory](https://github.com/osmdroid/osmdroid/issues/812#issuecomment-355788917) is probably the issue.

**Comment by secaw** [comment] 2018-01-07 22:38
Interesting, thanks.

**Comment by spyhunter99** [comment] 2018-01-15 18:37
so how should we resolve this? should we set the default overshoot size to be non zero? and if so, what is a reasonable value?

**Comment by monsieurtanuki** [comment] 2018-01-15 19:01
Disclaimer: I was never able to reproduce this bug.

As I explained in my [theory](https://github.com/osmdroid/osmdroid/issues/812#issuecomment-355788917) and my [suggested action plan](https://github.com/osmdroid/osmdroid/issues/812#issuecomment-356024809), I think this has to do with memory LRU management.
The idea would be to rewrite it in order to:
* still have control on the target number of tiles to keep in memory _if possible_
* have more control over the used memory vs. the available memory
* avoid the xmas tree effect
* possibly being able to reproduce the xmas tree effect everywhere if necessary with very very bad set up

**Comment by spyhunter99** [comment] 2018-01-15 19:15
What if we set the overshoot size to a negative number?

**Comment by spyhunter99** [comment] 2018-01-15 20:12
looks like even if it is set, the change doesn't go into affect unfortunately

**Comment by spyhunter99** [comment] 2018-01-15 20:27
good news, i just confirmed that i can replicate this issue.

**Comment by spyhunter99** [comment] 2018-01-15 20:43
Fix: I've added another configuration setting to create the overshoot cache size. @miguel-porto did you by chance have your map set to not scale tiles to dpi? If this setting is off, more tiles will render on screen that when it's set to true. This usually means that any printed text on the tiles are not readable, however bing tiles are sometimes still ok in terms of readability.

**Comment by pasniak** [comment] 2018-01-16 12:28
Why do we use LRUMapTileCache? 

If that helps... a similar app app I use uses android.support.v4.util.LruCache and has the memory constants based on the device's memory:
https://github.com/apps4av/avare/blob/316d066ef7022a4b15b12325578e051ad11e1893/app/src/main/java/com/ds/avare/shapes/MapBase.java#L67
where the 3 values are defined in
https://github.com/apps4av/avare/blob/73a22de25f61166327e9db5cd67a0513aea4d44e/app/src/main/java/com/ds/avare/storage/Preferences.java#L280

**Comment by spyhunter99** [comment] 2018-01-21 20:29
@pasniak thanks for the reference. Their source code license is a bit scary so i'll look into another solution. 

We currently ensure the capacity of the LRU cache by using (w+1)*(h+1), where w and h are the quantity of tiles wide and height based on device orientation and screen resolution. Changing it to (w+2)*(h+2) may solve the problem for @miguel-porto 

on API 10
before the change, we are running at about 3.1MB 
after the change, we are running at about  3.2MB

works for me

**Comment by spyhunter99** [comment] 2018-01-21 20:54
merged and snapshot published, please update and test your app. if you still have issues, reopen

**Closed by spyhunter99** 2018-01-21 20:54 UTC
Labels: bug
