### ISSUE TITLE
ItemizedIconOverlay doesn't call onDrawItem method in draw method

### ISSUE THREAD

**Issue by trak17** [osmdroid/osmdroid#195] opened 2015-11-16 08:36 UTC
Like I wrote in title, method ItemizedIconOverlay.onDrawItem isn't call in method ItemizedIconOverlay.draw in 5.0 version. In 4.3 version everything was OK.

**Comment by spyhunter99** [comment] 2015-11-16 12:10
I'm not entire sure what the problem is. Are icons not showing up for you? the example app lets you plot 500 icons at a time and it does work. I'll review the code to see what was changed

**Comment by spyhunter99** [comment] 2015-11-16 12:22
looks like the biggest change was for ItemizedOverlay in which during zooming, icons do not scale with the map and retain their original size. I'm guessing you overrode onDrawItem.

Hmm. this was a user submitted patch  https://github.com/osmdroid/osmdroid/issues/92

it looks fixable. @trak17 do you by chance have time to look at it? i'm a bit swamped at the moment

**Comment by trak17** [comment] 2015-11-16 14:41
Ok. I will try look at it in this week.

**Comment by spyhunter99** [comment] 2015-11-18 23:59
@trak17 i just pushed a change to the branch #195. it appears to be working for icons now. can you test out that branch with whatever your application is? i'd be great if we had some kind of test for this to prevent this from happening in the future

**Comment by spyhunter99** [comment] 2015-11-28 19:04
ping

**Comment by spyhunter99** [comment] 2015-12-02 12:08
merged

**Comment by sandman7920** [comment] 2015-12-02 15:04
I think it will be better to calculate matrix in draw method, not in onDrawItem.
And then to use scaleX, scaleY in onDrawItem.

My Current implementation is:

```java
private float scaleX, scaleY;
@Override
protected void drawSafe(ISafeCanvas canvas, MapView mapView, boolean shadow) {
        if (shadow || MapFragment.thumb) return;

        canvas.getMatrix(mMatrix);
        mMatrix.getValues(mMatrixValues);
        scaleX = 1 / ((float) Math.sqrt(mMatrixValues[Matrix.MSCALE_X]
                        * mMatrixValues[Matrix.MSCALE_X] + mMatrixValues[Matrix.MSKEW_Y]
                        * mMatrixValues[Matrix.MSKEW_Y]));
        scaleY = 1 / ((float) Math.sqrt(mMatrixValues[Matrix.MSCALE_Y]
                        * mMatrixValues[Matrix.MSCALE_Y] + mMatrixValues[Matrix.MSKEW_X]
                        * mMatrixValues[Matrix.MSKEW_X]));
        super.drawSafe(canvas, mapView, shadow);
}

@Override
protected void onDrawItem(ISafeCanvas canvas, CustomItem v, Point p, float aMapOrientation) {
        if (scaleX != 1.0 || scaleY != 1.0) {
                canvas.save();
                canvas.scale(scaleX, scaleY, p.x, p.y);
        }
        super.onDrawItem(canvas, v, p, aMapOrientation);
        if (scaleX != 1.0 || scaleY != 1.0) {
                canvas.restore();
        }
}
```

**Comment by spyhunter99** [comment] 2015-12-03 22:36
@sandman7920 for the method 'drawSafe', what is that overriding? I'm not sure where we can put that function at the moment. It's currently in ItemizedOverlay

**Comment by sandman7920** [comment] 2015-12-04 16:07
@spyhunter99 yes, this is my custom ItemizedOverlay (from old osmdroid build drawSafe = draw)
After calculation super.drawSafe method call onDrawItem, again Override set canvas and call super.onDrawItem where real draw is called

**Comment by sandman7920** [comment] 2015-12-04 16:17
@spyhunter99 just move calculation  before item loop
```java
        scaleX = 1 / ((float) Math.sqrt(mMatrixValues[Matrix.MSCALE_X]
                        * mMatrixValues[Matrix.MSCALE_X] + mMatrixValues[Matrix.MSKEW_Y]
                        * mMatrixValues[Matrix.MSKEW_Y]));
        scaleY = 1 / ((float) Math.sqrt(mMatrixValues[Matrix.MSCALE_Y]
                        * mMatrixValues[Matrix.MSCALE_Y] + mMatrixValues[Matrix.MSKEW_X]
                        * mMatrixValues[Matrix.MSKEW_X]));
       for (int i = size; i >= 0; i--) {
            final Item item = getItem(i);
            if (item == null) {
                continue;
            }

            pj.toPixels(item.getPoint(), mCurScreenCoords);

           onDrawItem(canvas,item, mCurScreenCoords, mapView.getMapOrientation());
        }
```

**Comment by spyhunter99** [comment] 2015-12-05 21:47
that won't work either since the scale x and y needs to be present in onDrawItem. We could store the current x and y scale as a class level variable or change the API for onDrawItem (which will break any existing class that extends overlay)

**Comment by spyhunter99** [comment] 2015-12-05 23:44
opted for the "let's not change the api's approach"

**Closed by spyhunter99** 2015-12-05 23:44 UTC
Labels: bug, waiting for feedback
