### ISSUE TITLE
build faild~~ no support:compatibility

### ISSUE THREAD

**Issue by ikkyu0319** [osmdroid/osmdroid#194] opened 2015-11-13 08:48 UTC
Error:(32, 13) Failed to resolve: android.support:compatibility-v4:23+

**Comment by neilboyd** [comment] 2015-11-13 08:55
Please read the relevant [wiki](https://github.com/osmdroid/osmdroid/wiki) for your build method

**Comment by spyhunter99** [comment] 2015-11-13 12:23
you may need to update your android sdk

**Comment by spyhunter99** [comment] 2015-11-19 23:22
I'm going to go ahead a close this. Please reopen if this is still a problem for you @ikkyu0319. No one else appears to be having the problem and most likely the issue is that you need to run the android sdk updater tool

**Closed by spyhunter99** 2015-11-19 23:22 UTC
Labels: waiting for feedback

**Comment by rastikw** [comment] 2015-11-24 16:58
What helped me was to change the dependencies line to:
```
compile 'com.android.support:support-v4:23+'
```

**Comment by ZKjellberg** [comment] 2015-12-08 13:08
When building using **gradle**, the **OpenStreetMapViewer\build.gradle** will fail as it cannot discover
>compile 'android.support:compatibility-v4:23+'

As @rastikw suggested, replacing this with the below value will resolve the issue.
>compile 'com.android.support:support-v4:23+'
