### ISSUE TITLE
MyLocationNewOverlay memory leak

### ISSUE THREAD

**Issue by raulperez** [osmdroid/osmdroid#424] opened 2016-09-21 12:35 UTC
Hi.

I am getting this exception every time I leave and reenter the Fragment that contains the map:

```
E/ExceptionHandler: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@6139d6d
                                                                      at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
                                                                      at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
                                                                      at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.drawMyLocation(MyLocationNewOverlay.java:259)
                                                                      at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.draw(MyLocationNewOverlay.java:323)
                                                                      at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:134)
                                                                      at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1076)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15279)
....
```

I tried this on my onDestroyView method:

```
	@Override
	public void onDestroyView() {
		super.onDestroyView();

		_myLocationOverlay.onDetach(_mapView);

		if (_mapEventOverlay != null) {
			_mapEventOverlay.onDetach(_mapView);
			_mapView.getOverlays().remove(_mapEventOverlay);
		}

		if (_myLocationOverlay != null) {
			_myLocationOverlay.disableMyLocation();
			_myLocationOverlay.disableFollowLocation();

			_mapView.getOverlays().remove(_myLocationOverlay);
		}

		_mapView.onDetach();
		_mapView.getTileProvider().clearTileCache();

		_mapView = null;

		_myLocationOverlay = null;
		_mapEventOverlay = null;
	}
```

I am in a hurry and I cannot fix this problem. Any suggestion?

It is also happening on the demo app. If you try to enter/exit several times it crashes with the same Exception.

Thanks in advance.

**Comment by spyhunter99** [comment] 2016-09-21 18:03
You can try the other location overlays or write your own.  I'll look into
this as soon as I can

**Comment by atoone** [comment] 2016-09-22 16:58
Had the same exception:

```
09-22 17:53:54.117 18205-18205/.....E/ACRA: ACRA caught a RuntimeException for ...
                                                                 java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@27625cc0
                                                                     at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
                                                                     at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:811)
                                                                     at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.drawMyLocation(MyLocationNewOverlay.java:259)
                                                                     at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.draw(MyLocationNewOverlay.java:323)
                                                                     at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:134)
                                                                     at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1076)
                                                                     at android.view.View.getDisplayList(View.java:13364)
                                                                     at android.view.View.getDisplayList(View.java:13411)
                                                                     at android.view.View.draw(View.java:14190)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                     at android.view.View.getDisplayList(View.java:13364)
                                                                     at android.view.View.getDisplayList(View.java:13411)
                                                                     at android.view.View.draw(View.java:14190)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                     at android.view.View.getDisplayList(View.java:13364)
                                                                     at android.view.View.getDisplayList(View.java:13411)
                                                                     at android.view.View.draw(View.java:14190)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                     at android.view.View.getDisplayList(View.java:13364)
                                                                     at android.view.View.getDisplayList(View.java:13411)
                                                                     at android.view.View.draw(View.java:14190)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                     at android.view.View.getDisplayList(View.java:13364)
                                                                     at android.view.View.getDisplayList(View.java:13411)
                                                                     at android.view.View.draw(View.java:14190)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                     at android.view.View.draw(View.java:14476)
                                                                     at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2329)
                                                                     at android.view.View.getDisplayList(View.java:13369)
                                                                     at android.view.View.getDisplayList(View.java:13411)
                                                                     at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
                                                                     at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:149)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
                                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by spyhunter99** [comment] 2016-09-23 01:17
@raulperez are you setting the map view or any layers as static by chance?

**Comment by spyhunter99** [comment] 2016-09-23 01:28
i just pushed a fix for this. if it passes travis, i'll merge it in and then maybe we can convince @neilboyd to cut another version

**Comment by raulperez** [comment] 2016-09-23 06:35
Thank you very much @spyhunter99! I had found a workaround but I will migrate my code to contain this fix.

I am not using map view or any other layers as static.

I end up using org.osmdroid.views.overlay.mylocation.SimpleLocationOverlay and passing my own instance of a bitmap that I can manage externally.

But I will try the new patch also.

Thank you very much and thanks a lot for your effort and help 👍

**Comment by atoone** [comment] 2016-09-23 07:18
Thanks from me as well. I'm seeing a couple of other minor oddities since the upgrade, but haven't managed to quantify them yet, so don't feel you have to rush another release ;)

**Comment by spyhunter99** [comment] 2016-09-24 16:28
merged @neilboyd your turn. This seems to be big enough of a bug to cut a release (imo)

**Comment by neilboyd** [comment] 2016-09-25 20:09
I don't quite understand this. It looks like you simply removed the cleanup in onDetach. So when does it get cleaned up? The original report mentioned onDestroy, which seems like a potential candidate.
And why is draw getting called after it's been detached anyway?

**Comment by spyhunter99** [comment] 2016-09-25 21:00
I think it's being reattached when the fragment is resumed via the
backstack. **I think**. Your right, it should probably be moved to onDestroy

**Comment by neilboyd** [comment] 2016-09-26 05:13
And what about all that other stuff that's cleaned up in onDetach? It should be consistent.

I just read the docs on Fragments and there doesn't seem to be much difference between onDetach and onDestroy.  And onDestroyView describes the situation better.

**Comment by spyhunter99** [comment] 2016-09-26 11:06
onDetachView is part of the fragment, so that's something the user of osmdroid would have to do deal with. Let me run the extended leak test to see what's what. It may not even be an issue

**Comment by spyhunter99** [comment] 2016-09-27 11:29
I'm going to rework the automated to tests to hit the home button, then resume the sample app several times to try and catch this in the future. as of right now, the mylocation is still broken on develop. Not sure what the root cause is it

**Comment by spyhunter99** [comment] 2016-09-29 11:12
I ran the long duration test last night on hardware and didn't have any issues (on master, 100 iterations of each sample).  It doesn't appear to be leaking nor crashing at the moment and travis seems to be happy.

**Comment by spyhunter99** [comment] 2016-10-11 11:09
give 5.5 a shot

**Closed by spyhunter99** 2016-10-11 11:09 UTC
Labels: bug
