### ISSUE TITLE
Polyline and Polygon issues at higher zoom levels with/wo hardware acceleration

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#725] opened 2017-10-01 14:36 UTC
Priority:
This is blocking issue for 6.0.0 release. If we can't get everything rendering at the higher zoom levels, we may have to set the max zoom to the level at which we can render the content at.

Goals:
Provide proper rendering of polylines and polygons at any zoom level supported by the map view/projection with and without hardware acceleration turned on (really on is the goal)

Current issues after the merge of #329 #723 

- With hardware acceleration off
  - [ ] polyline disappears at zoom 25
  - [ ] polygon border disappears at zoom levels > 22
  - [ ] polygon has strange rendering behavior when the map wraps n/s, e/w
 - hw acceleration on
   - [ ] polyline disappears at zoom 26
   - [ ] polygon disappears when zooming in, it seems to be linked to large polygons that are primarily all offscreen see #353. Small polygons are not effected by this. The solution is an accurate clipping mechanism that supports all these strange edge cases when stuff is within or outside of the view port, holes and all at poles

Gotcha's
- Polygons are complex. 
   - "holes" that are partially offscreen, fill colors.
   - polygons in which all points are off screen, however the view port is within the polygon
   - polygons in which all points are off screen, however the view port is partially over the polygon
   - polygons in which all points are off screen, however the view port is completely over the polygon
 - lines
   - 1 or more points are on screen others are off screen
   - All points are on screen
   - All points are off screen, however the viewport covers an area in between some of the points
   - Poll/dateline wrapping

Considerations
- Performance is a big one

Directly related issues
 - MKergall/osmbonuspack#168
 - #353 Polyline Path too large to render into a texture
 - #476 Polygon drawing issue
 - #675 Polygon issues with the dateline
 - https://www.youtube.com/edit?o=U&video_id=S4Pf2u9WSyQ
 - https://www.youtube.com/edit?o=U&video_id=EQsi38PIYm8

Indirectly related issues
 - #595 scaling during animations of polyline

**Comment by monsieurtanuki** [comment] 2017-10-01 15:18
Some remarks

We shouldn't have different codes for `Polygon` and `Polyline`. They should both use `Path`. A `Polyline` behaves as a `Polygon` except that there are no holes, no fill and no `Path.close()`.

In my tests polygon borders even disappear at level 23 (when I draw a polygon at level 0)

The expected behavior of `Polygon`s in zoom level 0 is not clear for me, because we potentially have several pixels that match the same `GeoPoint`.
Could we say that:
* we want only one `Polygon` displayed 
* whenever the same `Polygon` could be displayed in different drawn worlds, we favor the one with the biggest displayed pixels coverage, and among them the one that is top left?

**Comment by spyhunter99** [comment] 2017-10-01 15:20
Concur on both.

**Comment by monsieurtanuki** [comment] 2017-10-01 19:18
I managed to do something: `Polygon`s ok on zoom 29.
![20171001 polygon zoom0](https://user-images.githubusercontent.com/11576431/31058083-e5d518a4-a6ed-11e7-91e6-229203b3c2b7.png)
![20171001 polygon zoom29](https://user-images.githubusercontent.com/11576431/31058088-ee55ba4c-a6ed-11e7-90e3-209b8447b0e0.png)

The code needs to be cleaned and checked again.
Then, the zoom 0 issues.

**Comment by spyhunter99** [comment] 2017-10-01 19:21
well that's awesome, also check with "holes"

**Comment by monsieurtanuki** [comment] 2017-10-02 19:49
I've just pushed my fix for `Polygon`s in zoom level 29 ([monsieurtanuki:feature/#725](https://github.com/monsieurtanuki/osmdroid/tree/feature/%23725)).

I fully understand what is expected about the low-zoom "best top-left version" of `Polygon`.

I even understand most of what is expected for `Polyline`s, although there are some unexpected specificities like method `addGreatCircle` and click events.

What is not clear for me is to "check Polygon with holes".
I can't really figure out what a `Polygon` with holes stands for. Would it be something like a map of continental Europe (Polygon) without Switzerland (hole 1) and Hungary (hole 2)?
Currently if I run demo "More samples / Drawing / Draw a Polygon with holes on screen", the hole has the same border and the same background color as the Polygon.
My assumption would be that the map under the hole would be displayed without alpha Paint on top. Am I correct?

**Comment by spyhunter99** [comment] 2017-10-03 02:54
Your description is accurate.  The demo with holes allows you to draw a ploygon, remove part of its center using the knife. The hole is drawn without the fill color.

**Comment by monsieurtanuki** [comment] 2017-10-03 15:08
There's something wrong with the algorithm: incoherent behavior between Polygon and GeoPoint.

Let's say the Polygon is the USA, and the GeoPoint is New York City.

My screen displays 2x2 worlds (something like a 512x512 screen).

If the top left of my screen is on Siberia, the Polygon is displayed top left, and so is the GeoPoint. The GeoPoint (NYC) is displayed inside the Polygon (USA). Looks like a sensitive behavior.

But if I scroll the map so that Chicago is on x=0, the NYC GeoPoint will still be on top left, but the US Polygon will be displayed in the middle of the screen (x-wise). The GeoPoint and the Polygon will be disconnected. Looks like a bug to me.

First question: do we agree on the fact that the zoom 0 specific algorithm is flawed?

Second question: could there be a better algorithm that solve this USA/NYC combination?
I don't think so, unless we add some parameter to the draw Polygon feature (like offset or justify)

Third question: could we be more relaxed about the zoom 0 specific algorithm, as it's a very specific use case to display the whole world (and more) on a smartphone screen?
As I assume no algorithm can be perfect on that subject, I would recommend that we consider the first GeoPoint of a Polygon to be top left, with the following Polygon's GeoPoints' coordinates computed from this start.
Does that make sense?

**Comment by MKergall** [comment] 2017-10-03 18:23
"Third question: could we be more relaxed about the zoom 0 specific algorithm"
=> IMO, zoom 0 doesn't make sense. Repetition is ugly, useless and a nightmare to support. 

What most common online maps services are doing? Here are my findings, translated in osmdroid Min zoom levels "equivalents": 
Google Maps: 2
Bing Maps: 2
openstreetmap: 0, or -1 (I can get up to 6 repetitions)
mapquest : 1
Mappy: 4
Yandex: 1

=> our Min zoom level could be not less than 1. 

"can we impose the first GeoPoint of a Polygon to be top left": I don't think such a constraint is acceptable.

**Comment by monsieurtanuki** [comment] 2017-10-04 08:52
@MKergall I agree with you on world repetitions. More specifically, the S85 / N85 latitude transition makes no sense at all.

Maybe #722 is the correct answer and should be the default mode (disclaimer: I just read the description).

> "can we impose the first GeoPoint of a Polygon to be top left": I don't think such a constraint is acceptable.

Hey, I never said "impose"! ;)
To clarify my thoughts: I don't mean at all we should expect/demand the users' `Polygon`'s first `GeoPoint` to be the top left one of the `GeoPoint` list. I just wondered if the algorithm in the lousy repeated world case could be:
* the `Polygon` starts with a `GeoPoint`
* this `GeoPoint` can be projected on many pixels on this repeated world map - and among them we choose the top left pixel (cf. NYC example above)
* all the other `Polygon` `GeoPoint`s are projected accordingly - among all the projected pixels we choose the one that is closest to the chosen projected pixel of the previous `GeoPoint`

Alternate version - we stick to what I suggested earlier:

> whenever the same `Polygon` could be displayed in different drawn worlds, we favor the one with the biggest displayed pixels coverage, and among them the one that is top left

Knowing that anyway the USA `Polygon` vs NYC `GeoPoint` potential issue cannot be prevented.

**Comment by MKergall** [comment] 2017-10-04 20:56
Understood :-)

**Comment by monsieurtanuki** [comment] 2017-10-06 17:37
Done and committed.

**Comment by spyhunter99** [comment] 2017-10-06 21:41
test results:
hw acceleration off (current default):
 - polyline working perfectly
 - polygon (solids) kind of working, however the border is disappearing at max zoom -2, i had the whole polygon disappear at max zoom -9
 - polygon with holes, working, however the border is disappearing at max zoom -2

hw acceleration on:
 - polyline still disappears for long lengths
 - polygon super slow performance (crashed my genymotion vm)
 - polygon with holes, not yet tested

**Comment by spyhunter99** [comment] 2017-10-06 22:17
i'll add, that my test cases and generally very large polygons drawn at near min zoom, generally the size of the continental us

**Comment by monsieurtanuki** [comment] 2017-10-07 06:33
There are 2 paths of optimization/bug fix.

The polygon (and all its consecutive segments) are clipped into a [min, min, max, max] area for two reasons:
* fitting `long` pixels value (due to high zoom level) into acceptable `int` values (for `Path`). In that case, the min/max values of the clip area could simply be `Integer.MIN_VALUE` and `Integer.MAX_VALUE`
* fixing the Android bug hardware acceleration bug on `Path` drawing. In that case, there's no explicit min/max value. I initially adjusted the values to `Integer.MIN_VALUE / 8` and `Integer.MAX_VALUE / 8` because it worked OK on my smartphone.

If we put high values for min/max:
* we alter less the shape of the Polygon _outside of the visible area_. (the visible area will always be OK, unless min/max are smaller than the screen)
* we have more points in the `Path` (less pixels will be truncated to min/max)
* we are more likely to have hardware acceleration issues (but there's no explicit value)

If we put low values for min/max:
* we alter more the shape of the `Polygon` _outside of the visible area_. I thought it could be an issue when zooming out: displaying a truncated version of the `Polygon` during the animation. But it doesn't seem to be the case, as the `Polygon` seems to be redrawn somehow (and therefore recomputed)
* we get better performances because there are less points in the `Path`
* we are less likely to have hardware acceleration issues.

I suggest the following values for `LinearRing.mClipMax`: 17000 (a lousy approximation of 2^8 * a screen size of 1000). And -17000 for min.

There's another optimization possibility but that's not the most important now.
The low level "best position best area top left" algorithm costs a lot, because we need to save the whole path into local `PointL` lists before displaying the `Path`, in order to compute the best pixel offset.
If we don't need this "best offset" (for instance because the zoom level is not that low), we can get rid of those local lists and directly populate the `Path`.

**Comment by monsieurtanuki** [comment] 2017-10-07 11:35
@spyhunter99 I guess you can re-run your tests with my latest commit - or just set `LinearRing.mClipMax` to 17000 and `LinearRing.mClipMin` to `-mClipMax`.
It should solve the issues (disappearing border and very slow display).

**Comment by spyhunter99** [comment] 2017-10-07 13:44
test results

hardware acceleration on
- polyline disappearing
- polygon, super slow zooming, panning

hardware acceleration off
- polyline disappearing, i also saw one case where a fling caused the line to disappear on the same zoom level in which it was visible. it would reappear i panned to another world
- polygon border disappearing fixed

**Comment by spyhunter99** [comment] 2017-10-07 14:38
i'm thinking we need some way to automate some of these test cases and to add test cases related to very small drawings as well as very large ones

**Comment by monsieurtanuki** [comment] 2017-10-07 16:15
I need you to give me all the data you use for your tests: Polygons with all their GeoPoints (most important), map center and zoom levels.
With that I can build a new test Activity and try to reproduce the bugs you encounter.
That's OK for visual tests.

But I don't really know how we could say programmatically that there's an issue. Perhaps by comparing some canvas pixel color before and after we add a Polygon.

**Comment by spyhunter99** [comment] 2017-10-07 16:19
I'll fire up an emulator and record what i've been doing to reproduce

**Comment by spyhunter99** [comment] 2017-10-07 16:40
and that's just it, there's now way to programmatically tell if something has rendered or not, or is visible on screen or not, aside from checking pixel colors. Bummer

**Comment by spyhunter99** [comment] 2017-10-07 17:51
https://youtu.be/-TKE2tDm7KU polygon with hardware acceleration test
https://youtu.be/Jc6tm07iQb0 polygon with software acceleration test
https://youtu.be/qB_IQ_FfnKY hardware acceleration line test
https://youtu.be/oB5Uf0KtcIc software acceleration, line test
https://youtu.be/ki5W26lynrU fling issue with software accerlation

**Comment by monsieurtanuki** [comment] 2017-10-08 20:20
@spyhunter99 Thank you for your videos.
I focused on https://youtu.be/qB_IQ_FfnKY, which is a demo of the following bug: "when hardware acceleration is on, the polyline disappear beyond approximately zoom + 4".

I ran many experiments. For instance, this shows a path:
````java
path.moveTo(-1554, 1410);
path.lineTo(-326, 400);
path.lineTo(11, 341);
path.lineTo(308, 321);
path.lineTo(565, 459);
path.lineTo(763, 816);
path.lineTo(2512, 1229);
````
But that one doesn't show anything, though the only difference is the last `x` `lineTo` parameter, with a difference of 1:
````java
path.moveTo(-1554, 1410);
path.lineTo(-326, 400);
path.lineTo(11, 341);
path.lineTo(308, 321);
path.lineTo(565, 459);
path.lineTo(763, 816);
path.lineTo(2513, 1229);
````

It looks like there's a drawing issue if the path covered area goes beyond a bit above 4x1024x1024 pixels.
The solution would therefore be to lower the clip area down to 2000x2000.
I set `LinearRing.mClipMin` to -600 and `LinearRing.mClipMax` to 1400.
And now the polylines and polygons are always displayed on my smartphone, with and without hardware acceleration.

Is that 4Mpixels limit relevant on all devices? I don't know.

@spyhunter99 Could you please test again: basically my assumption is that there should not path not drawing issue again.

As I stated previously, if the only problem left is speed there are still margins of optimization, as we compute tons of variables only for the low zoom level possible offset.

In "https://youtu.be/ki5W26lynrU fling issue with software acceleration" I'm not sure I understand the issue. If the problem is that the polyline is sometimes jumping when the map is panning, that's exactly what the business rule is: we offset the polyline where it covers the maximum visible area and possibly top left. Is that what bothers you? Or is it the slow speed of the fling?

**Comment by spyhunter99** [comment] 2017-10-08 23:31
Great job on fixing the issue. i'll run some more tests.

The panning issue. While slowly panning, i was noticing that the map was unexpectedly jumping around. Like the map was jumping, not the line.

**Comment by monsieurtanuki** [comment] 2017-10-09 10:45
There are side effects to such a small clip area, for instance in low zoom level when searching for the best location: if I add a world size to my polyline's pixels, I may go beyond the clip area.
Still things to fix...

**Comment by spyhunter99** [comment] 2017-10-09 12:26
lines
hw https://youtu.be/AtQQde1f8N4 
sw https://youtu.be/_eF7r3ss5CY 

lines appear to randomly redraw and strange angles seen on both with and without hardware accel. The fling issue is also still apparent.

**Comment by spyhunter99** [comment] 2017-10-09 12:45
@monsieurtanuki just pulled, compile failed
````
C:\projects\osmdroid\osmdroid-android\src\main\java\org\osmdroid\views\overlay\LinearRing.java:218: error: no suitable constructor found for RectL(RectL)
                                pSegments.add(new RectL(currentSegment));
                                              ^
    constructor RectL.RectL() is not applicable
      (actual and formal argument lists differ in length)
    constructor RectL.RectL(long,long,long,long) is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
````

**Comment by monsieurtanuki** [comment] 2017-10-09 12:48
That's what I meant: this comes from a collision between the clip area being very small AND the computation of the offset for very low zoom level.
But that's the past: I just fixed it (I compute the offset AND THEN I clip the area, not the other way around).

I've just committed a very nice version that should solve everything.

Except for one thing: the algorithm for very low zoom levels is to put the `Polygon` or `Polyline` where their centers are the closest to the screen (map) center.
The previous business rule was to put them top left with the best possible covered area.
As everybody here despises the very low zoom levels, I assume we can agree on this new decent business rule without too much friction. Can't we?

[about the `RectL` compilation issue, I just forgot to commit/push `RectL`. Added it now]

**Comment by spyhunter99** [comment] 2017-10-09 13:14
definitely better! business rule change seems fine, as long as it renders

ran into an issue with polygons on software acceleration... https://youtu.be/lhlFkA4h8D4 it's changing shapes with zooming/panning, 

issue is also present with hardware acceleration https://youtu.be/1zCjNb2bTdk

**Comment by monsieurtanuki** [comment] 2017-10-09 19:48
Now it should be OK (just committed/pushed again).
At last.
More robust segment clipping.

For the record I created a funny shaped `Polygon` in order to get the same unexpected behaviors as in your youtube videos:
````java
final Polygon polygon = new Polygon();
polygon.setFillColor(Color.argb(75, 0,255,0));
final List<GeoPoint> points = new ArrayList<>();
points.add(new GeoPoint(0., 0));
points.add(new GeoPoint(-10., 10));
points.add(new GeoPoint(-5., 15));
points.add(new GeoPoint(-7., 5));
points.add(new GeoPoint(-12., 20));
points.add(new GeoPoint(-50., 0));
polygon.setPoints(points);
mMapView.getOverlayManager().add(polygon);
````
Could be useful later for tests.

**Comment by spyhunter99** [comment] 2017-10-10 00:18
I'm positive you now appreciate the complexities of drawing map data. Welcome to the club. I'm also very happy that you were able to resolve this. 

I think this is the first time I've ever seen polygons work with hardware acceleration without clipping the shape before adding it to the map. bravo! I also tested with map rotation and everything seemed ok.

i did see one strange issue when i drew a polygon on screen and after it plotted, it moved. I'm not sure if it's a projection issue or point reducer or what... anyhow i'll merge it as is and we can move on. 

@MKergall might finally be happy about the hardware acceleration support

**Comment by monsieurtanuki** [comment] 2017-10-24 17:24
(continued from #742)
@Maradox The `LinearRing` clip area is merely a rectangle just beyond the screen rectangle.
Every `Polygon` will be truncated at display time so that it won't go beyond those clip boundaries. It sounds pointless (because we cannot see beyond the screen rect) but this way we avoid an Android Polygon display bug.

For instance, if the screen rectangle is [0, 0, 600, 800], it makes sense to have a clip area like [-600, -600, 1400, 1400], because
* the clip area encloses the screen rect
* the screen rect is vaguely centered on the clip area
* the 2000 pixel spans look experimentally OK on my smartphone

With a 1080×1920 resolution a clip area of [-600, -600, 1400, 1400] does not make any sense, as we would truncate the bottom-right part of the `Polygon`s. The minimum rectangle would be [0, 0, 1080, 1920] (the screen rect), and [-500,-500, 1500, 2500] if we apply a 500 delta.

It looks like we need to compute `mClipMin` and `mClipMax` for each smartphone.
What I can tell you is that on my smartphone [-600, -600, 1400, 1400] is the ideal clip area rectangle (if bigger we get the Android bug).
But I have no way to know the correct size of the clip area for other smartphones :(

**Comment by spyhunter99** [comment] 2017-10-24 18:57
i bet you orientation changes will cause issues too

**Comment by monsieurtanuki** [comment] 2017-10-25 15:49
I'm currently creating a demo `Activity` dedicated to those hardware acceleration issues.

**Comment by spyhunter99** [comment] 2017-11-03 11:24
bummer. alright i'll revert the commit which enables hardware acceleration on by default. Canvas.drawPath is implemented in android but has some scaling issues? I'm not sure i understand what that link is saying and the side effects a user of osmdroid may encounter with hardware acceleration on

**Comment by monsieurtanuki** [comment] 2017-11-03 17:38
My understanding is that in the context of hardware acceleration turned on:
* Android does not support `Canvas.drawPath` (that we use when drawing `Polygon`s and `Polyline`s) during Canvas scaling (that we use in the `Matrix` part of `Projection`).
* as a consequence, display results cannot be trusted to be relevant

Yesterday I had this idea that we may be able to remove the scaling part of the `Matrix`. Because we are able to draw scaled tiles and add points to a `Polygon` without a `Matrix`.
Would that mean that `Canvas.drawPath` would then work correctly with the hardware acceleration turned on? That should be checked first before starting the developments.

**Comment by monsieurtanuki** [comment] 2017-11-14 18:10
I think I now have a partial answer. Not relative to hardware acceleration limitations: I think that should be put specifically in a distinct issue (that would deal with avoiding the Android unsupported operations mentioned above)

My main focus here is the problem experienced by @Maradox, which I would sum up by: "there are constant min/max values in `LinearRing` defining the clip area, and those values are too small for a 1080x1920 screen".

I think I managed to solve this issue: the clip area min/max are not constants anymore, but depend on the `MapView` characteristics (width, height, scale and orientation).
The results look OK so far, and I think I even managed to create a very small (but big enough) clip area, which should give better performances and potentially small enough for hardware acceleration (assuming Android's issues come from the `Path` area).

Still testing. About to PR.

**Comment by monsieurtanuki** [comment] 2017-11-14 19:37
(just PR'ed)

**Comment by spyhunter99** [comment] 2017-11-15 00:38
sweet! does this value refresh when rotating the device?

**Comment by monsieurtanuki** [comment] 2017-11-15 11:13
Even more often, because it depends on the current pinch scale and _map_ orientation (I mean _angle_, not portrait/landscape).

**Comment by spyhunter99** [comment] 2017-11-18 23:42
awesome thank you everyone for the excellent contributions. they are greatly appreciated!

**Closed** 2017-11-18 23:41 UTC
Labels: bug, enhancement

**Comment by mehulpxm** [comment] 2019-09-24 06:20
may I know the which line of code resolves the problem of polyline disappear on the max zoom?

**Comment by monsieurtanuki** [comment] 2019-09-24 06:58
If I remember well there should be no problem with `Polyline`s as long as they're build with `canvas.drawLines` - which is now the default behavior (as opposed to `canvas.drawPath`).

I've just used the demo app: "More Samples / Drawing / Draw a polyline on screen", and managed to zoom up to zoom 28.9, which should be enough for most cases, shouldn't it?
