### ISSUE TITLE
Floating point zoom

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#640] opened 2017-07-23 17:22 UTC
Today osmdroid displays only integer zoom levels.
The reason is obvious: the standard sources provide map tiles for integer zoom levels, from 0 (the world in a 256x256 bitmap) to about 20 (2^20 bitmaps).

Nevertheless, there's nothing that should prevent osmdroid from displaying floating point zooms.
Actually, during the zoom pinch gesture we can see what floating point zooms would look like, but after the gesture osmdroid unfortunately goes back to an integer zoom.

The goal: after the zoom pinch gesture, osmdroid won't go back to an integer zoom, but will keep the current floating point zoom. What will happen with zoom buttons: as they do now, they will add or remove 1 to the zoom level, limited by the same min and max zoom levels.

**Comment by devemux86** [comment] 2017-07-23 17:50
Mapbox had [forked](https://blog.mapbox.com/mapbox-android-sdk-ec5e2627461) Osmdroid and implemented floating zoom, among many other features.
Unfortunately after their move to OpenGL, that work doesn't seem found anywhere, except user forks.

**Comment by monsieurtanuki** [comment] 2017-07-23 18:28
I don't think it will be difficult to implement the floating point zoom for osmdroid. I'm rather confident :)

**Comment by secaw** [comment] 2017-07-24 12:10
Like #634 this would also be a fantastic overall improvement!

**Comment by monsieurtanuki** [comment] 2017-07-26 19:44
Just developed the double-precision zoom. Looks nice on my smartphone ;)

It's available on my branch [feature/#640](https://github.com/monsieurtanuki/osmdroid/tree/feature/%23640) (as far as I understand github). Hey guys, any additional test or comment is appreciated!

And then, PR.

**Comment by spyhunter99** [comment] 2017-07-26 22:50
Awesome! Super exciting. I'll look forward to testing this weekend.  Is the
range for zoom levels still 0 to 20 something? Thinking about backwards
compatibility

**Comment by monsieurtanuki** [comment] 2017-07-27 06:21
How does osmdroid display map (before the changes):
* Data comes from online providers as 256x256 bitmap tiles for integer zoom levels (typically between 0 and 18)
* A map is displayed on a canvas from 0,0 using these tiles
* Potentially the tiles are magnified because of density - for instance on my smartphone the actual size is 384 instead of 256
* An offset is applied (`int View.getScrollX/Y`) in order to center the map on the screen
* An additional transformation (via a `Matrix`) is applied in case of rotation
* Only during the zoom pinch gesture, the transformation Matrix includes the temporary map scaling

What I just developed:
* what we display is not only integer zoom levels, but double precision zoom levels
* but we still have integer zoom levels as input
* as an approximation of zoom level 15.999 I use the tile bitmaps of zoom level 15 that I almost double
* going from integer zoom level to integer zoom level used to be computed with standard *2 and /2 integer/long operators << and >>
* as we're dealing with real numbers it's not possible anymore - we use Math.pow(2,x) instead

Here are the limits:
* we use the Android standard View scroll parameters, that are `int` parameters, therefore 2^31 positive values
* we have 2^8 pixels on each tile bitmap dimension
* because of density we may have to double the tile size [or even worse - I don't know]
* with the zoom 15.999 output approximation from zoom 15 input we need enough space to be able to double the tile size. That's not a new "floating" limit as in the "integer" mode we would have needed integer zoom level 16 anyway and its additional power of 2
* little computation: for zoom level 0 on the x-axis we have 2^8 pixels (tile bitmap) x 2 (density) = 2^9
* as we have up to 2^31 values on the x-axis, that would mean we could go up to zoom level 22 (31 - 9)

Additional thoughts:
* if we display maps without using the standard View scroll parameters but scrolling maps ourselves, we don't have the `int` constraint anymore and its 2^31 limit
* there are limits to the accuracy of a double, apparently 16 digits. Enough up to 2^53.

**Comment by secaw** [comment] 2017-07-27 13:17
WOW this is so nice! Thanks for the great work.
Besides a so much smoother user experience, e.g. it is now possible to get perfect screenshots of plotted tracks by zooming in to the exactly desired bounding box by the pixel without being limited to the fixed zoom levels.
One thing that could maybe improved: The almost double scaled tiles (before the next int zoom level kicks in) start to look quite pixelated already on medium density screens, especially noticeable with transparent tile layers like OpenSeaMap. Would it be at all possible to e.g. use the zoom 16 tiles for any zoom above 15.499 (or even 15.299), if they are available?

**Comment by monsieurtanuki** [comment] 2017-07-27 14:10
My remarks about your additional feature request:
* I guess it's a matter of context. I use osmdroid maps for city maps, where using a small version of level 16 for 15.5 would make street names hardly readable. May be different in the context of OpenSeaMap
* It would be incoherent with the zoom pinch gesture, which is only a scale on the current zoom level (transformation `Matrix` applied to a `MapView`)
* Is `MapView.setTilesScaledToDpi()` of any help? An improvement could also be to add an optional scale parameter to `MapView` so that both level 15 and its almost double level 15.99 look ok. Potentially to be determined by each end-user, each of them having different smartphone densities and different eye sight confort zones.

My suggestion: for the moment, let's check that the double precision zoom works reasonably ok in many contexts, then a PR. And then we'll see :)

**Comment by secaw** [comment] 2017-07-27 20:24
Yes, you're right. I now remembered that I actually did `setTilesScaledToDpi(true)`, because the map texts initially were too small, so this of course enhances the visual pixelation of double sized map tiles.
Did some more testing and all works really well.
One thing I noticed though is that if say you are offline and got tiles at zoom 6, but none above. Now you are zooming in - at zoom 7 all looks scaled as expected, but as soon as you are zooming into 8, something flips and you seem to have the wrong tile scaled at the wrong place. This happens always when offline and zooming into the last available tiles at zoom level + 2 no matter if tiles come from `mapTileSqlCacheProvider` or `MapTileFileArchiveProvider`.
Just checked current integer zoom version, which instead behaves as expected.

**Comment by secaw** [comment] 2017-07-27 20:59
UPDATE: It seems that tiles with last available offline zoom level + 2 get scaled double the supposed size!

**Comment by spyhunter99** [comment] 2017-07-28 01:28
would be awesome that when offline, automatically scale the last tile
available at the given zoom level, even when panning.
also would be awesome to overcome the max zoom issue. i came to the same
conclusion. If we can find a way to no use android scrolling mechanism, we
can overcome this limitation

**Comment by monsieurtanuki** [comment] 2017-07-28 04:41
@secaw: thank you for your bug report. I actually just reproduced it.

@spyhunter99: about your first remark, I guess it has something to do with my pending PR - which has no common code with this feature code (I started from scratch) and will eventually merge.

About your second remark, what I did in a similar project was to only focus on the LatLng of the map center - not on scrollX/Y - without using the standard `View.onScroll` behaviour.
Nevertheless I don't see a use case for zoom levels higher than 22.

**Comment by secaw** [comment] 2017-07-28 10:22
@monsieurtanuki: Yes, I actually just checked out your `MapTileApproximater` from feature #634, which is also working very nicely and exactly like @spyhunter99 proposes. Also the grey tiles (as described in #624 and #630) finally disappear and get replaced by scaled ones with `MapTileApproximater` as last provider. This is now working on tiles from the system cache only, would it be at all possible to generally integrate the mechanisms of `MapTileApproximater` in such a way, that always the tile with the last highest available zoom level gets scaled, no matter from which provider in the array (including archives) it's been coming?
Anyways, if this all gets merged at some point, will be a huge, huge step in overall usability improvement!

**Comment by monsieurtanuki** [comment] 2017-07-28 15:54
Just fixed the "x2 zoom offline" bug on my branch [feature/#640](https://github.com/monsieurtanuki/osmdroid/tree/feature/%23640). Confusions on the ScaleLooper.
@secaw, could you check if it's ok for you? There are side-effects if you go very deep and then back up, because the minimap and the standard map share the same memory cache. Would get unnoticed with `MapTileApproximater`.

Regarding your request about `MapTileApproximater`, the need for alternate sources makes sense but may be tricky. Should I use the memory cache as an input? But `MapTileApproximater` also writes in the memory cache. I'll think about it once the first version is delivered.

**Comment by secaw** [comment] 2017-07-28 19:54
Great, looking forward to testing the bug fix beginning of next week..

Regarding `MapTileApproximater ` and offline sources: users may be able to put custom offline maps on top of online sources. So what happens when being offline is that if e.g. you have an offline map from zoom 6 to 15 and are zooming into 16 you then get a scaled tile from cached online source of zoom level 5 instead of scaled offline tile from level 15, which would not be the desired outcome. I hope this description makes sense? So I think including all available sources for approximation would be very desirable. Thanks a lot for thinking about looking into this! Can imagine that it's not that trivial.

**Comment by spyhunter99** [comment] 2017-07-29 01:25
just tested this i love the fact that it's super smooth!

**Comment by spyhunter99** [comment] 2017-07-29 15:09
#329 related

**Comment by spyhunter99** [comment] 2017-07-31 10:52
@monsieurtanuki your branch no longer compiles

**Comment by monsieurtanuki** [comment] 2017-07-31 11:27
I got trapped between git branches. I'm about to push the missing files - files that are now on the master but were not when I started the branch. I hope this will fix things.
I'll do that within 30 minutes.

**Comment by monsieurtanuki** [comment] 2017-07-31 11:44
Done. Sorry about this confusion.

**Comment by MKergall** [comment] 2017-07-31 12:40
Just tested: excellent! Huge improvement. 

@spyhunter This feature, along with recent improvements on offline tiles, may legitimate a 6.0 version? 

@monsieurtanuki Two questions: 
- Is MapView.zoomToBoundingBox now able to stick to the bounding box requested, instead of the int approximation? 
- I seen in the demo Viewer that the floating zoom is available on the very first sample, but not on the others. Is the floating zoom available by default? 

I imagine that some APIs will have to be revisited. For instance, MapView.getZoomLevel (and possibly MapView.setZoomLevel).

**Comment by monsieurtanuki** [comment] 2017-07-31 15:05
What I did:
* I added the floating point zoom to MapView and all impacted interfaces and classes in "osmdroid-android"
* For that, I created "double-precision" versions of zoom methods and deprecated the old "int" ones - most of the time they just call the new "double-precision" version.
* I tested it on the first demo (`StartMapActivity`), which seemed appropriate

What should be done now or little by little:
* Upgrade the methods that I possibly didn't upgrade - for instance because they were not used in the first demo. That seems to include `MapView.zoomToBoundingBox`.
* Upgrade the other demos to the new double-precision zoom.
* In all those cases, everything should work very well now, but still relying on the "int" methods that call now the "double" methods. Therefore, still in "int" mode. And the upgrades should be very light to code, something like passing a double instead of an int as a parameter.

My focus was to implement new features without breaking the existing code. But I had no time for testing on all demos and all methods that I didn't know. I guess someone with a wide view on all demos would be more efficient than me on that part.

**Comment by MKergall** [comment] 2017-08-11 16:31
@monsieurtanuki OK, understood. 

I tested floating zoom to check how it behave with an opened InfoWindow on a Marker: the previous "bad" behaviour is still there: 
- the marker is scaled during zoom gesture, and sticks at the right position
- the infowindow is not scaled, but doesn't stick at expected position
Then, when gesture ends, everything is drawn correctly. 

I imagine the issue is that display during zoom gesture still relies on Android views animations. Is it feasible to get rid of that, and call onDraw during zoom gesture?

**Comment by monsieurtanuki** [comment] 2017-08-12 07:45
@MKergall: just opened #661 to discuss that specific matter

**Comment by spyhunter99** [comment] 2017-08-12 16:07
@MKergall how much of an issue is this? should we wait to merge this PR?

**Closed** 2017-08-12 21:27 UTC
Labels: enhancement

**Comment by spyhunter99** [comment] 2017-08-17 01:31
@monsieurtanuki think it would be useful and/or feasible to making the floating point zoom be optional or be able to be disabled? I'm thinking about potential issues users may have with custom layer setups.

**Comment by monsieurtanuki** [comment] 2017-08-17 06:19
@spyhunter99 could be a good idea. Another use case: people that don't like the 7.999 magnified pixels. I'll think about it.
