### ISSUE TITLE
is there any function to add marker on user click 

### ISSUE THREAD

**Issue by wisdomrider** [osmdroid/osmdroid#1284] opened 2019-02-27 11:09 UTC
Searched a lot but not got any help how can we implement marker when user clicks on mapview

**Comment by spyhunter99** [comment] 2019-02-27 12:20
The sample app has a number of press to plot examples

**Comment by monsieurtanuki** [comment] 2019-02-27 12:22
Like in the demo, "More samples / bookmarks / bookmark samples" with a long click.

**Comment by monsieurtanuki** [comment] 2019-03-06 08:03
@wisdomrider Did that answer your question? If so please close the issue.

**Comment by wisdomrider** [comment] 2019-03-08 09:19
yes i got it

**Comment by monsieurtanuki** [comment] 2019-06-07 09:25
It looks like the issue is solved: I'm closing it.
@wisdomrider Feel free to open a new one if needed.

**Closed by monsieurtanuki** 2019-06-07 09:25 UTC
