### ISSUE TITLE
Handling Device Low Disk Storage

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#435] opened 2016-10-06 04:33 UTC
This is actually kind of a feature request. I am observing below exception on an emulator, but it could well be on a real world device and I wonder, if osmdroid could do some checking of free memory or at least cleanup, when below the exception occurs:

`10-06 04:27:01.710 7978-9239/de.spieleck.app.badgers.debug E/SQLiteDatabase: Error inserting expires=1475812252000 key=47358738 tile=[B@27aea82 provider=Mapnik
                                                                             android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
                                                                                 at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                 at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
                                                                                 at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                                 at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                                 at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
                                                                                 at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
                                                                                 at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:133)
                                                                                 at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:230)
                                                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:296)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)`

**Comment by spyhunter99** [comment] 2016-10-18 22:59
#448 related issue

and roger this. Great idea. What should the expected behavior be then? 

Maybe on start up, set the cache max size to the current size + free disk space. This should force the trim mechanism however this is only triggered on application startup. As such, we should probably do some trickery to have the vacuum functions run periodically. It should be quick enough to attach to every tile insert event.

**Comment by spyhunter99** [comment] 2016-10-23 00:12
@InI4 might want to look at these changes. could always use another set of eyes

**Comment by InI4** [comment] 2016-10-23 08:56
I had a glance at the code and it seems, that it is trying to do some async database cleaning on startup?! Vacuum still commented out. But looks like a step in the right direction. 

I need to merge this into my (local) branch for unclear fixes of #411 and then build it into my product. I will keep you posted.

**Comment by InI4** [comment] 2016-10-23 09:32
"That" emulator stays calm now. Can it be, that some memory to database code was also helping, tile files are gone now.

**Comment by spyhunter99** [comment] 2016-10-23 12:18
The vacuum command apparently isn;t supported by sqlite. But basically on start up, it will purge expired tiles, which may or may not be desirable. The old tile system writer did the same task on startup so i just mirrored the logic. Now i'm thinking the logic may be wrong.

On low disk space it will trim, also on every insert, it will check the database size and trim if needed. I also added a bit of code to auto resize the max database size based on the available free space on the storage media.

**Comment by spyhunter99** [comment] 2016-10-23 18:26
merged

**Comment by spyhunter99** [comment] 2016-10-23 19:50
and my fix causing all kinds of issues, disabling the auto trimming for now

**Comment by InI4** [comment] 2016-10-29 10:03
Spontaneous question: Does a trim without vaccum shrink the database file size?

**Comment by spyhunter99** [comment] 2016-10-29 11:59
From what I've seen, yes.  But it may vary by android version

On Oct 29, 2016 6:04 AM, "InI4" <notifications@github.com> wrote:

Spontaneous question: Does a trim without vaccum shrink the database file
size?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/osmdroid/osmdroid/issues/435#issuecomment-257082945>,
or mute the thread

**Comment by spyhunter99** [comment] 2016-10-29 12:10
Actually this ticket needs more work.  App procure storage isn't working

**Closed** 2016-10-30 16:44 UTC
Labels: enhancement, ready to merge
