### ISSUE TITLE
Zoom level 19+ disables loading of additional tiles on scroll

### ISSUE THREAD

**Issue by semanticer** [osmdroid/osmdroid#470] opened 2016-11-10 15:58 UTC
I'm using osmdroid version 5.2 and when I zoom to level 19 or 20(my max level) tiles zoom normaly but when I try to just move(scroll/swipe) to other location it doesn't load any more tiles. 

Here is my stackoverflow question with more info:
http://stackoverflow.com/questions/40531783/osmdroid-zoom-level-19-disables-loading-of-additional-tiles-on-scroll

**Comment by miguel-porto** [comment] 2016-11-10 16:10
Maybe the same as [this](https://github.com/osmdroid/osmdroid/issues/354#issuecomment-256029602)? This only happens to me when using offline cached tiles...
IMHO, this is one of the most urgent issues, since it interferes a lot with the usability of the map when the user is offline...

**Comment by spyhunter99** [comment] 2016-11-11 12:16
@semanticer what you are describing is the situation in which you don't have tiles at zoom 19 or 20. The tiles from zoom 18 are stretched to fill the screen, but no tiles were available for higher than 18. Check your tile source and the cache to confirm tile availability at > 18

**Comment by miguel-porto** [comment] 2016-11-11 12:28
But the tiles from zoom 18 should always be stretched to fill the screen when tiles from >18 are not available in cache, right? (assuming offline)
In my situation, stretched tiles only appear if I reach them by zooming in. If I scroll, the stretched tiles won't appear. (I'm always talking offline)

**Comment by spyhunter99** [comment] 2016-11-11 14:43
No. what you are describing is the expected behavior. I think it's in the
FAQ

**Comment by miguel-porto** [comment] 2016-11-11 16:58
We're not talking about the same issue. My issue happens at any zoom level - I'm having it at level 11 for example: when you scroll the map, the new tiles won't load at zoom 11 if they're cached at a zoom < 11. But when I zoom out and in again, they will load and stretch as necessary. It seems like the panning isn't triggering loading the cache when it is in a lower zoom level.
I would try to fix this if I had the time, but right now it's difficult.
Best,
Miguel

**Comment by spyhunter99** [comment] 2016-11-11 21:14
ahh got it now. sounds like a duplicate of #354

**Comment by miguel-porto** [comment] 2016-11-11 23:49
Yes, probably the same as #354, I thought it might be related to this one also, but maybe not...

**Closed** 2016-12-04 19:20 UTC
Labels: duplicate
