### ISSUE TITLE
GEMF and JPG - problem and solution

### ISSUE THREAD

**Issue by jfk34** [osmdroid/osmdroid#615] opened 2017-06-09 16:27 UTC
Hello,

There is a problem with GEMF file containing JPG images.
In BitmapTileSourceBase.java / public Drawable getDrawable(InputStream aFileInputStream)
The call to BitmapFactory.decodeStream(aFileInputStream, (Rect)null, ex1); never exit because of a bug with InputStream ang JPG (probably the end of jpg tile is not found and stream is readed to the end...)

My solution is to copy inputstream to byte[] and decode it.

	@Override
	public Drawable getDrawable(final InputStream aFileInputStream) throws LowMemoryException {
		try {
			    byte[] buf = readBytes(aFileInputStream);

				BitmapFactory.Options bitmapOptions = new BitmapFactory.Options();
				BitmapPool.getInstance().applyReusableOptions(bitmapOptions);

				final Bitmap bitmap = BitmapFactory.decodeByteArray(buf, 0, buf.length, bitmapOptions);

				if (bitmap != null)
				{
					return new ReusableBitmapDrawable(bitmap);
				}

		} catch (final OutOfMemoryError e) {
			Log.e(IMapView.LOGTAG,"OutOfMemoryError loading bitmap");
			System.gc();
			throw new LowMemoryException(e);
		} catch (Exception ex) {
			Log.w(IMapView.LOGTAG,"#547 Error loading bitmap" + pathBase(), ex);
		}
		return null;
	}

	public byte[] readBytes(InputStream inputStream) throws IOException {
		// this dynamically extends to take the bytes you read
		ByteArrayOutputStream byteBuffer = new ByteArrayOutputStream();

		// this is storage overwritten on each iteration with bytes
		int bufferSize = 1024;
		byte[] buffer = new byte[bufferSize];

		// we need to know how may bytes were read to write them to the byteBuffer
		int len = 0;
		while (inputStream.available()>0)
		{
			len = inputStream.read(buffer);
			if (len>0)
			byteBuffer.write(buffer, 0, len);
		}

		// and then we can return your byte array.
		return byteBuffer.toByteArray();
	}

**Comment by spyhunter99** [comment] 2017-06-09 16:45
Nice find! This issue was reported before and is still open.  I'll see if I
can get it merged this weekend

**Comment by spyhunter99** [comment] 2017-06-16 22:45
@jfk34 feel like testing the based off the branch i pushed?

**Comment by spyhunter99** [comment] 2017-08-15 00:48
@monsieurtanuki ran into an issue with the map tile approximator not working as expected using the `OfflineTileProvider` along with the attached gemf file (unzip then put in /sdcard/osmdroid running this branch)
[usgssat-jpg.zip](https://github.com/osmdroid/osmdroid/files/1223837/usgssat-jpg.zip)

**Comment by monsieurtanuki** [comment] 2017-08-16 09:25
@spyhunter99 I copied the `.gemf` file and used demo "More Samples / Tileproviders / Offline Only..."
I saw the world in a satellite view.
If I zoom in, I see the bitmaps computed by `MapTileProviderBase.ZoomInTileLooper.computeTile`.
But if I go left or right, I don't see anything relevant: that's normal because the MapTileApproximater is not included in this demo:
* do we agree on what we actually see?
* would you like me to update this demo in order to include the `MapTileApproximater`?
* is it a more general problem, like "`MapTileApproximater` should be automatically set everywhere by default"?

**Comment by spyhunter99** [comment] 2017-08-16 11:12
@monsieurtanuki 

- yes seeing the same thing
- i added the approximater to the offlinetileprovider but now that i think of it, it's possible android studio/gradle didn't detect the change and never recompiled the aar.

**Comment by spyhunter99** [comment] 2017-08-17 01:02
confirmed, it was gradle/android studio being it's usual stupid routine. for something designed to detect incremental changes, it's certainly not very good at it.

**Comment by spyhunter99** [comment] 2017-08-17 01:15
and confirmed that the solution in this ticket resolves the issue

**Closed** 2017-08-17 01:16 UTC
Labels: bug, ready to merge
