### ISSUE TITLE
Restore ZoomButton's auto hide feature

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#823] opened 2017-12-24 17:39 UTC
## Issue Type

[ ] Improvement

## Description and/or steps/code to reproduce the problem

The previous setup, using Android's built in zoom buttons would leak references while the animation for fading the buttons in and out.

https://github.com/osmdroid/osmdroid/pull/741
https://github.com/osmdroid/osmdroid/issues/736

This issue to restore that function

**Comment by spyhunter99** [comment] 2017-12-24 18:28
In order to support the auto hide, we'll need to add mapview handling for onpause and onresume, which means all app that use osmdroid will also need to add these calls to activity or fragment using osmdroid.

**Comment by spyhunter99** [comment] 2017-12-30 16:01
@monsieurtanuki the current issue with this branch is that the zoom controls work intermittently and i have no idea why. Once in a state of not working, panning the map, even just by one pixel, usually restores the functionality. 

I'm starting to think that it may be easier to create and attach a custom view/layout to the map view and just rely on that instead of calculating our own hit test. The other option is to revert the zoom buttons overlay back to the original android based zoom controls

**Comment by monsieurtanuki** [comment] 2017-12-30 16:50
@spyhunter99 Initially, when I developed the current version of the zoom buttons, it was supposed to be a quick win in order to get rid of a harmless exception caused by the standard Android zoom buttons, when I was interested by no specific issue.

If it's a pain in the neck to fine tune our own version of zoom buttons, I guess we can forget it and switch back to the standard version. And survive with that harmless exception that nobody cares about - except those who read the logs.

**Comment by spyhunter99** [comment] 2017-12-31 14:25
sadly i think we should. We can revisit this for 6.1 or some other future version. 6.0 has already taken much longer than expected. The core features and performance are more important that zoom buttons IMO

**Comment by monsieurtanuki** [comment] 2017-12-31 14:29
Definitely.

**Comment by spyhunter99** [comment] 2017-12-31 14:58
ok, working on it now...

**Comment by monsieurtanuki** [comment] 2018-11-14 10:15
Fixed by #1190. Feel free to reopen.

**Closed by monsieurtanuki** 2018-11-14 10:15 UTC
Labels: enhancement
