### ISSUE TITLE
java.lang.OutOfMemoryError crash with high res tiles and 6.0.3 only

### ISSUE THREAD

**Issue by wharnisch** [osmdroid/osmdroid#1217] opened 2018-12-01 08:57 UTC
## Issue Type

[ ] Question
[ x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Problem can be reproduced with a small app (listing below):
o Start the app
o Rotate and scale the map very very intensely
o in the profile of Visual studio you can watch how memory footprint increases
o on a device with 256 MB heap for the app no memory is left after about half a minute
o ==> app crashes with java.lang.OutOfMemoryError

Problem can be reproduced only:
o with hires tile source (basemap.at in the app)
o with osmdroid 6.0.3

Did NOT manage to reproduce the problem
o with MAPNIK tile source
o with osmdroid 6.0.2

Here is the app to reproduce the problem:

public class MainActivity extends AppCompatActivity
{
  private org.osmdroid.views.MapView map = null;
  private final double
    centerLon = 13.5,
    centerLat = 47.3;

  private ITileSource getTileSourceBasemapAt()
  {
    return
      new OnlineTileSourceBase("bmaphidpi.basemap.at",
        1, 19, 512, ".jpeg",
        new String[] {
          "https://maps1.wien.gv.at/basemap/bmaphidpi/normal/google3857/",
          "https://maps2.wien.gv.at/basemap/bmaphidpi/normal/google3857/",
          "https://maps3.wien.gv.at/basemap/bmaphidpi/normal/google3857/",
          "https://maps4.wien.gv.at/basemap/bmaphidpi/normal/google3857/",
          "https://maps.wien.gv.at/basemap/bmaphidpi/normal/google3857/"
        },
        "Tiles © basemap.at, CC BY 3.0 AT")
      {
        @Override
        public final String getTileURLString(final long pMapTileIndex)
        {
          return String.format(Locale.ENGLISH,"%s%d/%d/%d.jpeg",
            getBaseUrl(),
            MapTileIndex.getZoom(pMapTileIndex),
            MapTileIndex.getY(pMapTileIndex),
            MapTileIndex.getX(pMapTileIndex));
        }
      };
  }

  private ITileSource getTileSourceMapnik()
  {
    return new XYTileSource("Mapnik",
      1, 19, 256, ".png",
      new String[] {
        "http://a.tile.openstreetmap.org/",
        "http://b.tile.openstreetmap.org/",
        "http://c.tile.openstreetmap.org/"
      },
      "© OpenStreetMap contributors, CC BY-SA");
  }

  @Override
  protected void onCreate(Bundle savedInstanceState)
  {
    super.onCreate(savedInstanceState);

    Configuration.getInstance().load(this,
      PreferenceManager.getDefaultSharedPreferences(this));
    map = new org.osmdroid.views.MapView(this);
    map.setTileSource(getTileSourceBasemapAt());

    map.setMinZoomLevel(1.0);
    map.setMaxZoomLevel(19.0);
    final float density = getResources().getDisplayMetrics().density;
    TileSystem.setTileSize(Math.round(256*density));
    map.setTilesScaledToDpi(true);

    map.getOverlays().add(new RotationGestureOverlay(map));

    map.setMultiTouchControls(true);

    setContentView(map);

    map.getController().setCenter(new GeoPoint(centerLat, centerLon));
    map.getController().setZoom(12.0);

    map.invalidate();
  }

  @Override
  public void onPause()
  {
    if (map!=null)
      map.onPause();
    super.onPause();
  }

  @Override
  public void onResume()
  {
    super.onResume();
    Configuration.getInstance().load(this,
      PreferenceManager.getDefaultSharedPreferences(this));
    if (map!=null)
      map.onResume();
  }
}

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

**Comment by wharnisch** [comment] 2018-12-01 09:46
Sorry I meant " profiler of Android Studio" NOT "profile of Visual Studio"

**Comment by monsieurtanuki** [comment] 2018-12-01 09:53
I'll try to reproduce it.

Could be caused by the notions of "protected tiles" we have: we keep in cache the tiles not only that are displayed but that are on the borders and zoom +-1. Perhaps it's too demanding with hi-res tiles. You can modify this set-up, cf. MapTileProviderBasic (or something like that, I have no access to my laptop), where we explicitly ask to put the borders and zoom+-1 to be kept.

How specific is it to 6.0.3? I have no idea, though there were minor changes on this topic.

**Comment by wharnisch** [comment] 2018-12-01 10:02
I am sure it is absolutely specific to 6.0.3. My app "Charging stations" in play store used versions 5.x.x and 6.0.0 to 6.0.2 with this hires tile provider - no "OutOfMemoryError" problems at all have ever been reported by any user. I wanted to upgrade my app to 6.0.3. Found the problem very soon while testing with 6.0.3 - it is easy to reproduce with 6.0.3 and I never managed to reproduce this with 6.0.2. even though trying hard.

**Comment by wharnisch** [comment] 2018-12-01 10:41
Found a workaround for the problem: If I add
`map.getTileProvider().getTileCache().setAutoEnsureCapacity(false);`
to the app in 6.0.3 the the problem is not reproduceable any more - the app runs stable.

So maybe the problem can be found in "feature/#1128 - faster MapTileCache management" from 6 Aug.

Maybe this helps.
Regards

**Comment by monsieurtanuki** [comment] 2018-12-01 15:01
@wharnisch Thanks for your work on this issue!

I had a look at it. 

Now in 6.0.3 the memory cache garbage collector is implemented that way: "we need to be certain that some tiles are in the _memory_ cache: the tiles currently displayed, and as we are greedy the neighboring tiles too (borders, zoom +1, zoom -1)".

What you changed with your `setAutoEnsureCapacity(false)` fix shouldn't be that important: it just says "recompute the maximum capacity including the neighboring tiles".

It's not that important because the neighboring tiles as considered "protected" anyway and won't be removed from the cache. But the optimization behind is "if we already know the (auto-ensured) needed capacity and if we have the same number of tiles in the cache or less, we know we don't have to remove any tile therefore we don't need to take the time to parse all the tiles".

It looks like something goes wrong: maybe in the computation of the number of "protected" tiles. Interesting.

**Comment by monsieurtanuki** [comment] 2018-12-02 12:38
@wharnisch Answers:
* "it happened with my Austrian tiles but not with Mapnik tiles": your Austrian tiles are 4 times bigger (512x512 instead of 256x256), that's a good reason (each of "your" tiles weighs 512*512*4 = 1Mb)
* "it happened with 6.0.3 but not with 6.0.2": after your investigation then mine, the difference in the versions is that in the latest version we raise the capacity by default (and you decided to switch that off, fair enough) _AND_ we say "if the capacity is big enough, don't bother to remove the useless tiles asap" (which can be a problem with little memory and big tiles) 

So far I wouldn't say there's a bug in 6.0.3. Maybe we're a bit generous with memory which can cause problem in some context (like big tiles), and I'm ready to edit the code in order to have useless tiles removed asap. Btw in your case in first approach I would rather remove the additional map areas (`map.getTileCache().getProtectedTileComputers().clear()`) than using `getTileCache().setAutoEnsureCapacity(false)`.

That being said, I didn't manage to reproduce this issue on my smartphone.
Let me ask you something.
In your issue description you say

> o Rotate and scale the map very very intensely
[...]
o on a device with 256 MB heap for the app no memory is left after about half a minute

"Rotate", I understand, but "scale the map very very intensely" and "about half a minute" I don't get it: as we start on zoom level 12 and max zoom is 19, it takes only 7 seconds (7x1s) to double tap from zoom 12 to zoom 19. How do you spend your time in order to reach half a minute? Panning the map, zooming again up and down? Maybe there's an additional reason for this issue.

**Comment by wharnisch** [comment] 2018-12-02 17:02
- I will test `map.getTileCache().getProtectedTileComputers().clear()`, thanks for the hint
- with "scale" I mean "scale  out and scale in alternately" - use the profiler in Android Studio to see how the consumed memory grows incessantly while rotating and scaling
- I don't think there's an additional reason, bug can be reproduced with the very simple test app
- Perhaps there is a possibility to detect such low memory situations and to stop caching or free memory BEFORE an OutOfMemoryError occurs.

Regards

**Comment by wharnisch** [comment] 2018-12-02 17:36
Here are the results of my profiler tests of the simple test app with 6.0.3 while rotating and scaling the map very very intensely:

- Using `cache.getProtectedTileComputers().clear()`: memory consumption is permanentely between 80 and 140 MB
- Using `cache.setAutoEnsureCapacity(false)`: memory consumption is permamentely between 130 und 200 MB
- Without using one of the above: memory consumption goes up more or less constantly, at 220 MB the app blocks (hangs) for some seconds, then the app gets terminated with the OutOfMemoryError

Regards

**Comment by MKergall** [comment] 2018-12-03 10:18
@wharnisch My 2 cents: did you configure your app with a large heap ? (android:largeHeap="true")

BTW, this is a very interesting subject. Having high-res tiles would be really better on modern devices. Our current method based on scaled tiles on osmdroid is just a workaround. Unfortunately, common map tiles providers do not provide such tiles!

**Comment by monsieurtanuki** [comment] 2018-12-03 10:57
@wharnisch Thanks for your profiler tests results. I still didn't manage to reproduce the issue, though.

Just PR'ed #1221, where I introduced a "stressed memory" parameter for the memory cache.
The default value is `false`, but in your case I obviously recommend to add `cache.setStressedMemory(true);` to your code:

> When true, all the tiles in the cache that eventually don't belong here are removed asap.
When false, we will still remove tiles that do not belong in the cache anymore, but not necessarily all of them: only the amount we need in order to fit the cache size.
Should be set to true when you have small memory and big tiles in order to avoid OutOfMemoryException.
Should be set to false for better performances.

In combination with `cache.getProtectedTileComputers().clear()` and `cache.setAutoEnsureCapacity(false)` you'll have the lowest possible memory use.

Btw the `float density = ...; TileSystem.setTileSize(Math.round(256*density));` lines in your code are useless as they are overridden by the next `map.setTilesScaledToDpi(true);` line.

Feel free to test #1221 and to close the issue if solved.

**Comment by wharnisch** [comment] 2018-12-04 07:34
@monsieurtanuki Thank you for your trouble. I will test "stressed memory" parameter the next days.

**Comment by asypost** [comment] 2018-12-07 01:36
And another:
`rg.osmdroid.tileprovider.modules.CantContinueException: org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase$LowMemoryException: java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 103856 free bytes and 101KB until OOM
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:174)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase$LowMemoryException: java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 103856 free bytes and 101KB until OOM
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:179)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:626)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 103856 free bytes and 101KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:626) 
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163) 
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) `

**Comment by spyhunter99** [comment] 2018-12-07 01:47
i would suggest you roll back to 6.0.2 for the time being

**Comment by wharnisch** [comment] 2018-12-08 08:55
For me combination of `cache.getProtectedTileComputers().clear()` and `cache.setAutoEnsureCapacity(false)` works best - moderate memory usage even with big tiles and no crashes any more. With "stressed memory" parameter set I did not observe any further improvement but in some rare situations I observed that tiles were not updated any more.

**Comment by monsieurtanuki** [comment] 2018-12-08 10:01
@asypost According to @wharnisch 's tests, I would suggest you to add the following code (still using 6.0.3):
````java
mapView.getTileCache().getProtectedTileComputers().clear();
mapView.getTileCache().setAutoEnsureCapacity(false);
````

@wharnisch Thanks for your thorough tests!
With the "stressed memory" parameter on, we are more aggressive regarding tiles in memory: if they are not on screen (given the use of `getProtectedTileComputers().clear()`) they are removed from the memory cache.
The rare cases you describe of tiles not being updated may be a "bad luck" bug. The garbage collection copies a `synchronized` list of tiles (therefore perfect at the time of the computation) into a not `synchronized` list (to be handled asynchronously, in order to remove useless tiles). Perhaps what you describe happens if by the time we remove an allegedly useless tile, it's useful again.
A solution would be, when removing a tile, to double-check `synchronized`ly if the tile finally deserves to be kept.
Another solution would be to rethink altogether the memory cache management.
Did you manage to identify a pattern (like fast panning, fast zooming in/out) when the tiles where not updated anymore?

**Comment by monsieurtanuki** [comment] 2018-12-11 08:46
Actually I said something wrong: the garbage collection is not performed asynchronously. It's not `synchronized` either.
Still thinking about simplifying the memory cache management...

**Comment by monsieurtanuki** [comment] 2018-12-11 16:30
@wharnisch Do you use several times the same tiles, like in a mini map?

**Comment by wharnisch** [comment] 2018-12-11 17:13
@monsieurtanuki Rare situations with problem can be reproduced with my small app posted above when using `cache.setStressedMemory(true)` and again scaling and rotating intensely.

**Comment by monsieurtanuki** [comment] 2018-12-11 19:30
Thank you @wharnisch for your quick answer. Unfortunately I don't manage to reproduce it.

That being said:
* I found a bug in the zoom out process that impacts the tile cache - I fixed it in #1229 and it could explain your rare situations
* I managed to provoke a xmas tree effect (that's the season) with a standard map and a minimap with the same tile provider (not only the same tile source) and in stressed memory mode, and I'm going to create an issue about it

**Comment by wharnisch** [comment] 2018-12-12 13:10
@monsieurtanuki I will try to test this next weekend.

**Comment by wharnisch** [comment] 2018-12-15 16:01
@monsieurtanuki 
Here are the results of my profiler tests of the simple test app with latest build 6.1.0-SNAPSHOT (including all commits until Dec. 13) while rotating and scaling the map very very intensely:

Using `cache.setStressedMemory(true)` and NOT using `mapView.getTileCache().getProtectedTileComputers().clear()` or `mapView.getTileCache().setAutoEnsureCapacity(false)`:
- memory consumption is permanentely between 100 and 160 MB
- NO OutOfMemoryErrors
- NO MORE of the "rare situations" where tiles are not updated any more.

Regards

**Comment by monsieurtanuki** [comment] 2018-12-16 15:38
@wharnisch Cool: it looks like the fix worked, doesn't it?

@asypost Did you find time to test with the additional lines of code I suggested and with latest build 6.1.0-SNAPSHOT?

In general I think that the solution that needs to be implemented in the "master" is the following _default_ options:
* empty "protectedTileComputers" list - people with specific needs (e.g. #812) still being able to fine-tune it
* `setAutoEnsureCapacity(false)` - I don't think it's relevant anymore, though ["It seemed to be a good idea at the time."](https://www.youtube.com/watch?v=0ieicflBG_Y)
* `setStressedMemory(false)`

**Comment by monsieurtanuki** [comment] 2018-12-17 11:00
I've just PR'ed #1235, and here are the new default values for `MapTileProviderBasic`:
* removal of protected tile computer zoom+1 (which was by far the greedier) - we only keep zoom-1 and the border
* `setAutoEnsureCapacity(false)`
* `setStressedMemory(false)`

Btw I also introduced the possibility to deactivate the "offline first" mode (`MapTileProviderBasic.setOfflineMode(boolean)`).

@wharnisch Feel free to test and close the issue if relevant.

**Closed** 2019-03-24 13:10 UTC
Labels: bug
