### ISSUE TITLE
LRUMapTileCache NoSuchElementException when clearing tiles

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#776] opened 2017-11-16 12:53 UTC
## Issue Type

[ ] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Crashreporter:
```
java.util.LinkedHashMap$LinkedHashIterator.nextEntry (LinkedHashMap.java:349)
--
  | java.util.LinkedHashMap$KeyIterator.next (LinkedHashMap.java:366)
  | org.osmdroid.tileprovider.LRUMapTileCache.clear (SourceFile:61)
  | org.osmdroid.tileprovider.MapTileCache.clear (SourceFile:82)
  | org.osmdroid.tileprovider.MapTileProviderArray.detach (SourceFile:81)
  | org.osmdroid.views.overlay.TilesOverlay.onDetach (SourceFile:118)
  | org.osmdroid.views.overlay.DefaultOverlayManager.onDetach (SourceFile:137)
  | org.osmdroid.views.MapView.onDetach (SourceFile:889)
```

Corresponding code (from `LRUMapTileCache`):
```
@Override
public void clear() {
  // remove them all individually so that they get recycled
  while (!isEmpty()) {
    remove(keySet().iterator().next());
  }

  // and then clear
  super.clear();
}
```

### Version of osmdroid the issue relates to:

6.0.0

**Comment by monsieurtanuki** [comment] 2017-11-16 17:40
What exactly is the Exception you get? It looks like a java concurrency issue between the moment of the `!isEmpty()` and the moment of the `next()`.
I didn't manage to reproduce the bug on my smartphone.
My assumption is that something like that would solve the issue:
````java
public void clear() {
	// remove them all individually so that they get recycled
	while (!isEmpty()) {
		try {
			remove(keySet().iterator().next());
		} catch (NoSuchElementException nse) {
			// as a protection
		}
	}

	// and then clear
	super.clear();
}
````

**Comment by spyhunter99** [comment] 2017-11-18 21:23
good catch

**Comment by spyhunter99** [comment] 2018-01-30 17:15
You're positive it was published with a recent snapshot?

**Comment by secaw** [comment] 2018-01-30 17:25
Yes.
Could it be, that `mWorking` is corrupting the `TileCache.clear()` procedure theoretically? Then the proposed deletion could be it.

**Comment by secaw** [comment] 2018-02-01 11:20
Update - to be more specific:
In version before above fix, there were actual crashes with `NoSuchElementException`.
In version with above fix, they actually are ANRs, so `NoSuchElementException` is raised, but then it seems to be hanging in the `while (!isEmpty())` loop. I'm almost positive now, that deletion of `mTileCache.clear()` as proposed above might solve the issue and will publish with that for testing.

**Comment by monsieurtanuki** [comment] 2018-02-01 16:48
I think we should be more specific about what we are supposed to do in the `detach` methods.
My assumptions are that:
* it should run very fast, as it's supposed to be called at critical moments (like an `Activity` being destroyed)
* we should implement _fail-safe_ code (like the empty `catch (NoSuchElementException nse)` clause I added in my first fix)
* possibly run async when the code may take time

**Comment by secaw** [comment] 2018-02-03 13:51
@monsieurtanuki I agree.
In this particular case, I wonder, if this is actually thread safe:

```
while (!isEmpty()) {
    remove(keySet().iterator().next());
  }
```
See for example https://stackoverflow.com/a/223929/4301846

> Note that Iterator.remove() is the only safe way to modify a collection during iteration; the behavior is unspecified if the underlying collection is modified in any other way while the iteration is in progress.

Maybe #915 fixes this because `mTileCache.clear()` is now only called after `mWorking` has been cleared, which might have caused interferences.

In addition, I noticed, that `mTileProvider.clearTileCache()` is called once again in `MapView.onDetach()`, so I'm not sure, we need it in `MapTileProviderArray` anyways...

**Comment by monsieurtanuki** [comment] 2018-02-03 16:09
@secaw Short comment
> In addition, I noticed, that mTileProvider.clearTileCache() is called once again in MapView.onDetach(), so I'm not sure, we need it in MapTileProviderArray anyways...

I would rather remove the call in `MapView.onDetach()`, as we may have several caches (for instance if we use a `MinimapOverlay`).

About the thread-safe way to remove all items, I'm not an expert, but I'd say `Iterator.remove()` looks better than what is currently implemented.

**Comment by secaw** [comment] 2018-02-03 21:58
@monsieurtanuki 

> I would rather remove the call in MapView.onDetach(), as we may have several caches (for instance if we use a MinimapOverlay).

Good point.
Looking at it closer, it's not clear, why this should even happen in `MapTileProviderArray` at all.
`clearTileCache()` should instead be called right from the super `MapTileProviderBase.onDetach()`, because in `MapTileProviderBase` the cache is being instantiated and logically should also be removed there.

**Comment by monsieurtanuki** [comment] 2018-02-05 17:48
@secaw
> clearTileCache() should instead be called right from the super MapTileProviderBase.onDetach(), because in MapTileProviderBase the cache is being instantiated and logically should also be removed there.

Fair enough. Anyway, I believe that you PR'ed your quick fixes regarding this issue - and hopefully they will be included in 6.0.0. But I just created #919 in order to go further on memory cache management.

**Comment by secaw** [comment] 2018-02-05 21:31
@monsieurtanuki Sounds good!

> But I just created #919 in order to go further on memory cache management.

**Comment by secaw** [comment] 2018-02-12 20:32
I think, this can be closed now!

**Closed** 2018-02-13 01:16 UTC
Labels: bug
