### ISSUE TITLE
Very fast perfomance degradation and app crash when using 6.1.6 osmdroid

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1389] opened 2019-08-29 05:52 UTC
Fast perfomance degradation and total application crash after moving, zoom in zoom out map.

## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[x] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I have a map with some polylines and markers on it. Use default "mapnik".
At each map move and/or zoom - I add new polylines and markers and remove objects that outside the map screen bounds (pls. see screen1).
For reproducing the problem: after application is openned, just enough to move or zoom in/out the map about 1-2 minutes. At each moving the application are freezing more and more.
After abbout 5 minutes - application totally crashes (pls. see screen2)
Log with crash info is log_6_1_0. In this log has some errors:
- E/OsmDroid: Error loading tile
    java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available 
- Waiting for a blocking GC Alloc

and etc.

Which version osmdroid:
- The problem occure if I use osmdroid 6.1.0. (pls. see log_6_1_0)
- If I use the same map but 6.0.2 osmdroid version - everything is Ok. I can move/zoom the map very long time (pls. see log_6_0_2)

![screen1](https://user-images.githubusercontent.com/29057366/63913778-07d7ae00-ca3a-11e9-89d6-98146e167a53.png)
![screen2](https://user-images.githubusercontent.com/29057366/63913785-0c03cb80-ca3a-11e9-9984-9a3cb2547050.png)
[log_6_1_0.txt](https://github.com/osmdroid/osmdroid/files/3554029/log_6_1_0.txt)
[log_6_0_2.txt](https://github.com/osmdroid/osmdroid/files/3554030/log_6_0_2.txt)

Stack trace of app crash, from error log is below: 
...
        at java.lang.Throwable.nativeFillInStackTrace(Native method)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:775)
        at java.lang.Throwable.<init>(Throwable.java:258)
        at java.lang.Error.<init>(Error.java:70)
        at java.lang.VirtualMachineError.<init>(VirtualMachineError.java:53)
        at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:58)
        at java.util.Arrays.copyOf(Arrays.java:3260)
        at com.android.internal.util.LineBreakBufferedWriter.ensureCapacity(LineBreakBufferedWriter.java:266)
        at com.android.internal.util.LineBreakBufferedWriter.appendToBuffer(LineBreakBufferedWriter.java:249)
        at com.android.internal.util.LineBreakBufferedWriter.write(LineBreakBufferedWriter.java:215)
        at java.io.PrintWriter.write(PrintWriter.java:473)
        at java.io.PrintWriter.print(PrintWriter.java:603)
        at java.io.PrintWriter.println(PrintWriter.java:756)
        at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
        at java.lang.Throwable.printStackTrace(Throwable.java:651)
        at java.lang.Throwable.printStackTrace(Throwable.java:713)
        at android.util.Log.printlns(Log.java:422)
        at android.util.Log.e(Log.java:251)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:176)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:183)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:149)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:131)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:112)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

### If it's a bug, version(s) of android this affects:

Android 9.0
Android 10.0

### Version of osmdroid the issue relates to:

6.1.0
6.1.6

**Comment by monsieurtanuki** [comment] 2019-08-29 07:42
@panovvitalik Could be related to #1299 (which maybe solves it) and #1383 (which may be a similar issue).
Do you by any chance use `MyLocationNewOverlay` or something like that?
What if you don't create/display the `Polyline`s and `Marker`s: do you still have this issue?

**Comment by panovvitalik** [comment] 2019-08-31 06:45
@monsieurtanuki 
I dont use MyLocationNewOverlay or something like...
If I don't create Polylines and Markers - everything is fine, on empty map: No Issue.
If I create only! Polylines: I have the Issue
If I create only! Markers: I have the Issue

**Comment by monsieurtanuki** [comment] 2019-08-31 07:47
@panovvitalik Then it looks like the issue is related to Markers, Polylines or just Overlays in general, not really to zooms. Or it's a memory usage side-effect.
That being said:
* if you remove Markers for performance reasons, that may be a wrong idea. When drawing, we loop on all Markers (of course), check if the Marker is likely to be on the screen (short test with coordinates and icon dimensions), and we display it (the more time-consuming step) only if it is on screen. Could you try your app without Polylines at all while always keeping all Markers?
* as a side effect, as your log displays the name of class `MapTileApproximater`, maybe the problem lies in the `MapTileProviderArray` you're using. I suggest that you try that:
````java
map.getTileProvider().getTileCache().getProtectedTileComputers().clear();
map.getTileProvider().getTileCache().setAutoEnsureCapacity(false);
````

**Comment by panovvitalik** [comment] 2020-07-12 08:03
I have tested the same scenario at 6.1.6 version. The same issue exists. 
But before the App crashed now I have following additional error messages in the error log:
(may be this info will be usefull...)

`E/OsmDroid: Error loading tile
    android.database.sqlite.SQLiteException: unknown error (code 0 SQLITE_OK): Native could not create new byte[]
        at android.database.CursorWindow.nativeGetBlob(Native Method)
        at android.database.CursorWindow.getBlob(CursorWindow.java:434)
        at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:47)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:614)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:125)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:30)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:41)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:919)`

`E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: vitalypanov.phototracker.pro, PID: 23912
    java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
        at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:63)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)`

So I have to stay with 6.0.2 version again (

**Comment by pasniak** [comment] 2020-07-14 20:06
You could try leak detector leakcanary and/or Android Studio profiler (where you can see the memory pile grow as you keep on doing some stuff such as not closing files or spinning threads...).

**Comment by panovvitalik** [comment] 2020-07-15 04:05
@pasniak 
What info do you want to see from profiler which helps to resolve the issue? Memory growing graph or what?

**Comment by pasniak** [comment] 2020-07-15 10:51
As you see the "memory growing" graph, you can click on it (assuming Allocation tracking is on) and see what is being allocated. The mountain should grow and Allocations/Shallow size columns will tell you Instances that keep being allocated and, most importantly the stacks at allocations. 

As the lib's user (multiple layers), I am pretty much on #master branch and it works fine on bunch of real devices, emu etc... I hit 227MB total and 300MB if zoom in/out at region scale...

Maybe check (set to null) infowindows attached to the elements you create?

**Comment by monsieurtanuki** [comment] 2020-07-15 12:32
@panovvitalik Did you try what I recommended on https://github.com/osmdroid/osmdroid/issues/1389#issuecomment-526809415?

**Comment by panovvitalik** [comment] 2020-08-04 09:40
@pasniak  @monsieurtanuki 
Thank you for the help. I think I have resolved the issue.
The problem was in infowindows attached to markers.

I have custom info windows for each marker on map. These info windows have specific custom layouts 
(with some textviews and imageviews)

I attached these views to my markers with code below:
```
Marker marker = new DistanceMarker(mapView);
MarkerInfoWindow infoWindow = new MarkerInfoWindow(R.layout.marker_track_openstreet, mapView);
marker.setInfoWindow(infoWindow);
```
THIS WAS THE ISSUE. And this was a reason of memory leaks.

When I run a profiler (@pasniak thank you for your advice again) I see a lot of AppCompatTextView and AppCompatImageView objects which are not freed.
It because of  dialog info window are сreated in the contructor of the Marker object (Layout inflater run inside contructor), not when I click on a marker and force to show info indow on screen. This behavior is very unexpected for me! 
So I had too much created dialog windows with images and texts as I have markers on the map. This was a disaster for the memory.

The solution is: 
Remove all marker.setInfoWindow calls and replace them with: OnMarkerClickListener and custom run of infoWindow.open(). Please see code below:

```
marker.setOnMarkerClickListener(new Marker.OnMarkerClickListener() {
                        @Override
                        public boolean onMarkerClick(Marker marker, MapView mapView) {
                            MarkerInfoWindow infoWindow = new MarkerInfoWindow(R.layout.marker_track_openstreet, mapView);
                            infoWindow.open(marker, marker.getPosition(), 0, 0);
                            return false;
                        }
                    });
```
So in this solution the dialog are created only when I tap on the selected marker - and this only one! dialog I need at the moment. The amount of RAM used has decreased significantly! 

I have tested new code with 6.1.8 version.

I think the issue can be closed

**Comment by monsieurtanuki** [comment] 2020-08-04 13:49
@panovvitalik I'm glad you solved your issue.
That being said, we should detach the info window when we detach the marker in order to leave a clean memory.
And I also like your solution that constructs the info window just in time.

**Closed** 2020-08-04 13:56 UTC

**Comment by xfeng-github** [comment] 2020-09-05 08:29
Can you tell me how to draw 1000 tags and still keep the program flowing

**Comment by monsieurtanuki** [comment] 2020-09-05 10:16
@xfeng-github What do you mean with "tags"? Opened InfoWindows? Or custom labels?
