### ISSUE TITLE
What causes different Y-coords of a tile in versions 4.2 and 5.6.5?

### ISSUE THREAD

**Issue by andronov-alexey** [osmdroid/osmdroid#668] opened 2017-08-16 06:06 UTC
Hi!
In my project I replaced old version 4.2(jar) with newer version from repo (5.6.5)
Here's the logs of getTileURLString calls of my custom XYTileSource:

> // osmdroid 4.2
> _tile.getX() = 1495, _tile.getY() = 1401
> _tile.getX() = 1496, _tile.getY() = 1401
> _tile.getX() = 1497, _tile.getY() = 1398
> _tile.getX() = 1496, _tile.getY() = 1400
> 
> // osmdroid 5.6.5
> _tile.getX() = 1496, _tile.getY() = 647
> _tile.getX() = 1495, _tile.getY() = 648
> _tile.getX() = 1497, _tile.getY() = 649
> _tile.getX() = 1497, _tile.getY() = 647

As you can see tiles' Y-coordinate calculates differently in new version.
So my question is how can I get Y-coordinate position of a tile as in old library version?
Any help would be greatly appreciated
PS: and thanks for the awesome library btw :)

**Comment by spyhunter99** [comment] 2017-08-17 01:16
there were no known commits that would effect this. Are you sure it wasn't tms coordinates you were seeing at one point?

**Comment by andronov-alexey** [comment] 2017-08-17 02:59
Thanks for reply, yes, zoom level and lat/lon are the same.
Here's the full log of getTileURLString of TileProvider for my current location:

> my location v5.6.5
> _tile.getX() = 6, _tile.getY() = 2, _tile.getZoomLevel() = 3
> _tile.getX() = 5, _tile.getY() = 3, _tile.getZoomLevel() = 3
> _tile.getX() = 6, _tile.getY() = 3, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 3, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 0, _tile.getZoomLevel() = 3
> _tile.getX() = 6, _tile.getY() = 0, _tile.getZoomLevel() = 3
> _tile.getX() = 6, _tile.getY() = 1, _tile.getZoomLevel() = 3
> _tile.getX() = 5, _tile.getY() = 2, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 1, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 2, _tile.getZoomLevel() = 3
> _tile.getX() = 5, _tile.getY() = 1, _tile.getZoomLevel() = 3
> _tile.getX() = 5, _tile.getY() = 0, _tile.getZoomLevel() = 3
> 
> my location v4.2
> _tile.getX() = 5, _tile.getY() = 6, _tile.getZoomLevel() = 3
> _tile.getX() = 6, _tile.getY() = 5, _tile.getZoomLevel() = 3
> _tile.getX() = 6, _tile.getY() = 7, _tile.getZoomLevel() = 3
> _tile.getX() = 5, _tile.getY() = 7, _tile.getZoomLevel() = 3
> _tile.getX() = 5, _tile.getY() = 4, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 5, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 7, _tile.getZoomLevel() = 3
> _tile.getX() = 6, _tile.getY() = 6, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 4, _tile.getZoomLevel() = 3
> _tile.getX() = 4, _tile.getY() = 6, _tile.getZoomLevel() = 3
> _tile.getX() = 5, _tile.getY() = 5, _tile.getZoomLevel() = 3
> _tile.getX() = 6, _tile.getY() = 4, _tile.getZoomLevel() = 3
And how its looks on the map:
---------my location v4.2
![my location v4 2](https://user-images.githubusercontent.com/3096785/29394048-19921820-8332-11e7-903b-a619454ade66.png)
---------my location v5.6.5
![my location v5 6 5](https://user-images.githubusercontent.com/3096785/29394050-1c123ac6-8332-11e7-8765-028b97ffae5c.png)
And here's some custom spot look:
---------custom location v4.2
![moscow ok](https://user-images.githubusercontent.com/3096785/29394148-b167b3e4-8332-11e7-8604-ce483a9f9e2f.png)
---------custom location v5.6.5
![moscow](https://user-images.githubusercontent.com/3096785/29394150-b310b4de-8332-11e7-82f1-60c542821a25.png)

**Comment by spyhunter99** [comment] 2017-08-17 03:05
can you post your custom tile source? this is unexpected behavior. It's possible that the cache is polluted, but I don't recall any changes related to the cache that would have caused this behavior. It looks like the either the TMS y inversion, or the X,Y coordinates were reversed somehow. There were some api changes from 4.x to 5.something related to custom tile sources. Specifically the constructor changed to drop an additional parameter. I doubt this is the problem though.

Would it be possible to clear the tile cache before each test? On 4.x it should be /sdcard/osmdroid/tiles. 5.1+ it's a sqlite database called cache.db in /sdcard/osmdroid/tiles/

**Comment by andronov-alexey** [comment] 2017-08-17 03:14
```
ITileSource m_tileSource = new NavitelTileSource ("Navitel",/* null,*/ 3, 17, 256, ".png",
    "http://dmapa.navitel.ru/navitms.fcgi?t=%08d,%08d,%02d&amp;hl=ru&amp;version=11",
    "http://dmapb.navitel.ru/navitms.fcgi?t=%08d,%08d,%02d&amp;hl=ru&amp;version=11",
    "http://dmapc.navitel.ru/navitms.fcgi?t=%08d,%08d,%02d&amp;hl=ru&amp;version=11",
    "http://dmapd.navitel.ru/navitms.fcgi?t=%08d,%08d,%02d&amp;hl=ru&amp;version=11"
);

/*NavitelTileSource .class*/

public class NavitelTileSource extends XYTileSource {

    public NavitelTileSource(String aName,
                             int aZoomMinLevel, int aZoomMaxLevel, int aTileSizePixels,
                             String aImageFilenameEnding, String... aBaseUrl) {
        super(aName, aZoomMinLevel, aZoomMaxLevel, aTileSizePixels,
                aImageFilenameEnding, aBaseUrl);
    }

    @Override
    public String getTileURLString(MapTile _tile) {
        Log.e("TAG", getBaseUrl() + ": _tile.getX() = " + _tile.getX() + ", _tile.getY() = " + _tile.getY() + ", _tile.getZoomLevel() = " + _tile.getZoomLevel());
        return String.format(getBaseUrl(), _tile.getX(), _tile.getY(), _tile.getZoomLevel());
    }
}
```
As I see, X coordinates are the same (just reordered), and Y coordinates are completely different from "normal" case
I'll try to clear cache a little bit later and tell the results

**Comment by spyhunter99** [comment] 2017-08-18 00:43
very strange. i honestly don't know. I don't believe anything changed that would cause this

**Comment by spyhunter99** [comment] 2017-08-20 13:39
there was some changes made to the caching system. namely the default switched from file system storage to sqlite.

**Comment by andronov-alexey** [comment] 2017-08-21 03:19
Seems like api changed. For example when I set tile source on my MapView as TileSourceFactory.MAPNIK, all works flawlessly :)

**Comment by spyhunter99** [comment] 2017-10-13 23:17
ok so it's possible that that tile source changed somehow.  You may want to contact them to figure out what happened. closing for now

**Closed by spyhunter99** 2017-10-13 23:17 UTC
