### ISSUE TITLE
Slight pause when pinch zooming in and out during tile loading

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#812] opened 2017-12-19 00:05 UTC
## Issue Type
See related issue #801 

[ ] Performance

## Description and/or steps/code to reproduce the problem

````
About the UX issue you mentioned: do you mean that the pinch gesture is smooth in itself but that you notice a break in the display of the tile every time the tile resolution changes (e.g. from 5.9 - which is tile 5 multiplied by 1.9 - to 6 - which is tile 6)?
What happens if you zoom in and out and in and out on the same location: do you still experience that little break?
````
````
Yes, it is exactly as you describe - the pinch zoom is smooth except for those little breaks when tiles from a higher resolution are loaded. It happens also when doing as you say, zooming in and out repeatedly in the same location. However, this does not happen on pinch zoom out - when pinch zooming out, the gesture is smooth all throughout the tile resolutions, tiles are replaced by lower resolution ones without any noticeable break.
But this is just a minor detail that is not of much importance.
````

### Version of osmdroid the issue relates to:

6.0.0

**Comment by spyhunter99** [comment] 2017-12-21 23:53
I'm not seeing the pause by the way. I'm not sure what @monsieurtanuki did, but it's amazingly smooth and fast. It's like a whole new app!

**Comment by monsieurtanuki** [comment] 2017-12-22 09:32
@spyhunter99 Thanks!

I don't see the little pause either, though I guess that if you reset the cache, when you zoom in you will see the gray background while the zoom+1 tile is loading. What could we do? Prepare a MapTileApproximater tile while zooming in?
The same thing is also likely to happen when zooming out, and in that case we don't have MapTileApproximater.

**Comment by miguel-porto** [comment] 2017-12-23 00:58
I cleared the cache and, with wi-fi on, when zooming in I still notice the little pauses when tile resolution changes. I don't see the gray background, the tile from the lower resolution will stay there until the one from the higher resolution loads. It is in this meantime that there is a little pause.
But if you both don't see anything, let's forget this issue for now. It's a minor problem anyway. As @spyhunter99 says, after the improvements with MapTileApproximater, this is like a whole new app! Really smooth and fast!

**Comment by miguel-porto** [comment] 2018-01-05 17:52
... I created a video shot so you can see this issue in action: [slight pause on zoom in](http://flora-on.pt/slight-pause.mp4)
You can notice the little breaks during pinch zoom in (when tiles change resolution), which is otherwise smooth. On zoom out there are no breaks, it's smooth all the way.

**Comment by monsieurtanuki** [comment] 2018-01-05 20:57
Nice video!
My comments:
* could you add a display of the zoom level (as you already display latitude/longitude). I would like to check if it happens precisely when the zoom level is an integer
* when zooming back out, we can see gray squares - it looks like your memory cache is not working well, what do you think about it?
* if you switch to another lighter tile source, does it still happen? Again, I'm wondering if memory is the issue or not
* could you upload another video zooming in, then when the first break happens, smoothly zooming back out, then zooming back in to the first break zoom level? Just double-checking that if everything is cached, that works well

My rough guess is that the memory management isn't as good as expected on your smartphone (possible causes: heavy tiles, small memory/cache, other apps at the same time) and that the MapTileApproximater, that works with memory cached tiles, has hickups because it's expected to run synchronously (assuming memory access is fast) and your memory access is too slow for that. That's just a guess, I haven't read the code.

**Comment by miguel-porto** [comment] 2018-01-06 21:18
Hi, thanks!
Maybe it's what you say, slow memory access, this is an old Nexus 5 with <2 Gb free space. Here you have a video showing that the pauses always happen even zooming in & out in the same place: [zoom in & out](http://flora-on.pt/slight-pause-in-out.mp4)
And you've got the zoom level at the bottom left. And yes, the pauses happen exactly when crossing the integer zoom levels (all).
Did not try a lighter tile source yet. But there are no other apps running, killed them all.
Another little issue that you can see (in the previous video) is that sometimes when zooming out, some tiles (or tile portions?) are not displayed at all. This is not very frequent, but happens now and then.
I don't know what you mean with the memory cache not working well - is there any place where we can configure it/check its settings?
Maybe if other people also find this issue, it could be solved by loading asynchronously..? Maybe it's the best bet, because some people (like me) need to work with some Gb of high-res cached tiles for offline use! But this is not a priority. What really worries me is #846.

**Comment by monsieurtanuki** [comment] 2018-01-07 00:25
Thanks for the new video!

I have this theory, that could explain #846 too: it's a matter of memory.
The tile display is partly based on the following assumption: "memory access is instant".
Imagine your screen displays (for integer zoom levels) 4x8 tiles.
When you're zooming in from zoom level 15.999 to 16, you need to retrieve 32 zoom 16 tiles, which is ok with low-res tiles, but takes more time (tenths of second) for hi-res tiles.
Icing on the cake: I even have a reason why it's not the same from zoom 16 to 15.999. It's because you need to reload 4 times less tiles as .999 tiles are displayed twice bigger.
About #846, I guess the additional frenzy effect is due to low memory - as opposed to hi-res tiles. By the time the LRU memory cached tile is removed, it's needed again. As it's needed and stored we need space therefore the next LRU tile is removed, but finally needed too. And so on.

Just to confirm this theory, I'd like you to try to reproduce both bugs with standard low-res tiles. Hopefully you won't be able to reproduce them, and it will be a good sign.

Could you also provide us with your tile set, or give us an idea about their characteristics (size, format png or jpg, ...)?

**Comment by miguel-porto** [comment] 2018-01-07 21:33
Great, I think the problem might well be what you suspect: if I set the overshoot cache to some big number (tried 300), all the problems go away - #846 also! It's super smooth now, except for the first time the tiles are loaded. I mean, when you zoom in the 1st time you still notice breaks. But after that, not any more, as they are not removed from memory. And the infinite redraw loop (#846) doesn't happen any more also, because tiles don't need to be reloaded from "disk" when you zoom in-out-in-out-in-out.
However, this is a bit "workaroundish". I mean, the infinite redraw loop problem is still there, just it has been workarounded by avoiding the unload-reload tile from memory so frequently. It would be good to have a fix for #846, and I think the theory you have might be correct - tile is removed, but needed again, and this happens for many tiles at the same time, so it ends up resulting in an infinite loop of removing-inserting because of not enough space for everyone. There should be a check for avoiding this situation, cause it ends up freezing the app.
At least, the default cache overshoot should be set to something [larger than 0](https://github.com/osmdroid/osmdroid/blob/0bad623dfd9bafb1632d8f87f2734ffc218128d7/osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java#L71), no?
As to the questions, I'm using Bing maps, but the #846 also happened with the default tile overlay (if I don't increase overshoot).
Thanks for the help, I think all my problems are solved now!

**Comment by monsieurtanuki** [comment] 2018-01-08 16:53
@miguel-porto I'm glad it helped!
I agree with you, setting "some big number" (why 300?) is not 100% satisfactory.
The problem may come from the fact that in `LRUMapTileCache` you set the number of tiles you want to keep in memory. Regardless of how much memory you actually have. Which makes sense functionally (you want to keep x tiles for the UX) but not technically (on Android your control over memory is also limited to what the system and the other apps are currently doing).
I guess a better fix would involve a max memory percentage (beyond which you must react in order to avoid the xmas tree effect), and possibly use the standard `android.util.LruCache` class.

Anyway, if you feel like closing issues and/or creating more precise issues, don't refrain! ;)

**Comment by shiroyagi** [comment] 2018-01-22 21:56
I have a similar problem and tried with b5db565f:
`Configuration.getInstance().setCacheMapTileOvershoot((short) 300);`
This eventually resulted in OutOfMemoryError with a 2GB device. 32 seems to work better, but occasional stutters are still present.

ps. should the Log in `MapTileProviderBase.rescaleCache()` be conditional on `Configuration.getInstance().isDebugTileProviders())`?  There is rather a lot of it.

**Comment by spyhunter99** [comment] 2018-01-22 23:17
@shiroyagi Just fixed the log statement. 300 is probably way too high. This is the quantity of images we are talking about here. Each image probably takes close to 200k in memory (assuming it's uncompressed bmp, not sure how android handles this). That's about 60MB of ram. Did you set the large heap attribute in your manifest? Even with that, most devices will only allow an app take around 500MB of ram max before android kills it without warning. Without large heap, the value is much smaller.

**Comment by shiroyagi** [comment] 2018-01-23 12:15
Ok, that explains it.  I guess if you zoom in and out through enough tile levels you are always going to purge them from memory so asynchronous loading may be a better solution?  It sounds like tiles are only scaled up, never down?  How about introducing some hysteresis to reduce disk/network access? eg. when zooming in load the next set of tiles at x.9,  and at x.7 when zooming out?

**Comment by monsieurtanuki** [comment] 2018-01-24 19:20
Just checked: `LRUMapTileCache` really implements a LRU cache behavior (cf. [http://www.makeinjava.com/access-order-linkedhashmap-using-java-example/](http://www.makeinjava.com/access-order-linkedhashmap-using-java-example/)) as a `LinkedHashMap` in "access order".

There might be a side effect in `MapTileApproximater`, which tries to retrieve (possibly from the LRU cache) tiles from other zoom levels. And therefore making them "newer", access order wise. Which may kick out relevant tiles from the LRU cache. I haven't tried to witness that behavior, though.

We can add checks about available memory or tile removal relevancy in `LRUMapTileCache.removeEldestEntry`, which is called every time `LRUMapTileCache.put` is used.

We could also be more directive and let `MapView` explicitly tell the LRU cache what is really important: the visible tiles. This way we could prevent visible tiles to be removed in `LRUMapTileCache.removeEldestEntry` by saying: "oh no, not this one". And even say: OK we reached the limit, but the eldest entry is a visible tile - let's find the eldest _not visible_ tile and remove it instead.

**Comment by monsieurtanuki** [comment] 2018-01-25 18:22
I just started a dev on the subject.

Apparently the LRU cache doesn't work 100%.
My new idea regarding tile cache is to:
* compute the list of tiles to be displayed (by all `TilesOverlay`s) _just before we display them_
* use this list in order to say to the cache - whatever happens, those tiles are important and deserve to be kept
* have potentially more flexibility, like "I not only want to keep the tiles on that list, but also all the tiles that surround them / one zoom higher / one zoom lower"
* use potentially less memory, saying something like "as soon as a tile is not to be displayed, remove it from the cache"

**Comment by miguel-porto** [comment] 2018-01-27 14:50
Hi,
I tested it, #903 fixed the Xmas tree effect! However, there seems to be still some problem. It seems that the `setCacheMapTileOvershoot` is not working so well as before. I mean, formerly, setting the overshoot to 300 solved all the problems. Now, even if I set it to 300, I still frequently get the pauses during zoomin-zoomout repeatedly in the same place, meaning that the tiles have been removed from cache despite that I forced it to be big. Further, the app now frequently freezes on detach, with no log messages thrown. Formerly, this freeze bug only happened when the overshoot cache was 0, when I set it to 300 it didn't freeze any more (on detach), but now it does.
Well, don't have more cues for now.
Best!

**Comment by monsieurtanuki** [comment] 2018-01-27 19:36
@miguel-porto I guess the idea is now not to use this ridiculous 300 value: I believe you overload the memory needs with that.
The idea would rather be to set the capacity to 0 (!) but to add some "hysteresis" to the cache as @shiroyagi suggested.
My latest dev was to list all the displayed tiles in order to protect them from memory erasure. Fine.
The next step would be to say: "memory-protect" not only this list of tiles, but also the corresponding zoom+1 and zoom-1 tiles. And maybe the tiles just after the border too.
What do you thinkbof that?

**Comment by miguel-porto** [comment] 2018-01-27 21:44
Yes yes I know 300 is not a good example, but that's not the point here now, because the problem also happens when setting to 0. Now the app frequently freezes on detach, no matter the overshoot cache value. This didn't happen in the previous version before the tile protection (if setting the overshoot to some value).
I tried to understand where in the code is the app frozen, but couldn't understand yet. I suspect there's some infinite loop triggered on detach. I'll try some more digging...

The "hysteresis" seems a good idea to minimize pauses in zoom in-outs in the same place, but if you don't load the tiles assynchronously, you won't get rid of the pauses on the first zoom.
Another idea would be to have a counter of how many times each tile has been requested. Those requested more times would be less likely to be erased. Don't know if in practice this would be any better, though.

**Comment by miguel-porto** [comment] 2018-01-27 22:00
Nope, the debugger won't show the line where the app has frozen. The last thing I hear from it is `I/OsmDroid: Database detached`, and it won't close.

**Comment by monsieurtanuki** [comment] 2018-01-28 13:34
@miguel-porto Several things need to be fixed:
* getting rid of the little pause you experience - possibly telling that we have the tile only when the tile is already properly loaded into the memory cache, and not as soon as it's found in the db
* upgrading to a not-LRU-anymore cache, as we know exactly which tiles we want, possibly introducing the hysteresis algorithm
* removing asynchronously the tiles from the cache

**Comment by shiroyagi** [comment] 2018-01-28 17:23
How about asynchronously loading the tiles from disk/network when they are not in the cache or does it do this already?  Whilst waiting either draw a greatly scaled tile from another zoom level or plain grey.

**Comment by spyhunter99** [comment] 2018-01-28 18:23
tile loading is async already (from disk/network/cache)

**Comment by monsieurtanuki** [comment] 2018-01-28 19:34
@spyhunter99 Of course there are async processes when fetching the tiles. But I think there's an additional problem with memory; my idea is to move the async one step further, in order to avoid the stuttering.

**Comment by shiroyagi** [comment] 2018-01-29 22:22
A thread pool?

**Comment by spyhunter99** [comment] 2018-01-30 00:13
I'm not seeing the pause on the start map fragment. The scale map tiles to dpi is off on that sample.

**Comment by monsieurtanuki** [comment] 2018-01-30 08:01
@shiroyagi Probably, something like the `ExecutorService` used in `MapTileModuleProviderBase`.

**Comment by snowle0pard** [comment] 2018-02-27 01:49
come up with the same problem, map pause while double-click to zoom in

**Comment by monsieurtanuki** [comment] 2018-03-10 11:02
Could be solved by #956. The idea is having more power about the tiles you want to keep in cache, therefore you need to set up the list of wanted tiles (cf. the comments in #956).
We'll take a further step with #930, where _pre-caching_ will be implemented.

**Comment by monsieurtanuki** [comment] 2018-04-10 14:11
Since #975 we have async tile pre-caching. Which should solve this issue.
@miguel-porto, @shiroyagi , @snowle0pard Feel like testing?

**Comment by miguel-porto** [comment] 2018-04-10 15:17
Sorry @monsieurtanuki for not giving further feedback on recent developments! Very busy with a variety of things. But yes, I feel like giving it a try ASAP! The branch title is promising.

**Comment by miguel-porto** [comment] 2018-04-14 21:27
It is indeed smoother! But it is still noticeable, even running on a recent fast device. But we're talking about very slight pauses now, I know I'm being too perfectionist. Does it need any configuration, or the default behaviour is to pre-cache +-1 zoom? (can we change this?)
I think the ultimate solution is not async pre-caching but async (post-) loading of requested tiles. I mean, the requested tiles would load async after they are requested and only be displayed when they're ready - but the map would not wait for them to go on, so no pause. Don't know if that's easy or possible to do in the current framework, it's just an outsider's idea!
Still didn't have time to explore the tile protection capabilities in depth...

**Comment by monsieurtanuki** [comment] 2018-04-15 09:32
@miguel-porto 
> It is indeed smoother! But it is still noticeable, even running on a recent fast device.

Now the only limit is the memory access and display speeds. Everything is fine on my 3 year old smartphone ;)

> But we're talking about very slight pauses now, I know I'm being too perfectionist.

Just by curiosity, can you upload a video of those pauses? The current fix is about tiles that are already stored in the db (or file) and that are now in a preventive way cached into the memory. For instance, zooming in and out and in and out +- 1 zoom level on the same area should show no noticeable pause.

> Does it need any configuration, or the default behaviour is to pre-cache +-1 zoom? (can we change this?)

The default configuration is +-1 zoom and 1 tile border around the displayed tiles. You can reconfigure that in order to suit your specific needs: just have a look at the constructor of class `MapTileProviderBasic`:
````java
getTileCache().getProtectedTileComputers().add(new MapTileListZoomComputer(-1));
getTileCache().getProtectedTileComputers().add(new MapTileListZoomComputer(1));
getTileCache().getProtectedTileComputers().add(new MapTileListBorderComputer(1, false));
````

> I think the ultimate solution is not async pre-caching but async (post-) loading of requested tiles...

That's already the way things work. Just stop the internet connection and pan the map to unknown tiles: the map moves will be smooth and won't stop for download. Restart the internet connection: the unknown gray tiles will automatically be downloaded and displayed.

> Still didn't have time to explore the tile protection capabilities in depth...

If you want to protect a specific area, you can add to `getTileCache().getProtectedTileComputers()` your own _ad hoc_ implementation of `MapTileListComputer`, something like this:
````java
getTileCache().getProtectedTileComputers().add(
		new MapTileListComputer() {

			private MapTileList mList;

			@Override
			public MapTileList computeFromSource(MapTileList pSource, MapTileList pReuse) {
				if (mList == null) {
					mList = new MapTileList();
					mList.put(8, 10, 25, 13, 40);
					mList.put(7, 5, 12, 6, 20);
				}
				return mList;
			}
		});
````

**Comment by monsieurtanuki** [comment] 2018-07-09 13:51
@miguel-porto ping
Still experiencing the slight pause?

**Closed** 2019-03-24 13:13 UTC
Labels: performance

**Comment by sobolvb** [comment] 2020-01-21 04:24
I have exactly the same problem. Surprisingly, after so many years, the solution is still not explicitly indicated anywhere. Also, for some reason, the cache is deleted when I close the fragment. All tutorials are pretty old and no deprecated solutions are mentioned there.
