### ISSUE TITLE
Crash when updating from 6.0.0 to 6.0.2 due to cache database locked

### ISSUE THREAD

**Issue by secaw** [osmdroid/osmdroid#1005] opened 2018-04-19 09:37 UTC
## Issue Type

[X] Bug

## Description and/or steps/code to reproduce the problem

Update your app with osmdroid 6.0.0 to osmdroid 6.0.2 with a cache database > 400 MB. On first map launch it will crash if tiles are to be downloaded immediately and written with SqlTileWriter.saveFile, because the database is locked. I take this is caused by the database index creation update in #973 ? On second launch it's working again.

```
04-19 10:39:39.749 E/SQLiteDatabase: Error inserting tile=[B@cb96fbd expires=1334919638000 provider=Mapnik key=905965568
	android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
		at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
		at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
		at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
		at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
		at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
		at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1464)
		at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:150)
		at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:255)
		at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:315)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at java.lang.Thread.run(Thread.java:764)
04-19 10:39:42.265 E/SQLiteDatabase: Error inserting tile=[B@5d34fd6 expires=1334880026000 provider=Mapnik key=905973758
	android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
		at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
		at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
		at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
		at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
		at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
		at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1464)
		at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:150)
		at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:255)
		at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:315)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at java.lang.Thread.run(Thread.java:764)
04-19 10:39:42.578 E/AndroidRuntime: FATAL EXCEPTION: Thread-4
	java.lang.NullPointerException: Attempt to invoke virtual method 'long java.io.File.length()' on a null object reference
		at org.osmdroid.tileprovider.modules.SqlTileWriter.runCleanupOperation(SqlTileWriter.java:114)
		at org.osmdroid.tileprovider.modules.SqlTileWriter$1.run(SqlTileWriter.java:69)
		at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
		at java.lang.Thread.run(Thread.java:764)
```

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment] 2018-04-19 10:48
@secaw Looks like you're right, the way you describe it the index creation and the tile insert happen at the same time and from different `SqlTileWriter`s.

From what I read in [SO](https://stackoverflow.com/questions/2493331/what-are-the-best-practices-for-sqlite-on-android/3689883#3689883), we should have only one open database at the same time (on the same file I mean). And this is not the case, as every `SqlTileWriter` opens its own.

I'll fix it by transforming `SqlTileWriter` into a singleton.
Provided that I can reproduce your issue, I should be able to fix it very soon.

**Comment by secaw** [comment] 2018-04-19 12:02
@monsieurtanuki Great, looks like an important overall fix! I will save old cache DBs on other device for future testing.

**Comment by monsieurtanuki** [comment] 2018-04-21 14:04
I managed to reproduce the issue:
* running 2 parallel `Thread`s
* the first one drops and creates the `SqlTileWriter.COLUMN_EXPIRES_INDEX` index (in a x100 loop)
* the second one saves a tile (in a x100 loop)

````
E/SQLiteDatabase: Error inserting key=8358680908399640576 tile=[B@32c5c2c1 provider=debug
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:952)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1609)
        at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1525)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:173)
        at org.osmdroid.samplefragments.events.SampleIndexCreation$2.run(SampleIndexCreation.java:74)
        at java.lang.Thread.run(Thread.java:818)
````

And with the fix I PR'ed in #1008 there are no locks anymore.

**Comment by monsieurtanuki** [comment] 2018-04-24 15:38
@secaw 
> I will save old cache DBs on other device for future testing.

Tested successfully with #1008?

**Comment by secaw** [comment] 2018-04-24 18:02
@monsieurtanuki Did some tests now:

- DB Update is working without crash
- Update (first launch with new version) on older device (Xperia Z1 Lollipop) with cache.db > 500MB is taking about 10 seconds! No map tiles shown during this process. End users probably need to be notified.

On second test I deleted updated cache.db / cache.db-journal and recopied old ones, with the result of ongoing logs of `android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database` and no tiles shown. Closing the app doesn't help, just reinstalling / rerunning from AS.
I figured, that in the end we indeed need to close the DB. Tested the following in `SqlTileWriter.onDetach` and it seems to do the trick. Any reason, why we shouldn't close the DB even when detaching everything else? DB seems to stay locked internally forever...

```
@Override
public void onDetach() {
    if(mDb != null) {
        mDb.close();
        mDb = null;
    }
}
```

**Comment by secaw** [comment] 2018-04-25 12:33
@monsieurtanuki 
> Are you talking about tiles you know are in the database?

No, tiles are also not shown, when they just can not be stored (in this case due to db being busy writing the index). So no matter, if they are in cache or not.

> In that case there's nothing to do, except write a note

Yes, that's what I meant.

> I guess it's rather a problem of file rwx rights.

That's what I initially thought as well, but it did work before the update and my proposal with closing the db actually fixes the issue!

> Regarding onDetach/close...

Well, I might not be familiar with the `static` state of a database. In my app I'm using an app db singleton, that I also never close, but it's in the app data storage. Whenever I use a publicly accessible db file, I always close it after use, otherwise the connection is leaked. I don't see a drawback with closing the cache db in `onDetach` like proposed. You are also doing it the same way in `SqlTileWriter.refreshDb()` ?
```
public void refreshDb() {
        synchronized(mLock) {
            if (mDb != null) {
                mDb.close();
                mDb = null;
            }
        }
    }
```

> What I can do though is introduce a use counter...

I don't think that would work, as I'm sure, not every `getDb` will at some point be followed by an `onDetach`.

**Comment by InI4** [comment] 2018-04-25 12:38
Didn't read the code yet, but the problem is, that index creation may take long. Question is, if you can provide an API call to trigger early index creation. I.e. my app has a splash screen, it would be easy to trigger index creation then and would run while various other things initialize and before the map activity is launched.

**Comment by monsieurtanuki** [comment] 2018-04-25 13:32
I found an interesting article called [Transactions and threads in SQLite on Android](https://medium.com/inloopx/transactions-and-threads-in-sqlite-on-android-215e46670f2d), which also pointed me to [SQLiteDatabase.html.enableWriteAheadLogging()](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#enableWriteAheadLogging%28%29):
* > [By default] it is not possible for reads and writes to occur on the database at the same time
* > it’s totally OK to not close the DB connection explicitly in your code and you will not need to handle this case

@secaw An explicit drawback is that when Thread-1 calls `getDb()` it gets the db and plans to use it, but if Thread-2 just called `onDetach()` 1/10000th second later, the db referenced by Thread-1 is closed when it uses it.
The `refreshDb()` action is supposed to be rather an admin task (something strange happened to the db, or we explicitly changed the db file path) than something to run each time the end-user tilts its screen. Opening and closing a db takes resources, and we also have to deal with async downloads too.
I need to try your "delete/copy" database experiment.

@InI4 Indeed, a `SqlTileWriter.runExpensiveAdminTasksDuringSplashScreen()` method could help.

**Comment by secaw** [comment] 2018-04-25 14:40
@monsieurtanuki Ok, I get your point. What about introducing a `SqlTileWriter.closeDb()`, which at the moment would be a copy of `refreshDb()`? I would certainly use it when cleaning up the map activity and knowing, nothing else is going on. By the way, I like the possibility of exchanging the cache db, e.g. doing this across devices etc ...

**Comment by monsieurtanuki** [comment] 2018-04-25 15:16
@secaw I tried to reproduce your `SQLiteReadOnlyDatabaseException` test but didn't manage to.
Just tested on my smartphone:
1. check if my cache db location is reachable from my laptop. It is (`/storage/emulated/0/osmdroid/tiles`)
1. close my osmdroid demo app. Android app selector => close
1. cut `cache.db` and `cache.db-journal` to my laptop. File sizes are 83Mb and 200Kb.
1. restart osmdroid. Everything works as expected, from an empty writable db.
1. close my osmdroid demo app. Android app selector => close
1. check `cache.db` and `cache.db-journal`. File sizes are 2Mb and 60Kb, which is acceptable
1. set the original files `cache.db` and `cache.db-journal` as read only on my laptop (windows), paste them back into osmdroid cache location, overwriting.
1. restart osmdroid. The read-only property is automatically unset for both files (for the record I cannot set this property for those files on my smartphone with Windows Explorer; I could only do that for the files when on my laptop). Therefore not only I get my data back, but the db is writable, and I could travel a bit on the map on new geo places
1. check `cache.db` and `cache.db-journal`. File sizes are 85Mb (bigger) and 200Kb (exactly the same size), which is acceptable
1. looking for `SQLiteReadOnlyDatabaseException` in LogCat. Cannot find any.

This worked as expected by me, except for Android dismissing the read-only file property. And I didn't change anything to my code regarding closing the database.
Is there anything slightly different you did in your own test? Maybe the differences come from an Android version file management discrepancy.

About your latest comment:
* `refreshDb()` is designed exactly for your need - a clean db close decided by an admin. We don't need an extra `closeDb()` method.
* I like the idea of reusing the `cache.db` file too, and just did on Window (OK, I did nothing really interesting but I connected to the database and ran a `select count(*) from tiles;`)

**Comment by secaw** [comment] 2018-04-25 15:46
@monsieurtanuki Thanks for double checking.
The difference might be, that I copy an old cache.db (without new index). So the problem probably is, that while db connection stays open, an already updated db is expected, but it's not there, the index is missing...
By the way - on Android 7.0 instead of `android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database` I get `java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase:` logs for each tile (never ending).
Haven't actually tried with updated db.
Might be an edge case, but anyways - will use `refreshDb()` on map activity end, just to make sure...

**Comment by monsieurtanuki** [comment] 2018-04-25 16:05
@secaw The index isn't necessary for the database structure. We build it in the garbage collection phase that doesn't even need it - it's just faster. What do you mean with "while db connection _stays open_": don't you properly close your app before doing anything with `cache.db`?

The logs you describe about Android 7.0 look more like some `db.close()` that happened before writing tiles.

Following @InI4's suggestion, I'm developing `interface SplashScreenable`. I may commit today.

Btw, about SQLite on Windows with my copy of `cache.db`:
* when I tried to create a table (`create table tiles_tmp1 as select * from tiles;`), I had the following message: `Error: attempt to write a readonly database`. I then closed the db, set the file property back to read/write, and everything went fine.
* during the previous `create table as` statement (that takes about 5 seconds) the `cache.db-journal` is created, then deleted

**Comment by monsieurtanuki** [comment] 2018-04-26 20:51
@secaw I'll test that tomorrow.
The only thing that puzzles me in your comment is how/why the index creation would corrupt a database that is implicitly closed by the app being destroyed (your "BUT" bullet)

**Comment by monsieurtanuki** [comment] 2018-04-27 12:31
@secaw Just tried what you tested but I couldn't reproduce the database corruption.
My assumption is that in your case the corruption might come from async `cache.db` and `cache.db-journal` (cf. [How To Corrupt An SQLite Database File](https://www.sqlite.org/howtocorrupt.html)).
Could you redo the same test copying/deleting/pasting back both files?

If I sum up my thoughts:
* we need at most one instance of the database in the app
* if we have several instances, we may have crashes & database locks when 2 instances are writing
* with one instance of database, we won't have database locks, but there cannot be more than one action (read or write) at the same time (the latter queries are automatically queued)
* therefore every long running database query will postpone all the other contemporaneous queries - it makes sense then to run only small queries (if possible) and to run them not in the UI thread (to avoid ANR)
* we don't need to close explicitly the instance of the database - it will be closed implicitly when the app terminates
* if ever we need to copy the database, we need first to ensure that the database is properly closed (either by terminating the app or by explicitly closing the database using `refreshDb()`) (and of course not reopen it!), and then copy both `cache.db` and `cache.db-journal`

**Comment by monsieurtanuki** [comment] 2018-04-27 19:08
@secaw Transactions are about data modifications (insert update delete), and their purpose is to maintain functional data integrity.
If you give me $100 it's a 2 step atomic transaction: -$100 for you, +$100 for me. The whole transaction either succeed, or fail. The 2 steps are both committed, or both rolled back.
In the case of select cursor there's no data modification.
In osmdroid we insert tiles one by one, each time with an implicit one step transaction.
Not sure about index creation in SQLite, but there's a fair chance it's also an implicit one step transaction (data modification of admin tables).

Just to confirm again: whenever you talk about `cache.db`, you do the same thing (copy delete paste) with the `cache.db-journal` file, right? Assuming you have a journal file (in the same directory).

**Comment by secaw** [comment] 2018-04-27 20:36
@monsieurtanuki Yes, always both files.
I remember transactions are making SQLite singleton thread safe on Android, but it's some time ago...

**Comment by monsieurtanuki** [comment] 2018-04-28 08:52
@secaw If I sum up:
* before, we had potentially several database instances working at the same time, and the index creation (run by the garbage collector) sometimes crashed when running during tile upserts (run by the downloader on another database instance)
* my idea was to use a kind of database instance singleton, shared by whoever wants to use the database. With a singleton there cannot be crashes, because SQLite will only deal with one action at a time, which solves the current issue
* this database instance singleton should never be explicitly closed because other processes potentially use this instance
* this database instance singleton will eventually be implicitly closed when the app terminates
* there's a method to explicitly close the database if needed called `SqlTileWriter.refreshDb()`
* you experienced database corruption with the singleton system, but _only_ (is that correct?) when trying to copy / paste the database files (`cache.db` and `cache.db-journal`) without explicitly closing the database - there are still database corruption when you terminate the app and therefore _implicitly_ close the database. For the record I never experienced database corruption doing the same tests, making it harder for me to understand what's actually going on.

Focusing on the current problem:
* you experienced database corruption with the database instance singleton system, only when doing admin tasks (replacing the database files)
* your fix suggestion is to explicitly close the database

My latest thoughts on the subject:
* assuming the database corruption only potentially happens during admin tasks, we could imagine a "database safe" mode for admins where we refuse any incoming database query and explicitly close the database, in order to let the admin copy / paste / delete the database
* another solution would be to use a counter +-1 each time a user uses the database, and explicitly close the database when the counter is 0. We can have control over this counter without any problem as the database is virtually a private member of `SqlTileWriter`. There could be thread concurrency side effect though.

**Comment by monsieurtanuki** [comment] 2018-05-02 08:05
@secaw Could you upload your saved versions of `cache.db` and `cache.db-journal`? I'm very puzzled by the behavior you described...

**Comment by secaw** [comment] 2018-05-02 11:39
@monsieurtanuki Thanks for info and thoughts, unfortunately I won't be able to check and get back in detail before the end of the week...

**Comment by secaw** [comment] 2018-05-03 15:29
@monsieurtanuki Finally had the time to do some more tests and I think I managed to find the reason for the reported copy misbehavior: In the end it seems to be an MTP connection problem related to not explicitly closed databases!
If I do the following:
- Copy old cache.db + journal from Windows to Android device
- Start app to update with index etc
- Close app task
- Copy back updated cache.db + journal to Windows (version 1)
- Copy cache.db + journal on the Android device with a file manager internally to a new location
- Copy those cache.db + journal to Windows (version 2)

Then version 1 and 2 have different file sizes with version 1 smaller than 2, thus version 1 being corrupted!
Also if I try to open version 1 and 2 in an SQLite browser on Windows, only version 2 is browsable.
The difference with explicitly closing the db before copying probably is that when closing, file info will finally be publicly written to the file system and this way the file being usable for the MTP connection.

Now there are many misbehaviors related to MTP connection between Android and Windows anyways, so I'm positive now, we can live with that - there's not much we can do. A solution might be to do a media scan on the cache files before closing the app. I might try this at one point as I'm doing it with other files in order to make them visible over MTP at all.

So again, in the end this is not an osmdroid issue, it just became obvious after migrating to static db usage. Thanks for the energy and time!

**Comment by monsieurtanuki** [comment] 2018-05-04 08:38
@secaw OK then! Sounds like we can close the issue now - can't we?

**Closed by monsieurtanuki** 2018-05-04 08:38 UTC
Labels: bug
