### ISSUE TITLE
Crash when browsing map

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1078] opened 2018-07-05 05:18 UTC
--------- beginning of crash
07-04 14:39:17.538  5419  5419 E AndroidRuntime: FATAL EXCEPTION: main
07-04 14:39:17.538  5419  5419 E AndroidRuntime: Process: ..., PID: 5419
07-04 14:39:17.538  5419  5419 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect android.graphics.drawable.Drawable.getBounds()' on a null object reference
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at org.osmdroid.views.overlay.Marker.hitTest(Marker.java:404)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at org.osmdroid.views.overlay.Marker.onSingleTapConfirmed(Marker.java:409)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at org.osmdroid.views.overlay.DefaultOverlayManager.onSingleTapConfirmed(DefaultOverlayManager.java:273)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at org.osmdroid.views.MapView$MapViewDoubleClickListener.onSingleTapConfirmed(MapView.java:1509)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6595)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-04 14:39:17.538  5419  5419 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Sometimes crash when browsing map

## Environment
Android 8.0

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment] 2018-07-05 12:54
@panovvitalik 
> Sometimes crash when browsing map

It looks like the crash happens precisely when you perform a single tap (instead of just panning the map): could you confirm that?

Do you have `Marker`s on your map?

**Comment by panovvitalik** [comment] 2018-07-05 14:45
Maybe..., first I tap the map, next I try to drag for browsing - maybe crash cause at first step.
Of course I have markers on map - perharps I tap on marker when trying dragging...
Map looks like below (in attachment):
![screenshot_20180705-173957](https://user-images.githubusercontent.com/29057366/42330060-f1078a7e-807a-11e8-8d6d-1a384f02952e.jpg)

**Comment by panovvitalik** [comment] 2018-07-05 14:49
Today crashes were again - at this time when I zoom in the map (double tab).
But again - mey be crashing happens at first tap - I'm not sure.

Do you have a workaround for it? 
Can I catch this exception?, instead of my app is crashing each time :(((
Pls. help.

--------- beginning of crash
07-05 14:03:14.459  4653  4653 E AndroidRuntime: FATAL EXCEPTION: main
07-05 14:03:14.459  4653  4653 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 4653
07-05 14:03:14.459  4653  4653 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect android.graphics.drawable.Drawable.getBounds()' on a null object reference
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at org.osmdroid.views.overlay.Marker.hitTest(Marker.java:404)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at org.osmdroid.views.overlay.Marker.onSingleTapConfirmed(Marker.java:409)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at org.osmdroid.views.overlay.DefaultOverlayManager.onSingleTapConfirmed(DefaultOverlayManager.java:273)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at org.osmdroid.views.MapView$MapViewDoubleClickListener.onSingleTapConfirmed(MapView.java:1509)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6595)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-05 14:03:14.459  4653  4653 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by monsieurtanuki** [comment] 2018-07-05 16:21
The problem is that there's a Marker with a null icon.

The solutions:
* maybe you explicitly set a Marker's icon to null (perhaps to make it disappear, if that works?), and that causes the crash
* anyway with a null icon the method that currently crashes ("do I tap on this Marker?") should return false - I can fix that by tomorrow

**Comment by panovvitalik** [comment] 2018-07-05 16:48
"maybe you explicitly set a Marker's icon to null" 
No, I don't set icons to null manually. But - when I browse the map, I clear all markers (with calling: marker.remove() and/or mapView.getOverlays().removeAll()) and create new ones. 
I think, single tap map's event occur at the same moment - and may be event's procedure try to process markers which I have just deleted. Maybe this is the reason of this bug....

"...I can fix that by tomorrow" thank you very much. 
And when this fix can released in new version?

**Comment by monsieurtanuki** [comment] 2018-07-05 19:58
> when I browse the map, I clear all markers (with calling: marker.remove() and/or mapView.getOverlays().removeAll()) and create new ones

Is there a specific reason why you remove/recreate the markers? I mean, if it's for performance reasons when you have tons of markers but only few currently visible on the map, there's a recent optimization for that matter, therefore you shouldn't do that and always keep the same list of Markers, on the current visible map and beyond.

My guess is that those constant removal of `Marker`s leads to somehow async calls to `Marker.onDetach`, setting `mIcon` to `null`, and therefore causing the bug.
Or perhaps you happen to use `Marker.cleanDefaults` (setting `mDefaultIcon` to `null`)?

My suggestion: keep the same list of `Marker`s and don't remove/recreate them constantly.
My action: I'll just add a `mIcon == null` test and PR tonight.
Regarding the version availability, I'll let @spyhunter99 answer.

**Comment by monsieurtanuki** [comment] 2018-07-05 20:41
Just PR'ed and merged the fix in #1082.

**Comment by monsieurtanuki** [comment] 2018-07-05 20:44
@panovvitalik Btw, just had a look at your screenshot, you might be interested in the following demo: More Samples / Data / 10K race in Paris.

**Comment by monsieurtanuki** [comment] 2018-07-06 12:21
@panovvitalik For testing purposes, could you please try NOT to remove markers, in order to:
* check if the performances are decent with tons of markers, most of them being invisible
* check if the bug does not happen

I don't know when the next release is available, and we don't even if my code edit will fix this bug.
If you're in a hurry, I guess you can use the osmdroid java code (instead of aar?), anyway my fix is a one-line code edit. Additional thought: extend `Marker` and override its `hitTest` method with a `mIcon==null` check.

**Comment by panovvitalik** [comment] 2018-07-06 14:43
@monsieurtanuki 
"check if the performances are decent with tons of markers, most of them being invisible"
Already checked this. Markers are created by data which I get from web: flickr.com - so if I request more data than now  it will be very very slowly :(

"...extend Marker and override its hitTest method with a mIcon==null check."
I think it's very nice idea! Method hitTest is public and I can override it, check for null value, and call super.hitTest()  only if it's not null. Looks very optimistic! I will try this. Thank you for your help!

p.s.
of course better will be released new version of the main product with your bug fix as soon as possible :)

**Comment by monsieurtanuki** [comment] 2018-07-07 08:04
@panovvitalik 
> so if I request more data than now it will be very very slowly :(

I don't say that you should load everything at the start, I just say that perhaps you should not get rid of the already downloaded data as soon as it's not visible anymore.

Btw, could you tell me if the override solution finally works?

**Comment by panovvitalik** [comment] 2018-07-07 08:12
@monsieurtanuki
I understand you - not remove marekers at all. 
Of course it will work, but in future I'm afraid that I can get some other problems with perfomance or memory, etc.
So, I think second solution (with overriding) is more preferable. 

Ok, I let you know if crashes will desappear.
Thank you for your help, again.

**Comment by spyhunter99** [comment] 2018-07-16 20:29
reopen if needed

**Closed by spyhunter99** 2018-07-16 20:29 UTC

**Comment by monsieurtanuki** [comment] 2018-07-19 11:09
@panovvitalik Cool! [The fix is now embedded](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java#L415) in the 6.0.2 distribution.
