### ISSUE TITLE
gazillion of UnknownHostException downloading MapTile

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#989] opened 2018-04-07 18:49 UTC
[x] Question

When no route to Tile source is available I get gazillion of 

```
04-07 14:46:09.960 19527-20147/com. W/OsmDroid: UnknownHostException downloading MapTile: /11/601/770 : java.net.UnknownHostException: Unable to resolve host ".....com": No address associated with hostname
04-07 14:46:09.990 19527-20147/com. W/OsmDroid: UnknownHostException downloading MapTile: /11/601/770 : java.net.UnknownHostException: Unable to resolve host ".....com": No address associated with hostname
04-07 14:46:10.020 19527-20147/com. W/OsmDroid: UnknownHostException downloading MapTile: /11/601/770 : java.net.UnknownHostException: Unable to resolve host ".....com": No address associated with hostname
05-07 14:46:10.060 19527-20147/com. W/OsmDroid: UnknownHostException downloading MapTile: /11/601/770 : java.net.UnknownHostException: Unable to resolve host ".....com": No address associated with hostname
```
flooding the log.  Do I have to handle this somehow i.e try to ping the host separately and disconnect tile updates?

## Description and/or steps/code to reproduce the problem

Disconnect from internet and stay on a local network.

6.0.2-SNAPSHOT

**Comment by spyhunter99** [comment] 2018-04-07 19:56
related https://github.com/osmdroid/osmdroid/issues/131
it would be nice if we had a better solution for this. Perhaps an expiring cache setup that caches the server hostnames that are down and skips downloading from it. My fear with this solution is that if there are no endpoints for a given source available, the downloader will probably loop forever. It's a tricky threading situation

**Comment by monsieurtanuki** [comment] 2018-04-08 11:45
A solution might be to say:
* sometimes the providers fail to give the desired tile bitmap for some reason (we don't even have to know precisely why)
* therefore in the provider loop we could say "if we tried all the providers and couldn't get a bitmap, there's no reason why it should work in the next 5 minutes (configuration parameter)", and populate a tile/timestamp failed attempts `Map`
* we could say there are objective reasons why it should work again, like the network or the wifi being back, and in those cases clear the failed attempts map in order to be able to try again

**Comment by pasniak** [comment] 2018-04-10 08:45
Why a ```map```?  Maybe I single "last tried" timestamp per provider would suffice? With API ability to reset it?

From short web round-out I understand the risk is to hide or delay the failure and the standard strategy is is "exponential backoff" (this guy's [approach](https://www.bennadel.com/blog/3415-creating-a-poor-man-s-exponential-backoff-and-retry-algorithm-in-legacy-code-using-coldfusion.htm) is nice as it would not involve any complex math).

**Comment by secaw** [comment] 2018-04-18 13:40
An important topic IMO. As a first step, tile downloading should just stop as failed when a 404 or other error is returned immediately for the current view. Right now retrying to download each failed tile is stuck in an infinite loop, actually slowing down the UI and firing on the poor server endlessly. I consider this an osmdroid bug!
Sometimes map source adresses change, so this is probably not even a rare one.

**Comment by monsieurtanuki** [comment] 2018-04-18 15:30
I just had a deeper look into the code.
This is what I did:
* I edited `TileSourceFactory.MAPNIK` and changed the http part with unlikely domain names
* I tested with and without internet connection

Let's focus on `MapTileModuleProviderBase.run`, `MapTileDownloader.loadTile` and `MapTileProviderArray.getMapTile`, and let's work on an unknown geo area.

This is what happens _without_ internet connection:
* `loadTile` isn't even called because the download provider is skipped (as it needs internet)
* `getMapTile` tries with the other providers that don't need internet, then eventually stops for this tile with a `MapTileApproximater` tile
* as it is the "downgraded" mode (without internet), finding a tile, even approximated, is good enough
* everything's fine

This is what happens _with_ internet connection:
* `loadTile` tries to download the tile but throws an `UnknownHostException` as expected, which is transformed into a `CantContinueException`
* `run` catches `CantContinueException` by clearing the working and pending tile queues
* the queues are empty, but the display still needs tiles, asks again for tiles, calls `loadTile` again and again on the first tiles of the display (by the time the first tiles trigger the exception the queues are cleared and the other to-be-downloaded tiles are cleared from the queues as well)

My solution is that the queues shouldn't be cleared in those cases, and like in the "downgraded" mode, we should be able to stop trying to fetch a tile (temporarily) at the `MapTileProviderArray` level.
Something like:
* we tried all the providers
* that was not good enough to get a good tile (`ExpirableBitmapDrawable.UP_TO_DATE`)
* then we flag the tile with an exponential backoff value of (now, +10seconds)
* which means we won't consider finding it in the providers before now+10 seconds
* at now+11 seconds we try again to find it in the providers, if we can't we'll try 20 seconds later, and so on

**Comment by monsieurtanuki** [comment] 2018-04-18 19:12
The focus will be on `MapTileProviderArray.getMapTile`.

What's going on now:
* we try to get the tile from the memory cache
* if it's not null and it's flagged as "up to date", then we return the tile
* if it's not null and we're in the "downgraded" mode (basically, no internet) (and the tile is implicitly flagged as "expired", "approximated" or "not found"), then we return the tile as the best guess
* we try to get the tile from the ordered list of providers (the first who finds stops everything), which asynchronously try to find the tile and if found, put it into the memory cache and trigger a screen refresh
* the screen refresh calls again `getMapTile`, potentially with an updated memory cache

What happens if we have an issue with a http request, internet on, as in this issue?
* we're not in the "downgraded" mode (because the interner is on)
* we try to get the tile from the memory cache
* it's either not in the memory cache or not flagged as "up to date"
* we try to get the tile from the ordered list of providers
* among them is `MapTileApproximater`, which very very often manages to compute an "approximated" tile, puts in into the memory cache and triggers a screen refresh
* the screen refresh calls again `getMapTile`, with an updated memory cache that contains an "approximated" version of the tile
* "approximated" is good enough for display, but still we try to find a better version in the ordered list of providers, including in the download provider (that is going to fail)
* it's an endless loop

What could we do in order to prevent the endless loop?
When we put the tile into memory, whatever the status of the tile (up to date, approximated, expired, not found), we use the "(exponential backoff) delay" in order to say: "OK you found it (or couldn't even find it), so it's useless to try again to find it in the providers within the next n seconds" (and later the next m seconds, with m >= n)

About to PR...

**Comment by secaw** [comment] 2018-04-18 20:24
@monsieurtanuki great - sounds tricky, looking forward to testing..

**Comment by monsieurtanuki** [comment] 2018-04-18 20:35
@secaw @pasniak Note that for the moment the delays are:
* 1 second
* 2 seconds
* 15 seconds
* 1 minute
* 2 minutes
* and then always 5 minutes

The delay list is kept in `final` member `long[] MapTileProviderArray.mExponentialBackoffDurationInMillis`.
If applicable, tell me what you think would be the appropriate delay values or if it would make sense to be able to change them programmatically.

**Comment by secaw** [comment] 2018-04-19 09:54
@monsieurtanuki After experiencing a crash #1005 after updating to 6.0.2, I was able to test this. Seems to work nicely! I'm not sure, if we need such short intervals, maybe just 5s / 15s / 1m ...? Great concept anyways.

Two things I observed:
- Tiles with state `shouldWait` are not always rerendered by the approximater, but instead stay blank. This maybe caused by my own variant of `MapTileProviderArray`..?
- At least after some `W/OsmDroid: Problem downloading MapTile: xxx HTTP response: Bad Request`, I regularly get some `W/OkHttpClient: A connection to http://a.xxx/ was leaked. Did you forget to close a response body?` I guess this has happened before though too.

**Comment by monsieurtanuki** [comment] 2018-04-19 11:44
> @secaw Can you try again with `close` instead of `disconnect`?

Except that `HttpURLConnection.close` doesn't exist :(

**Comment by monsieurtanuki** [comment] 2018-04-19 11:54
@secaw How come you get a message mentioning `OkHttpClient`? In the code we use the standard `HttpURLConnection`. A variant of yours, again?

**Comment by secaw** [comment] 2018-04-19 12:00
@monsieurtanuki Exactly - investigating right now, no variant of `MapTileDownloader` :-)
Re my variant of `MapTileProviderArray`, will check also, I take, you can't replicate missing approximation tiles with state `shouldWait`?

**Comment by monsieurtanuki** [comment] 2018-04-19 13:39
@secaw 
* OK for `OkHttp`
* Just PR'ed your one-line fix
* > you can't replicate missing approximation tiles with state `shouldWait`?

I'm not sure I understand what you mean. You can remove `MapTileApproximater` from the providers' list for your tests.

**Comment by monsieurtanuki** [comment] 2018-04-20 08:07
@secaw Anything else? May I merge the PR and close the issue?

**Comment by secaw** [comment] 2018-04-20 08:55
@monsieurtanuki No objection, great work as usual...

**Comment by pasniak** [comment] 2018-04-20 11:52
I think it is working now. A pulled the PR branche (bug/#989) and I think I get less of `W/OsmDroid: UnknownHostException downloading MapTile: /13/2415/3077 : java.net.UnknownHostException: Unable to resolve host ` (when I connect to a local network without internet) AND there is a delay to refresh tiles after I reconnect to the one with internet.  Maybe 2min is too high?  An impatient user (like me...) would be frustrated as to why these tiles are not reappearing.... I'd stop at 20s and every 20s thereafter.

**Comment by monsieurtanuki** [comment] 2018-04-20 16:04
@secaw @pasniak Cool, I just merged the PR.
Regarding the "optimal" delay values I have no strong ideas.
Here are my suggestions:
* you guys agree on a common list of delay values and I PR them
* maybe there's no way users with different use case can agree on a common list; therefore you must specify your own delay values with the appropriate (existing) method
* beyond that you're able to detect when something relevant happened (e.g. wifi from off to on) and in that case you call a method (to be created) that clears the tile delay map

**Comment by monsieurtanuki** [comment] 2018-05-04 13:40
@secaw @pasniak Just PR'ed the new `MapTileProviderArray.clearDelays()` method in #1024.
Feel free to test the PR and close the issue if relevant.

**Comment by monsieurtanuki** [comment] 2018-07-09 13:41
@secaw @pasniak ping
OK to close this issue?

**Comment by monsieurtanuki** [comment] 2018-08-12 09:52
Allegedly fixed. Feel free to reopen.

**Closed by monsieurtanuki** 2018-08-12 09:52 UTC
