### ISSUE TITLE
Marker leaks the latest activity that used it

### ISSUE THREAD

**Issue by Nodjo** [osmdroid/osmdroid#1074] opened 2018-07-02 17:08 UTC
Reproduced on osmdroid 6.0.1

Steps:
1) Have an activity with an instance of MapView
2) Create a new Marker (new Marker(mapView))
Finish the activity
Trigger a garbage collection
Expected: the activity is GC'd
Actual: the activity remains in memory

The cause of this bug is that the Marker constructor will keep a static reference to the latest mapview's context, which is the activity it's been inflated from, in its field mDefaultInfoWindow (which should be called sDefaultInfoWindow as it's a static field).

Workaround: in the activity's onDestroy method, call:
        new Marker(new MapView(getApplicationContext()), getApplicationContext());

**Comment by cbalster** [comment] 2018-07-03 04:56
Actually the reference _should_ be nulled out in onDetach(): https://github.com/osmdroid/osmdroid/blob/ad27030e401f5ddfe27570fdd92bd599a61a0e33/osmdroid-android/src/main/java/org/osmdroid/views/overlay/infowindow/InfoWindow.java#L159

**Comment by Nodjo** [comment] 2018-07-03 08:22
Indeed, but that method is never called

**Comment by spyhunter99** [comment] 2018-07-08 20:13
`Marker#onDetach` is called when the map is destroyed, however there is a static reference to infowindow. To release that, call `Marker#cleanDefaults()`

**Comment by monsieurtanuki** [comment] 2018-07-20 16:12
What about a fictive `Overlay`:
* that draws nothing
* that would be named something like `OptimRepositoryOverlay`
* that would contain all the resources that need to be computed not too often for performance reasons
* that would provide access to those resources through static getters
* that would be added to `DefaultOverlayManager`
* whose `onDetach` method would clean references to `mMapView`
* that would automatically be detached as the other `Overlay`s

**Comment by monsieurtanuki** [comment] 2018-07-23 08:45
Related to #397

**Comment by monsieurtanuki** [comment] 2018-07-23 15:56
Just started devs about it. The idea is to use a dedicated class `MapViewRepository` where the following items are computed for each new `MapView`:
* the default `InfoWindow` for `Marker`s
* the default  `InfoWindow` for `Polyline`s
* the default  `InfoWindow` for `Polygon`s
* the default icon for `Marker`s

The point is to get rid of:
* `static` members - which are not a good idea in Android in general
* lousy code in `Marker`'s constructor - where we check if the `MapView` of the static member (the default) is the same as the current `MapView`

**Comment by monsieurtanuki** [comment] 2018-07-25 17:07
Just PR'ed in #1112

**Comment by monsieurtanuki** [comment] 2018-08-03 12:10
Just merged #1112.
AFAI the issue is now fixed.
@Nodjo Please feel free to reopen in necessary.

**Closed by monsieurtanuki** 2018-08-03 12:10 UTC
