### ISSUE TITLE
Random crash during using osmdroid

### ISSUE THREAD

**Issue by taiffu** [osmdroid/osmdroid#1260] opened 2019-01-27 22:00 UTC
I have used osmdroid of several years and users are reported me to weird random crashes. I have not find any googd reason why this happens until now I started used firebase. I'm unable to reproduce this by self error but it seems happens in varied devices randomly every week. I have now updated to version 6.0.3

Any Idea how to fix this?

Here is log form firebase:
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 63, Size: 62
       at java.util.concurrent.CopyOnWriteArrayList.listIterator(CopyOnWriteArrayList.java:1040)
       at org.osmdroid.views.overlay.DefaultOverlayManager$1.iterator(DefaultOverlayManager.java:92)
       at org.osmdroid.views.overlay.DefaultOverlayManager.onShowPress(DefaultOverlayManager.java:323)
       at org.osmdroid.views.MapView$MapViewGestureDetectorListener.onShowPress(MapView.java:1521)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:289)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:6729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by cbalster** [comment] 2019-01-28 06:04
https://github.com/osmdroid/osmdroid/blob/50f1d3901c8582898d5da3785201f3f1a15724de/osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java#L92

Might a threading issue due to mOverlayList beeing changed between calls to .size() and listIterator().

**Comment by monsieurtanuki** [comment] 2019-01-28 11:39
@cbalster You're right, but it would look like a very bad luck error considering that the code of `DefaultOverlayManager` didn't change that much in the last 3 years, and that the issue seems to be a fresh one.

@taiffu Do you by any chance sometimes add `Overlay`s asynchronously, which could happen when the user touches the screen (maybe a new feature you introduced in your app)?

The problem is that we assume we are thread-safe because `mOverlayList` is a [`CopyOnWriteArrayList`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html). Unfortunately, only the _iteration itself_ is safe, and this issue is apparently caused when we _create_ the `ListIterator` object, not when we use it.
The solution is probably:
````java
final ListIterator<Overlay> i;
synchronized (mOverlayList) {
	i = mOverlayList.listIterator(mOverlayList.size());
}
````

Trying to reproduce the issue in a unit test class...

**Comment by monsieurtanuki** [comment] 2019-01-28 14:11
So far, I haven't managed to reproduce the issue in a unit test class with 2 `Thread`s: one adding items, and the other looping on the reverse list.

**Comment by spyhunter99** [comment] 2019-01-29 00:17
it's pretty clear that we are missing a `synchronized` keyword somewhere. You must have added/removed a layer from the collection during a draw cycle. should be an easy fix

**Comment by cbalster** [comment] 2019-01-29 07:31
Question: Why are the overlays iterated over in reverse in the first place?

**Comment by monsieurtanuki** [comment] 2019-01-29 07:58
@cbalster The overlays are used in both ways:
* they are displayed forwards (the last overlay being on top)
* they can be tested backwards (for onTouch events, as we want to test the latest displayed overlays first)

**Comment by spyhunter99** [comment] 2019-01-29 23:54
it's pretty clear that we are missing a `synchronized` keyword somewhere. You must have added/removed a layer from the collection during a draw cycle. should be an easy fix

**Comment by monsieurtanuki** [comment] 2019-01-30 07:52
Quickly said: I don't even think that `synchronized` is the answer.
Anyway, my initial thought is not the answer, as I still have the `Exception`:
````java
final ListIterator<Overlay> i;
synchronized (mOverlayList) {
	i = mOverlayList.listIterator(mOverlayList.size());
}
````
The problem is that we should add `synchronized` to the other pieces of code that access the list - more specifically when we remove an item. That would be ugly, not good performance-wise, and not even bullet proof, as we cannot guarantee that the developers won't remove items using `DefaultOverlayManager`'s `public List<Overlay> overlays()` rather than using `DefaultOverlayManager.remove`.

In my unit test I embedded the item removal in a `synchronized` block (same for the reverse order block), and then the issue is not there anymore. But as explained before that can't be the solution.

**Comment by monsieurtanuki** [comment] 2019-01-30 08:37
I've just finished my tests:
* I managed to reproduce the crash using the current implementation
* my fix works
* synchronizing both item removal and reverse order iterator creation works too, but is slightly slower (about 20% slower on a 5 test basis) and is not bullet proof (as we cannot expect developers to have `synchronized` item removal)

For the record, my fix is:
````java
public ListIterator<T> reverseIterator() {
	while(true) {
		try {
			return mList.listIterator(mList.size())
		} catch(IndexOutOfBoundsException e) {
			//
		}
	}
}
````

About to PR...

**Comment by monsieurtanuki** [comment] 2019-01-30 09:35
Fixed in #1261

**Comment by taiffu** [comment] 2019-01-30 12:31
Woooh! I will update this to in my app. Thanks!

**Comment by monsieurtanuki** [comment] 2019-01-30 12:51
@taiffu If you finally managed to reproduce the bug with your current version (when `Overlay`s are being asynchronously removed), please test the new version before making it available to your users as there are other new features (potentially new bugs) between 6.0.3 and 6.1.0.

**Comment by spyhunter99** [comment] 2019-02-03 19:49
updating the snapshots now...

**Comment by monsieurtanuki** [comment] 2019-02-09 07:41
@taiffu Any luck with the latest commit?

**Comment by samitai** [comment] 2019-02-10 18:14
> @taiffu Any luck with the latest commit?

Unable to reproduce this case by self, so far I think this fix is good. But I can verify after 6.1.0 release is officialy out and I will take it in my production line with latest OSMBonus pack.

**Closed** 2019-03-30 00:44 UTC
Labels: bug
