### ISSUE TITLE
sample is broken

### ISSUE THREAD

**Issue by emdete** [osmdroid/osmdroid#126] opened 2015-06-17 09:28 UTC
the compile of the sample does not work because build.gradle references non-existing versions.

**Comment by neilboyd** [comment] 2015-06-17 09:56
Please be more specific.  What is referenced that is non-existing?

**Comment by emdete** [comment] 2015-06-17 16:04
you should notice when you try to build with gradle... i remove the "-SNAPSHOT" and the third party lib to make it work.

**Comment by kurtzmarc** [comment] 2015-06-17 16:43
Perhaps related to https://github.com/osmdroid/osmdroid/pull/122

**Comment by neilboyd** [comment] 2015-06-17 19:49
I have merged #122 and everything works, so please check if you're still having a problem.

**Comment by fpoyer** [comment] 2015-06-18 15:15
I suppose @emdete is talking of the build.gradle in OpenStreetMapViewer directory having references to -SNAPSHOT version of osmdroid-android and osmdroid-third-party. This is not a bug, this only means that your first supposed to build these 2 libraries from the sources and install them in your local Maven repository before building the OpenStreetMapViewer sample project.
If you don't build these first, you'll have unresolved dependencies!

Note: If you remove the -SNAPSHOT from the build.gradle, gradle will fetch the last published version from MavenCentral, so it will build, but this is not what this sub project is for I guess. It is for testing that the osmdroid-android and osmdroid-third-party library are working as expected from their current sources (hence why it is part of the project and not another project altogether).

**Comment by neilboyd** [comment] 2015-06-18 15:19
The snapshot is also published to Maven Central, but of course that could be an older version.

And I understand that it should work without using Maven locally.

**Comment by emdete** [comment] 2015-06-19 08:59
i onsider sample a teaching code project that should build out of itself. it is not a test that prooves correctness of the current HEAD. so i would expect that you don't have to compile something else beforehand. especially because there is no doc explaining so. ;)

**Comment by neilboyd** [comment] 2015-06-19 09:16
I see that I didn't push the 4.4 snapshot.  I'll try and do that in the next few days.

https://oss.sonatype.org/content/groups/public/org/osmdroid/osmdroid-android/

**Comment by fpoyer** [comment] 2015-06-20 12:25
@neilboyd : that maven repo you mention, it is not used by maven nor by gradle by default, is it?
Maybe the fix is just to add that repo to the build.gradle and pom.xml so that the -SNAPSHOT artifacts are indeed fetched...

If you don't need that repo configuration for the OpenStreetMapViewer module, I expect that you actually have it defined globally in your settings.xml, don't you? I'm saying this because I have the same behaviour as @emdete if I clean my local repo of all -SNAPSHOT and try to build the module without building and installing the other modules first.

**Comment by neilboyd** [comment] 2015-06-22 05:02
I Googled a little and apparently snapshots aren't synchronized to Maven Central.  I think they used to be.
http://central.sonatype.org/pages/apache-maven.html#performing-a-snapshot-deployment

Here's how to get them:
http://stackoverflow.com/questions/7713996/is-there-a-way-to-make-maven-download-snapshot-versions-automatically

**Comment by fpoyer** [comment] 2015-06-22 07:21
That's what I'm talking about (maybe indeed Maven Central policy about snapshots changed, I couldn't tell, I haven't been using maven long enough).
But rather than asking users to add something to their settings.xml as the answer you linked suggest, I think we could add this bit of configuration to the pom.xml (and build.gradle) of the OpenStreetMapViewer module, so that snapshots would only be used for it, right?

I'll have a look at it later today and do a PR if I can get it to work.

**Comment by neilboyd** [comment] 2015-06-22 08:30
Yes, I suppose it should be possible to put that configuration into build.gradle.
Maybe it's pointless putting it into pom.xml because if you build with Maven then you'll have the dependencies in your local repo.

**Comment by spyhunter99** [comment] 2015-10-03 14:15
@emdete is this issue resolved now? i just pushed some changes that should resolve it. no one was maintaining the gradle build files. On top of that, every time google updates the sdk, they tend to delete old versions of support libraries, thus there being some issues on a freshly updated machine with a clean maven/gradle local repo

**Comment by spyhunter99** [comment] 2015-10-08 00:25
to be clear, you need the Android SDK installed. then download the maven-android-sdk-deployer and run mvn install -fn. Then build osmdroid using mvn clean install.
feel free to reopen if this is still a problem.

**Closed by spyhunter99** 2015-10-08 00:25 UTC
Labels: question

**Comment by neilboyd** [comment] 2015-10-08 07:59
The [Wiki](https://github.com/osmdroid/osmdroid/wiki/HowToMaven) could use a ittle love :)
