### ISSUE TITLE
 Disappears polygon in Mapview

### ISSUE THREAD

**Issue by PalilloKun** [osmdroid/osmdroid#609] opened 2017-05-26 15:37 UTC
Hi

I put some MapView  in a recyclerView  and curiously when scrolling up and down the recyclerView the map disappeared.  I tried to change some dependencies and the one that worked for me was the version
 'org.osmdroid:osmdroid-android:5.2@aar' in build.gradle. (
I found that another person also has the same error, in the thread "Map tile disappearing after scrolling recyclerview # 568").

Decides to draw a polygon on the map within the RecyclerView, the first time the data is displayed, but when scrolling up and down the RecyclerView, the polygon disappears and the map does not.

How to fix?

Thanks

**Comment by spyhunter99** [comment] 2017-06-16 22:59
there are currently some lifecycle issues that have become more an more apparent due to the use of recycler view.  Not entirely sure what the issue is, but i'm willing to bet the map is getting destroyed then recreated.

**Comment by spyhunter99** [comment] 2017-07-29 14:28
closing to due any other feedback, reopen if needed

**Closed by spyhunter99** 2017-07-29 14:28 UTC
Labels: bug, duplicate

**Comment by spyhunter99** [comment] 2017-08-27 14:46
#588 #568 related tickets
