### ISSUE TITLE
CompassOverlay memory leaks

### ISSUE THREAD

**Issue by chrisail** [osmdroid/osmdroid#283] opened 2016-03-22 14:52 UTC
Hello,
When using compass overlay in my code or when using it in “MapActivity” of the “OSMBonusPack demo v5.6.1” like this:
		CompassOverlay compassOverlay = new CompassOverlay(this, map);
		compassOverlay.enableCompass();
		map.getOverlays().add(compassOverlay);
Compass behavior is fine, but I can see memory leaks (via Android Studio Monitor or my own logs). 
When deactivate compass, memory consumption is stable.
It occurs both on android 23 on Nexus6p and android 22 on Samsung A5.

This memory consumption occurs when compass is drawn after it has been invalidate. Look at attached log, keywords: "lost free heapsize: ***"
I don’t see anything, in draw method, that is wrong, but as I'm new to Android development, it’s difficult for me to challenge it …
So, for now, I try to generate less orientation change events in order to delay memory consumption.
I modify “InternalCompassOrientationProvider” in this ways, but I know it isn’t the good solution:
- When registering to listener, add latency with “maxReportLatencyUs” parameter.
- On “onSensorChanged” event, call “onOrientationChanged” only if it change more than 15°.

Does I do something wrong, do you have an explanation?
Chris.

![defaultoverlaymanager](https://cloud.githubusercontent.com/assets/18008107/13955659/cbf6bdc6-f045-11e5-8043-c350913e3725.png)
[CompassMemoryLeaks.txt](https://github.com/osmdroid/osmdroid/files/184320/CompassMemoryLeaks.txt)

**Comment by spyhunter99** [comment] 2016-03-24 23:01
thanks for the bug report.

i'm not sure what's going on the picture. Is the left your code and the right from the osmdroid repo? If you think you have a solution, open a pull request and we'll get it merged.

**Comment by chrisail** [comment] 2016-03-25 18:48
Sorry for the misunderstanding. This is the code I add to "DefaultOverlayManager" class in order to produce attached logs. By this way, everybody can reproduce the same logs than me et see if memory leaks exist in other context. It can also be shown by Android Studio Monitor, but it's less precise.

As I say, I don't see anything wrong in "onDraw" CompassOverlay's method, that seems to be guilty, I don't have any solution.

For now, I just use this "sticking-plaster" for limiting "onOrientationChanged" calls that generates "invalidate, that generates "ondraw", that generates memory leaks :
In "InternalCompassOrientationProvider", 

- I first replace, in "startOrientationProvider" method, `result = mSensorManager.registerListener(this, sensor, SensorManager.SENSOR_DELAY_NORMALSENSOR_DELAY_UI);` by `result = mSensorManager.registerListener(this, sensor, SensorManager.SENSOR_DELAY_NORMAL);`
Using “maxReportLatencyUs” parameter wasn't evidential.
- in "onSensorChanged()" method, I replace the whole code by :`
if (mOrientationConsumer != null) {
        int amplitude = 15;
        if (event.sensor.getType() == Sensor.TYPE_ORIENTATION && event.values != null) {
            int newAzimuth = Math.round(event.values[0]);
            int currentAzimuth = Math.round(mAzimuth);
            if (newAzimuth > currentAzimuth + amplitude || newAzimuth < currentAzimuth - amplitude) {
                    mAzimuth = newAzimuth;
                    //Log.d(IMapView.LOGTAG, "InternalCompassOrientationProvider onOrientationChanged, mAzimuth " + mAzimuth);
                    mOrientationConsumer.onOrientationChanged(mAzimuth, this);
                }
            }
        }
`
For my needs, "amplitude=15°" is sufficient. But it can be change to fit other needs. It can also be pass to the constructor.

**Comment by spyhunter99** [comment] 2016-07-09 19:29
well I can confirm this issue, that's for sure. no clue what's causing it. MAT says it's a large number of LongSpareArray[] objects allocated from android.content.res.Resources

**Comment by spyhunter99** [comment] 2016-07-09 19:41
after some more playing around, it looks like the leak was bitmap related. on an api23 hardware device, memory stabilizes around 40MB with the sample starter map now.

**Comment by spyhunter99** [comment] 2016-08-13 14:06
operation timeout, reopen if this is still an issue

**Closed by spyhunter99** 2016-08-13 14:06 UTC
Labels: bug, waiting for feedback

**Comment by chrisail** [comment] 2016-08-23 15:02
Sorry for the delay.

On the same application, on the same device, on the same OSMDroid version (5.01), I've modified the four lines of code on "CompassOverlay.java". 
The result is that the memory consumption increase is still present. 
But when GC occurs, memory is freed, so in fact there's no memory leaks.

Side effect, by experience, is that GC occurs more often and display update can be more long at this moment. The user experience is less good.

I think that it's not an important thing to report all compass changes, my users accept to be notified only each 5 degrees. So I keep my changes on "onSensorChanged" method in InternalCompassOrientationProvider" class.

Thank you.
Chris
