### ISSUE TITLE
polygon drawing optimizations at low numerical zoom levels

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1409] opened 2019-09-29 20:06 UTC
## Issue Type

[ ] Performance

## description

see pr https://github.com/osmdroid/osmdroid/pull/937 and #906 for reference.

When there is a sufficient quantity of small polygons on screen and the user zooms out, draw speed can drop to a crawl. https://github.com/osmdroid/osmdroid/pull/937 mitigates this somewhat by enabling and using the feature requested by @MKergall which uses an overlay bounds as a faster mechanism to skip draw cycles on overlays that are not in view. This makes rendering quick if nothing is in view.

i think using the point reducer at lower numerical zoom levels may reduce complex polygons from potentially 1000s of points down to 4 or less, which should help draw speed significantly.

the reduced point set can be cached for panning operations to reducing the recalculation necessary and the cache invalidated on zoom events.

## to reproduce...
 
see pr https://github.com/osmdroid/osmdroid/pull/937 for esri shape file download link, then import the shape file, specifically the "shapes" within the shape file. after its imported, the performance issue is obvious

**Comment by monsieurtanuki** [comment] 2019-12-02 09:02
I managed to reproduce the poor performances using https://catalog.data.gov/dataset/military-installations-ranges-and-training-areas
A solution could also be to use a `PointReducer` for pixels too, not only for `GeoPoint`s.
In order to avoid confusion and painful code merge, I'll work on that issue after #1440 is finished.

**Comment by monsieurtanuki** [comment] 2019-12-19 07:16
... and now, #1440 is merged. I can start!

**Comment by monsieurtanuki** [comment] 2019-12-19 13:25
For what it's worth, I've just run some tests on my smartphone. We're talking about 2035 ESRI Polygons, to be displayed in the world map.

Test 1 was the target test, without editing anything.
The very first draw took 3890ms, and the next draw 830ms.
The difference comes from the fact that the first draw initializes data (for instance the projections of GeoPoint into a virtual screen).

Test 2: I removed the actual "canvas.drawPath" call, in order to understand if we are slow computing things or Android is slow drawing Paths.
The very first draw took 3980ms, and the next draw 730ms.
Very similar to test 1, because the population of the Path is already optimized (we remove consecutive duplicates points).

Test 3: I removed the "display this Polygon" calls.
The very first draw took 20ms, and the next draw 30ms.
Same duration. We don't compute data for each draw, and don't even initialize any.

Test 4, 5 and 6 are the same as 1, 2 and 3, but pretending that we use `Polyline`s instead of `Polygon`s.

Test 4.
The very first draw took 4740ms, the next draw 1270ms.
Seems to be slower than with `Polygon`s. A reason may be that `Polyline`s are not optimized for consecutive duplicate points: we add and add single point segments. `Polyline`s get drawn faster than `Polygon`s in general because `canvas.drawLines` is faster than `canvas.drawPath`, but in this case there's nothing to draw!

Test 5.
The very first draw took 4390ms, the next draw 980ms.
Slower than test 2, because the consecutive duplicate points case is not optimized: we spend time precomputing and adding useless segments - and in this test we don't display them.

Test 6.
The very first draw took 70ms, the next draw 20ms.
Similar to test 3.

Let's say that drawing involves 3 steps: the init phase (around 3s in those examples), the draw precomputation phase (around 1s) and the actual draw.
What we definitely need to optimize are the precomputation and the actual draw phases.

Suggestions:
* optimize `Polyline`s when dealing with consecutive duplicate points
* optimize the init phase (see how)
* short-circuit the precomputation phase when relevant. For instance, if in the init phase we computed the bounding box, we are able to say very quickly if the polygon is less than n square-pixel big, and then dismiss it as irrelevant for that projection. Perhaps take also into account the density. I'm a big fan of that option!
* see if it's relevant to use `Polygon`s instead of `Polyline`s for ESRI Polygons (@spyhunter99 what do you think?)
* pre-reduce the number of `GeoPoint`s for low zoom levels

**Comment by monsieurtanuki** [comment] 2019-12-19 18:15
The first tests are very encouraging ("if the boundingbox is too small, don't even try to display it").
I'll PR soon. It's a quick win. Is it going to be fast enough for you guys, I don't know, but even on my old smartphone the performances are decent.

**Comment by monsieurtanuki** [comment] 2020-01-09 11:43
Solved by #1459.

**Closed by monsieurtanuki** 2020-01-09 11:43 UTC
Labels: enhancement, performance
