### ISSUE TITLE
Problem with zoomToBoundingBox()

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#236] opened 2016-01-06 14:18 UTC
I have problem to use `zoomToBoundingBox()`. According to what I've read somewhere here, I've created my own MapView class to call `zoomToBoundingBox()` in `onLayout()`. Here is my code:

```
public class MyMapView extends MapView {

    public void setBoundingBox(BoundingBoxE6 boundingBox) {
        this.boundingBox = boundingBox;
    }

    private BoundingBoxE6 boundingBox = null;

    ...

    @Override
    protected void onLayout(boolean arg0, int arg1, int arg2, int arg3, int arg4) {
        super.onLayout(arg0, arg1, arg2, arg3, arg4);

        // Now that we have laid out the map view,
        // zoom to any bounding box
        if (this.boundingBox != null) {
            this.zoomToBoundingBox(this.boundingBox);
        }
    }
}
```

So, In my fragment I initialize the boundingBox:

```
@Override
public void onResume() {
    super.onResume();

    final BoundingBoxE6 boundingBox = new BoundingBoxE6( ... );
    // this gives ``N:44899816; E:5020385; S:44899001; W:5019482``

    mMapView.setBoundingBox(boundingBox);

    mMapView.invalidate();
}
```

So, the calculated bounding box should obviously cause to get a max zoom level but it doesn't.

First, problem in calculation; `onLayout()` is called after `onResume()` and I explored the code of `zoomToBoundingBox()` and here are the results on each data calculated:

```
zoomLevel = 0
maxZoomLatitudeSpan = 55.08
requiredLatitudeZoom = 14.0  // I have a big doubt on this result!
maxZoomLongitudeSpan = 472.07
requiredLongitudeZoom = 17.0  // hum well, better but not best expected value
So zoomToBoundingBox() will choose a zoom level of 14.0 why? Anyway,  requiredLongitudeZoom of 17.0 is not the best result. As you can see here (http://imgur.com/ZEnX2Za), the max level of 18.0 is possible.
```

So how should I use `zoomToBoundingBox()` ?

**Comment by spyhunter99** [comment] 2016-01-07 00:45
Couple of notes.
1) extending MapView isn't necessary in this case
2) in OnResume of your activity,   create your bounding box, then call zoomToBoundingBox. 

That should get you going...

if you set the bounding box on a map view that restricts the user from panning the map outside of that bounds.

**Comment by 2ndGAB** [comment] 2016-01-07 07:42
Hi spyhunter99,

I tested the MapView extend solution after searching on Internet because using it in onResume() didn't work. I get the same result in fact.
And I suppose that problem comes from ``requiredLatitudeZoom`` calculation with a result of 14.0 which doesn't correspond to an expected value.

About the restriction, maybe you are talking about ``setBoundingBox()``, because using ``zoomToBoundingBox()`` doesn't prevent to pan the map and I really really hope that it shouldn't!

**Comment by spyhunter99** [comment] 2016-01-07 11:56
Correct, I was referring to setBoundingBox because I thought I saw that in
your sample code.

**Comment by 2ndGAB** [comment] 2016-01-10 09:10
Ok my problem really with zoomToBoundingBox().

**Comment by 2ndGAB** [comment] 2016-02-10 17:37
Hello,
I wakeup this thread because I still cannot get zoomToBoundingBox working when I call it from onResume().

When I call it later (via a dcated button for example) with the exact same values, it works well.

**Comment by spyhunter99** [comment] 2016-02-21 13:09
try calling it after a delayed started. I think there's a few related issues to this
#264 #142 

Also try this
MapView.addOnFirstLayoutListener(new OnFirstLayoutListener() { ...});

**Comment by 2ndGAB** [comment] 2016-03-04 10:08
Hello, I tried to implement MapView.addOnFirstLayoutListener(new OnFirstLayoutListener() { ...}); and it seems to be the right place to call zoomToBoundingBox().
Thanks a lot

**Comment by 2ndGAB** [comment] 2016-03-04 11:30
Hello,
I tried to call `zoomToBoundingBox()` in `MapView.addOnFirstLayoutListener(new OnFirstLayoutListener() { ...});` but that doesn't solve all problems.
The view is well centered (but calling it with animate=true doesn't work at all [#264](https://github.com/osmdroid/osmdroid/issues/264) but the zoom level is not ok. Below is the code:

    mMapView.addOnFirstLayoutListener(new MapView.OnFirstLayoutListener() {

            @Override
            public void onFirstLayout(View v, int left, int top, int right, int bottom) {

                final BoundingBoxE6 boundingBox = new BoundingBoxE6(44899816, 5020385,44899001,5019482);
                mMapView.zoomToBoundingBox(boundingBox, false);
                mMapView.invalidate();
        }
    }

If I put the same code in an `onClickListener()`, it perfectly works:

**Comment by 2ndGAB** [comment] 2016-03-08 11:13
Here is some debug message to explain what I try to do when I get the problem:

	Here I open the fragment map with a given bounding box

	D/MyApp: Fragment_agmap: onCreateView
	I/OsmDroid: Using tile source specified in layout attributes: org.osmdroid.tileprovider.tilesource.XYTileSource@7118d91
	I/OsmDroid: Using tile source: Mapnik
	I/OsmDroid: sdcard state: mounted
	I/OsmDroid: sdcard state: mounted
	I/OsmDroid: sdcard state: mounted
	V/MyApp: PauseHandler: onResume
	D/MyApp: bounding box N:44899816; E:5020385; S:44899001; W:5019482
	I/OsmDroid: rescale tile cache from 0 to 14
	I/OsmDroid: Finished rescale in 2ms
	I/OsmDroid: Tile cache increased from 9 to 20
	D/cr_Ime: [ImeAdapter.java:587] detach

	Here I click a button to zoom out to a bigger box.

	I/MyApp: btFullItinerary clicked 
	D/MyApp: bounding box N:44900127; E:5021498; S:44899001; W:5019482
	I/OsmDroid: rescale tile cache from 14 to 18
	I/OsmDroid: Finished rescale in 104ms
	I/art: Background partial concurrent mark sweep GC freed 23788(2MB) AllocSpace objects, 5(15MB) LOS objects, 20% free, 60MB/76MB, paused 4.119ms total 192.565ms
	D/cr_Ime: [ImeAdapter.java:587] detach


	Here I click a button to zoom in to the original box

	I/MyApp: btFullItinerary clicked 
	D/MyApp: bounding box N:44899816; E:5020385; S:44899001; W:5019482

**Comment by pragmaware** [comment] 2016-10-28 22:30
I confirm that the initial zoomToBoundingBox() works only for certain bounding boxes, even if called from onFirstLayout(). The problem seems to be somewhere inside the calculation of maxZoomLatitudeSpan, maxZoomLongitudeSpan: their computed values differ depending on the initial zoom level and bounding box (with all the other parameters being the same, including the size of the view).

I suspect that this has something to do with the initial boundingBox() which appears to be very large, possibly introducing errors in the Projection() calculation? But this is just a guess.

**Comment by spyhunter99** [comment] 2016-10-28 22:37
Great info! It may be enough for a unit test

**Comment by pragmaware** [comment] 2016-10-28 23:25
Investigating more. I believe that the calculation of maxZoom*Span should not depend on the current bounding box (in map coordinates) but only on the view size and the maximum zoom level.

Calculations involving the current bounding box carry an error depending on the currently set zoom size and center coordinates. If I'm not wrong, if the current level of detail is set to 1 then the current map size is tileSize << 1 (512 in my case) and the average horizontal error in integer pixel coordinate mapping is something in the order of half a degree (in the middle of the map). The error grows pretty fast as the coordinates approach the upper/lower edge of the map.

A "hackish" workaround for this issue is to first set the map zoom to a "reasonable" level (I used 14), center it somewhere in the middle and then call zoomToBoundingBox().

**Comment by spyhunter99** [comment] 2016-10-29 00:18
I just made a quick sample that centers the map on the vatican, then varied the startup zoom level and compared the results. Interesting to say the list
start zoom levels 18-4 yielded zoom 13
start zoom 3 yielded 14
start zoom 2 yielded 15
start zoom 1-0 yielded 10

The expected zoom was actually 15. Something is definitely wrong. Rerunning the same test with a button click now...

**Comment by spyhunter99** [comment] 2016-10-29 00:27
Last update for tonight. Same results from a button onclick listener. Also of note, if i click the button a second time, we get the correct result (zoom=15). I don't think startup has anything to do with it. It's a calculation problem

**Comment by pragmaware** [comment] 2016-10-29 00:34
Hmmm...when you click the button a second time you have already set "reasonable" initial conditions with the first click.

More guessing: my feeling that this bug is caused by the error introduced by boundingBox() grows steadily. boundingBox() shouldn't be used here. If there is really no way around it then a hack is to first set a high zoom level and a point close to coordinates (0,0), so the error introduced is low. However, it's a hack. It should be possible to calculate the maximum lat/long span with only the view size, tile size and maximum zoom level as input.

**Comment by spyhunter99** [comment] 2016-10-29 01:07
simplest solution may be to just call zoomToBoundingBox twice.

````
        final BoundingBox boundingBox = new BoundingBox(41.906802,12.445436,41.900073,12.457852 );
        mMapView.zoomToBoundingBox(boundingBox, false);
        mMapView.zoomToBoundingBox(boundingBox, false);
        mMapView.invalidate();
````

this works for me on all zoom levels that i've tested. Always goes to the expected zoom level (15)

**Comment by pragmaware** [comment] 2016-10-29 01:10
An iterative solution :)
...a bit hacky... but it works :D

**Comment by spyhunter99** [comment] 2017-09-04 18:29
a real solution to this has been committed by @monsieurtanuki. Thanks for the bug report. This one has been open way too long

**Closed** 2017-09-04 18:28 UTC
Labels: bug
