### ISSUE TITLE
Mapview repetition bug

### ISSUE THREAD

**Issue by secaw** [osmdroid/osmdroid#845] opened 2018-01-05 11:28 UTC
There's a bug with horizontal and vertical map repetition, where the map jumps back when scrolled to the edges of a virtual 3x3 map repetition grid. (Might be related to #843)
To reproduce: Scroll the map (e.g. with zoom 2) past the current map in any direction to the next repetition map and further. As soon as you hit the edge of that one, in most cases it flips back to the center of that repetition map instead of seamlessly moving on to the next repetition (see image). This is most annoying with horizontal scrolling, but might also be confusing in the vertical direction. Interestingly, if you're in an 'edge map' and are zooming, you get to the center map again. Also the jump back might not happen when scrolling very slowly.

![osmdroid_map-repetition-bug](https://user-images.githubusercontent.com/28442368/34607204-ea34bb00-f212-11e7-9a06-f282519c2cc9.png)

### Version of osmdroid the issue relates to:

6.0.0-SNAPSHOT

**Comment by spyhunter99** [comment] 2018-01-05 23:36
I've definitely seen the scrolling issue. Probably an artifact of the zoom 29 changes

**Comment by monsieurtanuki** [comment] 2018-01-06 12:33
I think it's related to scroll limit enforcement, and I have only see that bug in those cases so far.
When there are scroll limits, the map checks the limits and possibly jumps according to them.
This is done in method `Projection.adjustOffsets(final BoundingBox pBoundingBox)`.
It looks like in the low zoom level cases, there are side effects when adjusting the offsets. I'm going to fix it.
Do you guys saw that bug when there was no scroll limits on? Disclaimer: I'm currently testing from #849, which may have an impact on the matter.

**Comment by secaw** [comment] 2018-01-06 15:50
@monsieurtanuki Not able to test #849 right now, but the scroll bug occured to me already some time back on several occasions, just now was able to finally track it down. Latest use of snapshot a few days ago. Above happens without scroll limits set and as far as I can see on any zoom level (though it's rare, you get to the 3x3 grid border on high zoom levels at all). Basically it means that you are always imprisoned in this 3x3 map grid illustrated above with only the center/middle map working as expected. As soon as you zoom and have been in an edge map, you get to the center/middle map again.

**Comment by spyhunter99** [comment] 2018-01-07 01:30
for reference. https://github.com/osmdroid/osmdroid/pull/849
Testing on branch 849, the scolling issue is still present. https://www.youtube.com/watch?v=GJ4aJCnXjfo&feature=youtu.be

**Comment by monsieurtanuki** [comment] 2018-01-07 09:57
@spyhunter99 I just tested again with #852 (which is related), and I cannot see those map jumps. Could you try again with #852?

**Comment by spyhunter99** [comment] 2018-01-07 13:22
@monsieurtanuki that video was on branch 845 which is the basis if or 852

**Comment by secaw** [comment] 2018-01-08 10:16
@monsieurtanuki I can confirm now that the scroll bug is still present in #852.

**Comment by secaw** [comment] 2018-01-15 22:45
Does anybody have an idea, how to fix this?

**Comment by monsieurtanuki** [comment] 2018-01-16 10:20
I just managed to reproduce the bug more or less.
In my case the jump happens in about the same conditions but only when I switch to another app. Actually I was trying to reproduce it, could not, and then switched to my internet browser through the Android app selector, about to type "still cannot reproduce the bug". And then the jump happened. Something related to fling, to onPause, to an inappropriate setCenter? I noticed in a previous issue that there could be incoherences between MapView scroll values and its Scroller. I even imagined duplicating Android Scroller in order to fine tune its code in the osmdroid context.
Well, now I have at least something to start from.

**Comment by secaw** [comment] 2018-01-16 11:41
@monsieurtanuki Interesting, in my case the bug is always there from the start, nothing special in onPause / onResume, and also without setCenter being called.

**Comment by monsieurtanuki** [comment] 2018-01-21 17:05
I think I nailed it - at least partially.

The problem I found was with fling actions - cf. `MapView.MapViewGestureDetectorListener.onFling`.
For some historical reasons, the fling was limited to +- worldMapSize.
The problem is that if you've already scrolled at least the breadth of a world, you're beyond the limit of the fling action. And in the way it was coded there is a contradiction: OK let's say I start flinging, therefore I set the "in action" flag to `true`. But as I'm beyond the limits, I'll never do actual fling actions, including the ones that set the "in action" flag back to `false`.
In my case that meant that some stalled scroll values were kept in `MapView.mScroller`, to be activated by standard `View.computeScroll` when I switched app (I guess on other smartphones `View.computeScroll` is called more often).
The fix is to set no limits to the `fling` action.

Having a look at @secaw 's initial comment:

> Scroll the map (e.g. with zoom 2) past the current map in any direction to the next repetition map and further.

That makes sense to have problem with low zoom like 2, where you are more likely to scroll beyond world map size.
And

> Also the jump back might not happen when scrolling very slowly.

In this case it's not a fling.

Just PR'ed #889

**Comment by spyhunter99** [comment] 2018-01-21 20:55
merged and snapshot published, please retest/reproduce and comment back if there's still an issue

**Comment by spyhunter99** [comment] 2018-01-21 23:35
causing test failures
````

org.osmdroid.views.OpenStreetMapViewTest > test_toMapPixels_0_0[test1(AVD) - 2.2] [31mFAILED [0m
	junit.framework.AssertionFailedError: the computed center of the map is in the pixel center of the map (Y)(zoom=0.5291292591692422,center=76.32586730594576,-152.71419392472797,0.0) expected:<381.0> but was:<9.0>

	at junit.framework.Assert.fail(Assert.java:47)

:OpenStreetMapViewer:connectedDebugAndroidTest FAILED

````

**Comment by monsieurtanuki** [comment] 2018-01-22 08:12
@spyhunter99 One thing is sure: this crash is not related to the latest push (which only impacted flings).
I also explicitly tried to add the following line to `OpenStreetMapViewTest.test_toMapPixels_0_0`:
````java
checkCenter(0.5291292591692422, new GeoPoint(76.32586730594576,-152.71419392472797));
````
and the test passed.
I guess it's a "bad luck" crash. Unfortunately the messages are not verbose enough to understand what provoked the crash.
Just PR'ed a little change in the unit test, with the hope that it will be stronger.

**Comment by secaw** [comment] 2018-01-22 09:05
@monsieurtanuki Thanks a lot for investigating and fixing this. Works like a charm now!

**Closed** 2018-01-22 12:03 UTC
Labels: bug
