### ISSUE TITLE
Zoom Buttons in 6.1.0

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#825] opened 2017-12-25 15:04 UTC
## Issue Type

[2] Improvement
[1] Bug

## Description and/or steps/code to reproduce the problem
Tried moving from 5.6.5 to 6.0.0. I really like the smooth zooming!

Found the following 3 issues with the zoom buttons.

1. I have custom overlays and Zoom Buttons are hard to spot on top of my overlay. Would be nice to have a way to adjust alpha without writing a new overlay.
2. New Zoom Buttons touch each other, being very small for "thumbs", would be nice to have the buttons about as wide as the old ones. Allowing the programming to set this up (or oven to put buttons in top of each other, instead od left right) would be a nice to have.
3. I catch a onLongPress on my map/overlay. Every touch of the Zoom control buttons subsequently creates such a touch event on the map. I consider this a bug. My guess is, it has to do with the zoom animation making the touch event last longer.

### If it's a bug, version(s) of android this affects:

Tested with Android 4.2 and 6.0

### Version of osmdroid the issue relates to:

6.0.0-SNAPSHOT

**Comment by spyhunter99** [comment] 2017-12-25 15:32
Great feedback! Thanks

**Comment by InI4** [comment] 2017-12-26 10:56
Hmm, now bug or here? I have 2 major problems with Zoom Buttons right now:

1. As stated above, long press events on map coming from short press on zoom. I have no workaround for this, this makes my UI useless.
2. setBuiltInZoomControls() semantics has changes, as these calls do not automatically turn buttons on or off, but I need to send an invalidate() to the map, to be sure, the buttons get updated. It is at least a behaviour change asking to be documented.

**Comment by spyhunter99** [comment] 2017-12-26 13:19
working on #823, the long press should be fixable along with the rest of this issue

**Comment by spyhunter99** [comment] 2017-12-27 18:14
root cause, the current zoombuttons overlay implementation was catching onTouch instead of using the overlay based mechanisms for onSingleTapConfirmed. This was causing confusion of the various gesture detection code that was causing both the zoom control to fire and a long press. This was discovered with #831 (plotting circles). 

The fix, which i just implemented, reworks on the ZoomButtonsOverlay to behave like any other overlay. The down side (and probably the reason why it was implemented with onTouch and directly integrated with mapView) is that the drawing order of overlays can now cause issues where the zoom buttons are either below or above other overlays. The default setup should now draw, the tiles overlay, followed by zoom controls, then everything else. This will change if the built in zoom controls are turned off, then on again, which will paint the zoom buttons last.

The only way to rectify this is to not use the built in zoom controls and implement your own setup in an android layout that is on top of the map.

**Comment by spyhunter99** [comment] 2017-12-27 18:31
regarding issue 2, you can control the explicit location of the buttons by calling the newer api, `setBuiltInZoomControls(true, pixelLeft, pixelTop)`

You can also change the padding by the following psuedo algoritm
1. get the overlay manager from the map
2. loop over all overlays and compare them for instanceof ZoomButtonsOverlay
3. once found, there's a number of methods to call to adjust presentation and whatnot, images, etc

**Comment by spyhunter99** [comment] 2017-12-27 18:45
@InI4 please update and retest on your end to see if these issues have been resolved. I'm still working on the auto hide feature which will require some addition work still

**Comment by InI4** [comment] 2017-12-28 00:45
Did some quick testing and it looks good. Good enough, that I consider, building 6.0.0 in the next release of my little app. Auto fade is more a nth here.

On the technical side, I observe a few new exceptions (which do not stop the app, only occur):
`12-28 00:37:37.619 32385-32385/de.spieleck.app.badgers.debug E/OsmDroid: error dispatchDraw, probably in edit mode
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.ZoomButtonsOverlay.draw(android.graphics.Canvas, org.osmdroid.views.MapView, boolean)' on a null object reference
                                                                             at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1024)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.draw(View.java:17188)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.draw(View.java:17188)
                                                                             at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

12-28 00:37:37.626 32385-32691/de.spieleck.app.badgers.debug E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)

12-28 00:37:38.540 32385-32385/de.spieleck.app.badgers.debug E/OsmDroid: error dispatchDraw, probably in edit mode
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.ZoomButtonsOverlay.draw(android.graphics.Canvas, org.osmdroid.views.MapView, boolean)' on a null object reference
                                                                             at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1024)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.draw(View.java:17188)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.draw(View.java:17188)
                                                                             at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

12-28 00:37:38.829 32385-32385/de.spieleck.app.badgers.debug E/chromium: [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver

12-28 00:37:38.842 32385-32385/de.spieleck.app.badgers.debug E/OsmDroid: error dispatchDraw, probably in edit mode
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.ZoomButtonsOverlay.draw(android.graphics.Canvas, org.osmdroid.views.MapView, boolean)' on a null object reference
                                                                             at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1024)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.draw(View.java:17188)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.View.draw(View.java:16951)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                             at android.view.View.draw(View.java:17188)
                                                                             at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

12-28 00:38:04.365 32385-32385/de.spieleck.app.badgers.debug E/OsmDroid: error dispatchDraw, probably in edit mode
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.ZoomButtonsOverlay.draw(android.graphics.Canvas, org.osmdroid.views.MapView, boolean)' on a null object reference
                                                                             at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1024)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

12-28 00:38:29.898 32385-32385/de.spieleck.app.badgers.debug E/OsmDroid: error dispatchDraw, probably in edit mode
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.ZoomButtonsOverlay.draw(android.graphics.Canvas, org.osmdroid.views.MapView, boolean)' on a null object reference
                                                                             at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1024)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

**Comment by spyhunter99** [comment] 2017-12-28 02:34
thanks for testing this. i see the issue, fixing now

**Comment by InI4** [comment] 2017-12-28 15:07
Hmm, pulled the snapshot just now and this one seems to have problems.

1. Using `mMap.setBuiltInZoomControls(zoomControl, OverlayLayoutParams.RIGHT | OverlayLayoutParams.BOTTOM);` but button comes out centered low, not right.

2. Buttons are unclickable now. This might be an interaction with my own Overlay?? But at least it still worked in the last snapshot.

**Comment by monsieurtanuki** [comment] 2018-04-30 13:30
Btw the standard [ZoomButtonsController](https://developer.android.com/reference/android/widget/ZoomButtonsController) is deprecated since API level 26:
> This functionality and UI is better handled with custom views and layouts rather than a dedicated zoom-control widget

**Comment by monsieurtanuki** [comment] 2018-10-31 13:20
What we need for our custom zoom buttons implementation as a minimum viable product:
* default icons for + and -, as active and inactive
* default position on map
* handle short click and long click the same way
* handle the "display always" case
* handle the "display when I click on the map, for n milliseconds, then auto-hide" case (cf. #823)

Pitfalls:
* handling LTR and RTL (cf. #1053)
* handling the click when the map is rotated (cf. #837)
* no benign crash when pausing/resuming the map (cf. #736, #328)

Nice to have:
* overriding the icons
* overriding the position
* overriding the fade in and fade out delays
* alpha animation when fading in and/or fading out
* full zoom scale "à la Google Maps"

@spyhunter99 Both you and I worked on the subject about 1 year ago, but finally nothing relevant was merged, am I right?
I guess it's better to start from scratch.
I think you're rather busy these days; any comment before I start on this custom zoom buttons dev?

**Comment by spyhunter99** [comment] 2018-11-02 18:53
Yup super busy.  Feel free to do whatever

**Comment by monsieurtanuki** [comment] 2018-11-03 19:49
So far so good. I'm very optimistic.
Last year too I was very optimistic about the zoom buttons..., but the good thing is that now we have a set of potential issues to work on.

**Comment by monsieurtanuki** [comment] 2018-11-04 18:17
Good news: I should be able to PR by next Sunday.

**Comment by monsieurtanuki** [comment] 2018-11-07 19:32
@InI4 PR'ed #1605. Feel like testing it?

**Comment by monsieurtanuki** [comment] 2018-11-14 10:15
Fixed by #1190. Feel free to reopen.

**Closed by monsieurtanuki** 2018-11-14 10:15 UTC
Labels: enhancement

**Comment by InI4** [comment] 2018-11-14 23:03
Sry, late, was elsewhere. Will see if I can test tomorrow night or so ...

**Comment by InI4** [comment] 2018-11-15 08:10
Automatic Zoom Controls do not happen any more:

In my app I have zoom controls only appear when map is tapped, this used to work fine with 6.0.2 and with some 6.0.3 snapshots, but does not seem to happen with the current snapshot any more: I simply do not get zoom controls at all now. Is this a regression or a feature?
