### ISSUE TITLE
"Fling" scroll on rotated map eventually scrolls in unrotated direction.

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1366] opened 2019-07-01 11:54 UTC
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

I first observed it in my app, but then realized, it is also there in the **osmdroid demo app**. 

Rotate the map 90°, then **fast** scroll the map by swiping up, the map first follows the fingertip and scrolls up, but then scrolling goes ballistic and the map animation actually moves the map left. 

If you rotate the map 180°, fling movements really "overbounce back", i.e. up becomes "first up, but eventually down".

Summary: After the follow finger, the actual animation moves the map in a direction, as if the map wasn't rotated below the finger.

## Environment

Tested on OnePlus 6 (Android 9), but I hear it from my users on other devices.

### If it's a bug, version(s) of android this affects:

9 in any case

### Version of osmdroid the issue relates to:

6.1.0.

**Comment by InI4** [comment] 2019-08-30 15:31
Hmm, did someone look into this? This is a bit annoying.

**Comment by monsieurtanuki** [comment] 2019-08-31 07:55
I've just tested the issue this morning on my Android Go, but couldn't reproduce it.

**Comment by jlimek** [comment] 2019-09-04 14:39
I've the same bug. Fling after rotation gesture or animateTo with orientation not working properly. Scroll without fling is ok.

**Comment by InI4** [comment] 2019-09-06 21:05
@monsieurtanuki I see it on all devices I held so far. You really need to fling ballistic, as soon as the finger leaves the screen, weird directions happen.

**Comment by InI4** [comment] 2019-10-06 21:28
I made a video of the effect. https://drive.google.com/file/d/1H2eKwU2EDF35Tah3zD9F_OtqQiTfubNZ/view?usp=drivesdk

**Comment by InI4** [comment] 2019-10-07 07:25
@jlimek I can now fix it on one of my devices, just to make it bad on another. There seems to be a dependency on Android version. Can you second this?

**Comment by monsieurtanuki** [comment] 2019-12-19 07:13
Fixed by #1415

**Closed by monsieurtanuki** 2019-12-19 07:13 UTC
