### ISSUE TITLE
6.0.2 issue in controller.animateTo()

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1040] opened 2018-05-23 21:26 UTC
## Issue Type

[X ] Question
[X ] Bug

## Description and/or steps/code to reproduce the problem

I have a self written overlay whichs `draw()` method line 1 is an `if ( shadow || map.isAnimating() ) return;`. 

Now when I send a `controller.animateTo()`, my overlay painted with v6.0.1 after animation target was reached. However with v.6.0.2-SNAPSHOT from right now the `draw()` method does not seem to get triggered after animation has finished. Consequently the overlay is not being drawn at all. Minimally touching and moving the map though triggers a correct `overlay.draw()`.

I see no way to achieve a overlay draw after animation now.

Using `controller.setCenter()` instead of `animateTo()` works fine, so problem seems to come from the animation.

## Environment

Found this behavior change on all 3 tested emulators.

### If it's a bug, version(s) of android this affects:

fully reproducible on 7.1.1, 8.1
very often reproducible on 6.0

### Version of osmdroid the issue relates to:

6.0.2-SNAPSHOT

**Comment by monsieurtanuki** [comment] 2018-05-24 07:03
> mapView.invalidate()` in `MapController.onAnimationEnd() should fix this

@InI4 You're right. The fact is that we don't need it for the actual animation, but it makes sense to run `invalidate` in your case because you check `map.isAnimating()`. And there's no drawback calling `invalidate` at the end.
Feel free to PR.

**Comment by InI4** [comment] 2018-05-24 07:30
@monsieurtanuki this animation check is actually a recommendation for heavy weight overlays I found somewhere. I didn't invent this and it worked smoothly till 6.0.1.

Concerning the PR, I have not setup the 6.0.2 build yet (again had one for 6.0 .. somewhere), and so I'd actually suggest, you simply do it, though I lose github karma then.

**Comment by monsieurtanuki** [comment] 2018-05-24 08:07
@InI4 Oh, I'm fine with this `isAnimating` check. The only place I found it was in the scale drawing, which used to be totally inaccurate during zoom pinch gesture - and therefore the drawing was skipped during animation. It makes sense for heavy weight overlays too.
I'm about to PR.

**Comment by monsieurtanuki** [comment] 2018-05-24 08:14
Just PR'ed in #1043

**Comment by monsieurtanuki** [comment] 2018-05-27 08:17
@InI4 Does #1043 fix the issue? Ready to close it?

**Comment by InI4** [comment] 2018-05-27 15:48
I am fairly sure. Do you know, if it is in the SNAPSHOT thing now?

**Comment by monsieurtanuki** [comment] 2018-05-27 15:54
@InI4 I don't know much about SNAPSHOT in general. Beside that, there was some kind of github misunderstanding that made me actually merge the code only 8 hours ago.
A safe answer would be: probably not.

**Comment by spyhunter99** [comment] 2018-05-27 16:09
i updated the snapshot a few hours ago

**Comment by InI4** [comment] 2018-05-27 20:33
Thx @spyhunter99! The combined zoom and pan operations in 6.0.2 are really looking cool.
Concerning the issue. I did some testing and it seems to work now.

**Comment by InI4** [comment] 2018-05-30 18:13
I do not understand what this has to do with the API issue, a listener, that does not get called and listens on events that do not happen any more.

**Comment by monsieurtanuki** [comment] 2018-05-31 09:44
@InI4 I'm losing the plot: what is the actual issue? I just tested, and the listeners are correctly called when I pan the map, during pinch gesture and double-tap zoom.

If the issue you have is actually about handling
* sometimes too many concomitant events
* of 2 distinct types (`ZoomEvent` and `ScrollEvent`)
* without an explicit event for a combination of new zoom and new position

...a solution might be to use the `MapView getSource()` method in order to retrieve the zoom level (`getZoomLevelDouble()`) and the map geo center (`getProjection().getCurrentCenter()`), and to simply ignore the other parameters (`ZoomLevel.getZoomLevel()`, `ScrollEvent.getX()` and `getY()`).
In that case you don't even care if it's a scroll or a zoom or both, it's just a "something happened on the map" event, and you retrieve from `MapView getSource()` all the details about the current zoom + geo position.
Is that relevant in your case?

**Comment by InI4** [comment] 2018-05-31 17:11
Sorry @monsieurtanuki. I hope I get it explained better this time.

First of all, initial reported problem **in detail** is fixed. That `invalidate() `thing is there and helps. However there is still a change in behaviour of `animateTo()` from 6.0.1 to 6.0.2. Since it is still in `animateTo()` I didn't create a second bug but proceeded here. I can do a new bug if you prefer.

To explain:
1. My App uses `doDraw()` in the overlay to do the actual drawing. This now works more often thanks to the invalidate(). Great! However it sometimes doesn't work entirely and I digged deeper:
2. My App uses a `MapListener` to retrieve certain data which is rendered in that overlay but also used in other places.

**With Osmdroid 6.0.1 everything works**. With 6.0.2-SNAPSHOT even with the new `invalidate()` code it doesn't. It turns out, the trigger for data retrieval (via `MapListener`) isn't firing during `animateTo()`.

I can rewrite my app to do more stuff in onDraw() and retrieve position, you are right! I might very well do this as it is cleaner. This raises the question what for the `MapListener` is at all. Everyone could create a (non drawing in some cases) overlay to get timely updates about map changes.

So something has changed with event generation during animations in 6.0.2. Therefore 6.0.2 might well break more code relying on `MapListener` than only my humble app. **It is a code breaking change.** 

My point was is to decide weather to document the behavioral change carefully. or to see if the old behaviour can be recovered. This is of course also about me rewriting my mechanics sooner or not.

**Comment by InI4** [comment] 2018-06-03 12:57
Note: I have a first version of my app working without MapListener. Turns out this is easy to achieve in my case, however this still might not generalize to other apps relying on Osmdroid.

**Comment by spyhunter99** [comment] 2018-06-09 13:28
@InI4 assuming this is still an issue, we should fix it before release. which is soon

**Comment by InI4** [comment] 2018-06-09 18:42
@spyhunter99 isn't the MapListener kind of deprectated? I have no idea, how the new nice implementation of zoom/scroll animations could supply meaningful onZoom() on onScroll() events?! I do not know the codebase of projects based on Osmdroid. For my project I have worked around the issue by moving code to handle map changes from a MapListener to an Overlay.

I'd vote for documenting this as a potentially breaking change and suggesting the Overlay workaround.

**Comment by spyhunter99** [comment] 2018-06-09 19:29
>  isn't the MapListener kind of deprectated?

no.

**Comment by spyhunter99** [comment] 2018-06-30 15:09
is this still an issue?

**Comment by InI4** [comment] 2018-07-02 16:07
Do you ask me? I worked around the lost `MapListener` events in my app a month ago, as described above. So I cannot test any more. From mere inspecting the code, I do not see code changes, bringing back the MapListener events.

**Comment by monsieurtanuki** [comment] 2018-07-07 09:54
If I sum up:
*  a new feature was merged into osmdroid in 6.0.2 - `MapController.animateTo` with zoom AND geopoint at the same time
* this new feature is not part of the initial `IMapController` and `MapListener` interfaces
* somehow this new feature introduced unwanted side-effects regarding `MapListener` events
* anyway `MapListener` cannot deal with zoom change and geopoint change at the same time
* a workaround is to emulate the `MapListener` with zoom, geopoint and zoom+geopoint events using an `Overlay` with no display

Hence the questions:
* should we create a new `ScrollZoomEvent` class extending `MapEvent`, and upgrade `IMapController` and `MapListener`? As they are `interface`s, it won't be harmless for apps already using the library
* should we deprecate `IMapController`, `MapListener`, `MapEvent`, `ScrollEvent` and `ZoomEvent`, and recommend the use of `Overlay` instead?

**Comment by spyhunter99** [comment] 2018-07-07 12:56
or we can just just update the new animateTo method to call the map events listener api. Since that api is as old as this project, fixing the implementation would be preferable IMO. Less impact on existing projects/apps that use osmdroid.

**Comment by spyhunter99** [comment] 2018-07-07 13:13
I'm not sure what the root cause is. Could it be that in `MapAnimatorListener#onAnimationUpdate` we need to call the map listeners?

**Comment by spyhunter99** [comment] 2018-07-07 13:59
side note: whoever added/updated the Animate To sample did an awesome job! Fantastic idea. I'm using that demo, which does call animateTo and onScroll and onZoom events are both firing. What am I not understanding?

**Comment by InI4** [comment] 2018-07-09 05:03
MapListener events are somewhat painful anyway and there is a lot of code floating around to get rid of most of those events (`DelayedMapListener`s) anyway. If it works out, wouldn't doing events in `onAnimationUpdate()`, probably zoom and scroll close to each other, flood clients even more?

Just to reiterate another possible minor variant. Reactivate the old implementations of `animateTo` and `zoom` (instead of calling the new combined one). Deprecate `IMapController`, `MapListener`, `MapEvent`, `ScrollEvent` and `ZoomEvent`. Recommend `Overlay` to follow map changes and document the new combined `animateTo()` to fire no MapListener events.

**Pro:** Breaks no legacy clients. **Contra:** Reactivates old code which was nicely cleaned away.

**Comment by monsieurtanuki** [comment] 2018-07-09 09:44
@spyhunter99 Glad you like my AnimateTo sample!

Just had a look again at my [`animateTo` code change](https://github.com/osmdroid/osmdroid/pull/991/commits/cffc2f73a92e151cff0e7e8c492b73eeb81b648d).

Regarding `ZoomEvent`s it should be the same behavior: in both cases eventually `MapView.setZoomLevel` is called several times (each time, calling `ZoomEvent`s).

I think what causes the different behaviors is the fact that with the previous version, the `animateTo(GeoPoint)` was transformed into a `animateTo(Point)` after a GeoPoint2Point projection. And this called a succession of `MapView.scrollTo` (each calling `ScrollEvent`s).
With the new version, `animateTo(GeoPoint)` becomes a succession of `MapView.setExpectedCenter`, and that method does _not_ call `ScrollEvent`s.

@InI4 Does it match your personal experience? If so, the fix would be to explicitly call the `ScrollEvent`s during the animation (`MapController.MapAnimatorListener.onAnimationUpdate`) (the `ZoomEvent`s already being implicitly called). Or to add a call to `ScrollEvent`s in `MapView.setExpectedCenter`.

**Comment by monsieurtanuki** [comment] 2018-07-11 08:51
@InI4 Just PR'ed #1090: "MapView.setExpectedCenter() triggers a scroll event if the position is changed"

**Comment by monsieurtanuki** [comment] 2018-07-12 09:09
Fixed by #1090

**Closed by monsieurtanuki** 2018-07-12 09:09 UTC
Labels: bug
