### ISSUE TITLE
Bad memory cache handling for expired tiles

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#630] opened 2017-07-15 10:49 UTC
Linked to #624 

Sometimes there are some empty tiles displayed as grey rectangles though they are obviously in the SQL cache.

Here what's happening.
The context:
* On a given map (geo coordinates + zoom), I have tiles that are expired, and tiles that are not (according to my map browsing history). All tiles are in the SQL Cache, but now some are expired.

The issue:
* I go offline
* If I look at the map, at first sight, everything looks ok (because everything is in the SQL cache - though with some expired tiles)
* Then I zoom in twice, then I zoom out back twice
* Now is the problem: the expired tiles look now as a grey rectangle
* If I tilt my smartphone landscape-portrait-wise I switch back to a correct display, with the expired tiles good again
* Just checked also: if I go far away on my map then go back to the initial spot, everything looks fine again too.

My first analysis: there's a problem around MapTileProviderArray.
It looks like the memory cache works ok the very first time:
* "get me the (x,y,z) tile" - from the SQL cache only because we're offline
* ok I found it
* I display it
* but if the tile is expired according to SQL cache, I mark the tile bitmap as "expired"
* so far so good, everything looks ok

The problem seems to be when I change zoom levels: it kind of partly breaks the memory cache / the memory cache is exceeded, something like that. And what happens next: the tile bitmap being marked as "expired" BEFORE I even could display it, then it is displayed as a grey rectangle.

**Comment by spyhunter99** [comment] 2017-07-15 14:29
excellent detective work. This may be an artifact of the great memory leak bug hunt. The bitmap is probably being marked as recycled too soon

**Comment by monsieurtanuki** [comment] 2017-07-17 10:32
I progress in my analysis. It looks like the issue comes from the zoom in / zoom out approximations, for instance in `MyMapTileProviderBase.ScaleTileLooper.finaliseLoop`

In short:
* during the zoom-in/zoom-out process, osmdroid computes approximations of the next zoom level tiles, for a smooth zoom display from level to level
* those approximations are marked as expired but are potentially stored in the memory cache if there's nothing for this (x,y,z). Or if there's already an expired tile, which is the case if I have expired SQL cache tiles.
* therefore sometimes zoom approximations overwrite SQL cache tiles in the memory cache.

Long version:
* I work offline
* I have a whole region of (SQL-cache) expired tiles, on my highest available zoom level - let's say 16
* I show the region on my map: every tile is displayed, but internally marked as expired
* I zoom in, to level 17: there's an approximation of my tiles, who look twice bigger. So far so good.

The trouble is what osmdroid does with that approximation on level 17, when I zoom out back to level 16.
What is displayed? During the zoom process, osmdroid computes an approximation of level 16 tile bitmaps, which is based on the approximations on level 17 (to be smoothly displayed during pinch gesture). And this bitmap is marked as expired, because it's just an approximation. Fair enough.
But osmdroid stores this approximation bitmap for level 16. Should we? Why not, the only thing we have on level 16 is expired too (though it comes from SQL Cache).

Does that make sense?

**Comment by spyhunter99** [comment] 2017-07-17 11:19
the scaled tile should not be stored anywhere IMO

**Comment by monsieurtanuki** [comment] 2017-07-17 18:35
A solution I'm currently developing is to have 3 decreasing status for tiles in `ExpirableBitmapDrawable` regarding memory cache:
1. up-to-date - this is a tile that we downloaded one day and that is not expired yet (that status already exists: `Drawable` without `state`)
2. expired - this is a tile that we downloaded one day and that is now expired (that status already exists: `Drawable` with `state[1]=EXPIRED=-1`)
3. approximative - this is a tile that we built as an approximative combination of regular tiles, typically for zoom in/out (that status is new: `Drawable` with `state[1]=APPROXIMATIVE=-2`)

Once this new `ExpirableBitmapDrawable.APPROXIMATIVE` status is created, the idea is to change the code that way:
* Each time we want to save a tile in the memory cache
* We check first if there's already a tile in the memory cache with a more relevant status.
* If it is the case, we don't save the tile - doing so we don't overwrite a tile with a less relevant one
* That's already working more or less that way, but unfortunately without a distinction between `EXPIRED` and `APPROXIMATIVE` and that's why zoom approximations sometimes overwrite expired tiles.

My first tests look encouraging.

**Comment by secaw** [comment] 2017-07-24 12:06
Sounds very promising, looking forward to testing!

**Comment by monsieurtanuki** [comment] 2017-07-29 06:51
Closing the issue as code has been merged.

**Comment by shiroyagi** [comment] 2017-07-29 15:25
Sounds great, but unfortunately when testing offline it looks like rendering performance has decreased significantly at certain zoom levels (probably depending on cached tiles) and sliding the map often stalls (cf. 30a4622c).  Online it seems ok.  GPU profiling draws a lot of purple indicating 'XFer' uploading bitmaps to the GPU.

**Comment by spyhunter99** [comment] 2017-07-29 15:43
bugger. should i revert?

**Comment by monsieurtanuki** [comment] 2017-07-29 17:33
@shiroyagi I'm a bit confused.
In your comment you're referencing a commit you did about one week ago about the SQL cache purge (#631). Is that what is causing the poor rendering performance?
In another part of your comment it looks like the problem comes from a more recent commit of my code (#627, merged today). If so, any detailed description would be appreciated, like "this happens when I have data up to zoom 5 and I try to display offline zone 15" or things like that. Thank you!
A hint: I find the default cache level to be very low (9!). Maybe raising it would help things.

**Comment by shiroyagi** [comment] 2017-07-29 18:44
30a4622 is ok, so I think the problem is a subsequent change.  To reproduce I have the phone offline and view a region of map with cached tiles (not at many levels, but with all tiles in the area at these levels).  I then zoom in or out and at some zoom levels (not sure which but presumably levels without cached tiles), rendering when sliding the map is longer smooth.  Turning on the GPU profiler in developer options (Android 5) shows the system is under heavy load.

You mean setCacheMapTileCount()?  Yes this may help, but performance was very good before so ideally it could be resolved in another way.  With 30a4622 there are no tiles missing (grey), but some of the tiles drawn may have expired.  Perhaps if you set the cache back to 9 it would help replicating the problem?

**Comment by monsieurtanuki** [comment] 2017-07-29 19:06
I have never experienced that problem during the development phase even with the memory cache at 9 - I wouldn't have committed with that left unfixed.
Btw are you testing on an emulator or on a physical device?
Nevertheless there is something slightly related that puzzled me and that might explain the slow motion: the system desperately tries to find a good-downloaded-not-expired tile and loops until it finds it. And as it never finds it as we're offline, it's an endless loop. I'm not sure this wasn't the case before I committed my changes. Do you believe it would explain what you're experiencing?
A cleaner way would be to say to the system: "hey, we're offline, nothing's better is coming" and stop that loop. Until the network goes back.
I'll have a look at it tomorrow - though it will be hard if I cannot reproduce your bug.
Now that I'm thinking: we may not even need the Zoom Loops anymore (whichs happens AFTER the smooth zoom animation), as we are now able to approximate the tiles. But that's maybe another story. To be continued...

**Comment by shiroyagi** [comment] 2017-07-29 19:38
Physical device (Moto X).
I'm seeing both increased CPU and GPU load.  The loop might explain the former, but not the latter.  It would certainly be good to avoid it when offline though.
Before MapTileApproximater how were missing tiles approximated?  If I started zooming in where there were no higher level tiles I still saw a very pixelated but usable image.  This was one way though: zooming in would show the scaled tiles, zooming out would go grey.  With your changes zooming out draws scaled tiles too.  My suspicion would be that with a low memory cache canvas.drawBitmap() in approximateTileFromLowerZoom() is being called excessively and this is somehow less efficient than what was happening before.

**Comment by monsieurtanuki** [comment] 2017-07-30 06:08
> I'm seeing both increased CPU and GPU load. The loop might explain the former, but not the latter [...] Before MapTileApproximater how were missing tiles approximated?

Yes that would explain everything, because before `MapTileApproximater` the missing tiles were approximated once, just after the zoom animation.
Now we have (sometimes) an endless loop, in which a new step (`MapTileApproximater`) is computing bitmaps out of other bitmaps. Hence the high GPU use.

This morning (CET) I was able to reproduce the endless loop (but not the slow behaviour).
What I understood so far:
* the endless loop bug existed before my new code, but was rather harmless as nothing GPU intensive was performed anyway
* the endless loop bug seems tricky as the problem is not is the `MapTileProviderArray.getMapTile` method that loops on the provider list, but on the fact that in `MapView` the standard method `dispatchDraw` is called over and over again by the system. For no obvious reason.

In my context, this is how I reproduce the endless loop:
* in `MapTileProviderBasic`, remove the call to `MapTileApproximater`
* test offline
* go on a fully SQL cached zone - there are two calls to the main screen `TilesOverlay.draw` (why two? that's another bug, not mine, that I'm going to fix), and that's it, end of the story, no further call if you don't scroll the map
* scroll to a partially uncovered SQL cached zone - here you are with the endless calls to `TilesOverlay.draw`

I'll have a look again this morning.

**Comment by monsieurtanuki** [comment] 2017-07-30 07:44
I think I found the reason for the endless loop - standard `ViewGroup.dispatchDraw` must be very fast:
* if it's "fast enough", it's not automatically called again
* if it's too slow, I guess Android assumes the display must be refreshed, and this is what causes the endless loop.

How did I reproduce that:
* I have my tiles cached, so this can't be a problem
* I added a `Thread.sleep(100 milliseconds)` in the `MapView.dispatchDraw`
* the result is that I have a correct display but with an endless loop

Action: `MapTileProviderArray.getMapTile` must be optimized. I'm on it ;)
When everything is ok - I mean when tiles are found and up-to-date, this method returns immediately and that's fast enough.
But if the tile is not found or is expired, then there is a loop among all providers, with `synchronized` locks. It's already too slow. And with `MapTileApproximater` it's also too demanding for the GPU. And the process is definitiely not fast enough. And Android refreshes the display. Again and again.

**Comment by monsieurtanuki** [comment] 2017-07-30 09:04
Anyway `MapTileProviderArray.getMapTile` cannot be optimized so that it's always fast enough to fit inside a `MapView.dispatchDraw`. We don't know how many `Overlay`s there can be anyway.
But I found an elegant solution :)
The idea is to create a downgraded mode inside `MapTileProviderArray.getMapTile`.

How it used to work:
1. get me the tile from the memory cache
2. if you found a tile and if it's up to date, then it's the good bitmap, thank you my friend
3. if the tile you found is not up to date (expired or approximated) or if you found no tile, I'm sure you can do better. Please have a look at all the providers (that's the "slow" process that ruins everything)

How it's going to work in about 10 minutes:
1. get me the tile from the memory cache (same)
2. if you found a tile and if it's up to date, then it's the good bitmap, thank you my friend (same)
3. if the tile you found is not up to date (expired or approximated) _and if we are in the downgraded mode_, that tile is good enough for me (of course, the downgraded mode will be triggered when we have no connectivity)
4. if you found no tile, I'm sure you can do better. Please have a look at all the providers. That's still a "slow" process, but once we figured out that there's no tile, we will just set an empty tile image, and this is it

The only side effect is that the display is too optimized! When I go online again, the display is not refreshed because there are no nonsense loops anymore. I'll have a look at that.

**Comment by monsieurtanuki** [comment] 2017-07-30 10:24
@shiroyagi I think it should be ok now. Could you try again using the new version of MapTileModuleProviderBase, MapTileProviderArray, MapTileProviderBasic and MapTileRequestState available at [feature/#640](https://github.com/monsieurtanuki/osmdroid/tree/feature/%23640)?

Then I'll have a look at the offline-online automatic refresh.

**Comment by shiroyagi** [comment] 2017-07-30 10:55
Good work, sounds much better.

I'm not very familiar with git and tried the following:
```
git remote add monsieurtanuki https://github.com/monsieurtanuki/osmdroid.git
git pull monsieurtanuki feature/#640
```
There is a merge conflict in CacheManager.java.  I'm not sure if I'll have time to look at this today.

**Comment by monsieurtanuki** [comment] 2017-07-30 11:12
Just coded the offline-online automatic refresh. Did it on the `Activity` level, where a `BroadcastReceiver` can listen to network on/off events.

@shiroyagi I'm sorry I can't help you with the conflict, I don't understand very much about git.

@spyhunter99 Ready for a nice merge?

**Comment by spyhunter99** [comment] 2017-07-30 12:29
sure thing, what branch?

**Comment by monsieurtanuki** [comment] 2017-08-19 15:44
Btw though it's not obvious, this has been committed in branch [feature/#640](https://github.com/osmdroid/osmdroid/tree/feature/%23640)

**Comment by spyhunter99** [comment] 2017-09-05 01:00
@monsieurtanuki sorry, trying to catch up. Is this issue good to close?

**Comment by monsieurtanuki** [comment] 2017-09-05 16:54
@spyhunter99 Just double-checked the code in the master branch: yes this issue is solved and good to close.

**Closed** 2017-09-05 22:12 UTC
Labels: enhancement

**Comment by shiroyagi** [comment] 2017-09-06 21:53
Excellent, works well, performance is good (sorry I didn't get chance to test it earlier).
