### ISSUE TITLE
MapListener.onZoom does not get triggered when pinching and zooming

### ISSUE THREAD

**Issue by sonwh98** [osmdroid/osmdroid#707] opened 2017-09-07 12:15 UTC
I asked a question at https://stackoverflow.com/questions/46096035/osmdroid-scale-an-infowindow-when-zoom but I think this might be a bug with how MapListener.onZoom  is being called

I expect the onZoom method to be called as I am pinching and zooming the mapView but this does not appear to be the case. The onZoom method only gets triggered after I stop pinch-zoom by lifting up my fingers.  The method should get called as I am pinching and zooming

**Comment by spyhunter99** [comment] 2017-09-07 12:44
What verison? This sounds like the expected behavior for 5.6.5 and older.  I thing the new floating point zoom gesture will resolve this on the next version

**Comment by sonwh98** [comment] 2017-09-07 13:36
I'm building from master

**Comment by sonwh98** [comment] 2017-09-07 14:55
I see that in MultiTouchController.java, there's a performDragOrPinch . However, there is no way for me to call an onZoom because MultiTouchController has no reference to MapListener. To make it work will require major surgery.

I'd like to propose a different mechanism for handling events.  All events should generate a value that is put into a "message bus" event handlers will examine this message bus and process event based on a data values.  This will separate the generation of events from the consumption of events. I didn't invent this pattern. It comes from my experience using https://github.com/Day8/re-frame which is uses a common pattern in functional reactive programming

**Comment by sonwh98** [comment] 2017-09-07 19:12
I created a org.osmdroid.mercury.MessageBus. https://github.com/sonwh98/osmdroid/commit/875fc00bd5ad96a7c75c51b37019f73b434ca145

its in mercury package because mercury is the god messaging and communication.

what do you think?

I got scaling of InfoWindow view like by creating a MessageHandler like this:

``              
 MessageBus.registerMessageHandler("map/scale", MessageHandler { multiTouchScale: Any ->
                    val scale = multiTouchScale as Float
                    infowWindowView.scaleX = scale
                    infowWindowView.scaleY = scale
                    error("map/zoom value" + scale)
                    Object()
                })

**Comment by sonwh98** [comment] 2017-09-08 11:28
Can you point me to the floating point zoom gesture code? I'd like to see how it works

**Comment by spyhunter99** [comment] 2017-09-20 22:52
sure thing and sorry for the delay. it's currently on the master branch. 
There's a few things at play here

MapView is the android view. It handles the scaling, rotation, etc
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java

The gestures themselves are detected in the MultitouchController
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java 

During each movement/gesture, the MapView is notified. Specifically look for references to the `objectCanvas`
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java#L417
which leads you to here:
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L1201


https://github.com/osmdroid/osmdroid/issues/640 That's the zoom ticket

https://github.com/osmdroid/osmdroid/commit/ba74d6158904b9f247f4c80b395d6683cd82ff5e#diff-0bb50b730ea24896c5f4201928423da1
That's the commit that added floating point zoom

Finally, the contribution was by @monsieurtanuki who will probably have more insight into how it works.

**Comment by sonwh98** [comment] 2017-09-21 09:06
thanks. I'll take a look. What do you think about decoupling event producers from event consumers using a message bus? it can handle one-to-one and one-to-many. I think this will improve the design

**Comment by spyhunter99** [comment] 2017-09-22 00:45
I was never really happy with the away map events are fired because osmdroid only supports a single map events receiver. I've seen quite a few use cases whereby users of osmdroid put a shim in front of the events receiver so that multiple things can listen at the same time.

The messaging thing is closer to what https://github.com/missioncommand/emp3-android did along with http://cmapi.org/ Same type of deal whereby the map publishes events, such as the current extent to some kind of bus or an icon was tapped, icon drag events, etc. Multiple receivers are often needed to update displays, such as menus that display items on a layer, redrawing events, etc.

On the other hand, i'm somewhat against adding an additional dependencies for osmdroid unless the minsdk is reasonable, the library is relatively small and it is license compatible. Otherwise, someone would have to cook up a solution. It would likely be a large architectural and api shift, which would most likely cause some issues adopting the new code/version. This library was originally founded on mirroring a google maps like api.

**Comment by sonwh98** [comment] 2017-09-22 11:00
as long as changes to the api is 'appending' instead of 'removing', backwards compatibility is maintained without breaking existing clients.  a message bus can be introduced without breaking compatibility. any code that generates an event has to be changed to publish to the message bus too. in my example  sonwh98/osmdroid@875fc00 it is just one line of code to publish to the message bus at the point the event is being generated. there maybe many such places where events are generated but its just one line of code to publish to the message bus. the old api can be marked as deprecated and maintained as long as necessary while documentation is changed to inform people to use the message bus to publish and respond to events

**Comment by sonwh98** [comment] 2017-09-22 11:04
the jdk has https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html so building an aysnc messaging queue would not require more dependencies

**Comment by monsieurtanuki** [comment] 2017-12-16 15:07
@sonwh98 Should be fixed by #800. Could you give it a try?

The zoom used to be handled by a `Canvas` scaling during the pinch gesture, and at the end of the gesture the new zoom was computed as the product of the canvas scaling end zoom with the `MapView` zoom at the gesture start.

Now we don't use `Canvas` scaling anymore: we compute the floating zoom at each moment. Which is supposed to call `MapListener.onZoom`.

**Comment by monsieurtanuki** [comment] 2018-05-04 12:54
Fixed by #800.
@sonwh98 Feel free to reopen if needed.

**Closed by monsieurtanuki** 2018-05-04 12:54 UTC
