### ISSUE TITLE
MyLocationNewOverlay ZoomControlls

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#336] opened 2016-06-19 08:38 UTC
I have a MapView with MyLocationNewOverlay and the app uses Snackbar instead of Toast for temporary messaging to user. The zoom controls are played "on demand", i.e. not permanently, only when user interacts with the map.

As it turns out two bad things happen: 1. Zoom controls are shown on top of the Snackbar, making the the Snackbar content unreadable. 2. Zoom controls, while visible on top of the Snackbar, are actually inactive, i.e. touches are handled by the Snackbar. I'd like the zoom control to stay below the Snackbar. Haven't check the sources yet, to see what's happening.

**Comment by spyhunter99** [comment] 2016-06-19 11:51
easiest solution, disable osmdroid's zoom controls and use your buttons for zoom control. I

**Comment by InI4** [comment] 2016-06-22 06:05
Of course I could do this. But thus far I am perfectly satisfied with the zoom controls, osmdroid provides and I thought it might be worth to address it on lib level? And... less code is better code.

**Comment by spyhunter99** [comment] 2016-06-22 23:46
Agreed. Do you want to take a crack at it? The problem is obviously z indexing. The built in zoom controls are added programmatically to the view

**Comment by InI4** [comment] 2016-06-23 04:54
I am always busy with things and not particularly relyable in my open source contribution any more. But, ok, don't do anything, don't close this, feel free to check back with me, I am going to look into this.

**Comment by InI4** [comment] 2016-06-27 14:00
Whow ... what did I say. Looked somewhat into it. This is unkind stuff, burried more in Android than Osmdroid :-)

**Comment by spyhunter99** [comment] 2016-07-05 01:55
I think it's going to have to do with the order in which items are added to the view. try enabling the built in zoom controls in on resume.

**Comment by InI4** [comment] 2016-07-08 04:43
When you make those ZoomControls user controled i.e. either by a setting or dynamic on touch, this does not help.

**Comment by spyhunter99** [comment] 2016-07-08 10:55
that's a matter of implementation. I think you can set the relative
position to align bottom to the Snackbar. This should move it north of the
snackbar when it's visible

**Comment by spyhunter99** [comment] 2016-07-09 00:50
I'm closing this for now, since there's really not too much we can do. The built in zoom controls are provided by google and the alternative is to roll your own zoom buttons, which really isn't that hard to do. We even have an example for this. Feel free to continue the conversation and I'll help you the best i can.

**Closed by spyhunter99** 2016-07-09 00:50 UTC
