### ISSUE TITLE
please make the icon in MyLocationNewOverlay changeable

### ISSUE THREAD

**Issue by emdete** [osmdroid/osmdroid#127] opened 2015-06-17 16:06 UTC
it wold be nice if the icon that is used in MyLocationNewOverlay could be changed to meet the theme of the app. 

i can't even "overwrite" it by extending the class because it's final.

thank you! :)

**Comment by kurtzmarc** [comment] 2015-06-17 16:41
You can do this by creating your own ResourceProxy or by extending DefaultResourceProxyImpl.

**Comment by emdete** [comment] 2015-06-17 18:46
yes, that works but MyLocationNewOverlay is very pinned to the defaults (i found hardcoded sizes for the person icon in the code).

i would like to have a third state for "no current location" and have a better hotspot handling.

what do you think, would that be possible and desireable?

**Comment by kurtzmarc** [comment] 2015-06-17 18:48
What is hard-coded? You should be able to use mPersonHotspot to adjust the hotspot.

**Comment by emdete** [comment] 2015-06-17 19:06
in the code it says:

mPersonHotspot = new PointF(24.0f * mScale + 0.5f, 39.0f * mScale + 0.5f);

where do the values 24 and 39 come from and why is .5 added? it says it's the feet of the person... hm.

sure, i can set the hotspot, i figured that out and it works so far. still this is a bit ugly because it's on a completly different location in the program than the proxy is.

how could i add a third icon for a third condition? what if i don't like the condition "hasBearing"? here i would like to have more abstraction...

**Comment by kurtzmarc** [comment] 2015-06-17 19:48
Those values come from the default icon. They are adjustable based on your icon. Customization of the location icon has come up quite a few times. Maybe we can make it easier by:

1. Make the mPersonBitmap and mDirectionArrowBitmap non-final.
1. Use the actual mPersonBitmap width/height to calculate the initial mPersonHotspot. You're right - that shouldn't be hard-coded.

That should give a subclass enough control to change the drawn icon Bitmap and where it is drawn. Sound good?

**Comment by neilboyd** [comment] 2015-06-17 20:49
Duplicate of #99

**Comment by emdete** [comment] 2015-06-17 21:29
yes, you proposual would solve most of my desires ;)

but i have a 3-state: no-fix, no-move and moving (with direction).

i would suggest to have a member method deteriming image & hotspot for the current drawing. it can use the current state (bearing, accuracy, speed or lunar phase) to give back an image for that state. java can't return two objects but a reference can be a parameter. 

how do you like that?

**Comment by spyhunter99** [comment] 2015-10-18 00:25
since #99 is resolved, does that change meet your needs?

**Comment by spyhunter99** [comment] 2015-11-19 23:25
You can now change the icon on the fly and it can be overridden at construction time via the resource proxy. Please reopen if there's still an issue

**Closed by spyhunter99** 2015-11-19 23:25 UTC
Labels: waiting for feedback
